using Flowthru.Data.Validation;
using LanguageExt;
using static LanguageExt.Prelude;

namespace Flowthru.Data.Implementations;

/// <summary>
/// File-based catalog entry for binary file storage.
/// Stores byte[] content as binary files.
/// </summary>
/// <remarks>
/// <para>
/// <strong>Schema Type:</strong> Uses <c>byte[]</c> - the entire file content is loaded/saved as raw bytes.
/// </para>
/// <para>
/// <strong>Use Cases:</strong>
/// - Image files (PNG, JPEG, SVG, etc.)
/// - PDF reports generated by pipelines
/// - Compressed archives (ZIP, GZIP)
/// - Binary model files (ML models, serialized objects)
/// - Audio/video files
/// - Protocol buffer or binary serialization formats
/// </para>
/// <para>
/// <strong>Validation:</strong> Implements <see cref="IShallowInspectable{T}"/> and <see cref="IDeepInspectable{T}"/>
/// to validate binary files before pipeline execution:
/// </para>
/// <list type="bullet">
/// <item><strong>Shallow:</strong> Validates file exists and checks file signature (magic numbers)</item>
/// <item><strong>Deep:</strong> Validates entire file can be read without I/O errors</item>
/// </list>
/// <para>
/// <strong>Thread Safety:</strong> File I/O operations are inherently sequential. Concurrent access
/// may result in file locks or race conditions. Consider using separate file paths for concurrent writes.
/// </para>
/// <para>
/// <strong>Memory Considerations:</strong>
/// - Entire file loaded into memory on Load()
/// - For large files (>100MB), consider streaming approaches or chunked processing
/// - Monitor memory usage for pipelines processing many binary files
/// </para>
/// </remarks>
/// <example>
/// <code>
/// // In catalog - PNG image file
/// public ICatalogEntry&lt;byte[]&gt; VisualizationPng =>
///     GetOrCreateEntry(() => new BinaryFileCatalogEntry(
///         "visualization_png",
///         $"{BasePath}/reports/chart.png",
///         BinaryFileType.Png));
///
/// // In catalog - PDF report
/// public ICatalogEntry&lt;byte[]&gt; MonthlyReport =>
///     GetOrCreateEntry(() => new BinaryFileCatalogEntry(
///         "monthly_report",
///         $"{BasePath}/reports/monthly.pdf",
///         BinaryFileType.Pdf));
///
/// // In catalog - unknown binary type
/// public ICatalogEntry&lt;byte[]&gt; CustomBinary =>
///     GetOrCreateEntry(() => new BinaryFileCatalogEntry(
///         "custom_binary",
///         $"{BasePath}/data/model.bin"));
/// </code>
/// </example>
public class BinaryFileCatalogEntry
  : CatalogEntryBase<byte[]>,
    IShallowInspectable<byte[]>,
    IDeepInspectable<byte[]>
{
  private readonly string _filePath;
  private readonly BinaryFileType? _expectedFileType;

  /// <summary>
  /// Creates a new binary file catalog entry without type validation.
  /// </summary>
  /// <param name="key">Unique identifier for this catalog entry</param>
  /// <param name="filePath">Path to the file (absolute or relative to working directory)</param>
  public BinaryFileCatalogEntry(string key, string filePath)
    : this(key, filePath, expectedFileType: null) { }

  /// <summary>
  /// Creates a new binary file catalog entry with expected file type validation.
  /// </summary>
  /// <param name="key">Unique identifier for this catalog entry</param>
  /// <param name="filePath">Path to the file (absolute or relative to working directory)</param>
  /// <param name="expectedFileType">Expected file type for validation (null = no validation)</param>
  /// <remarks>
  /// When <paramref name="expectedFileType"/> is specified, shallow inspection will validate
  /// that the file's magic number matches the expected type. This helps catch errors where
  /// a file has the wrong extension or incorrect data was written.
  /// </remarks>
  public BinaryFileCatalogEntry(string key, string filePath, BinaryFileType? expectedFileType)
    : base(key)
  {
    _filePath = filePath ?? throw new ArgumentNullException(nameof(filePath));
    _expectedFileType = expectedFileType;
  }

  /// <summary>
  /// Gets the file path for this catalog entry.
  /// </summary>
  public string FilePath => _filePath;

  /// <summary>
  /// Gets the expected file type for validation (null if no validation).
  /// </summary>
  public BinaryFileType? ExpectedFileType => _expectedFileType;

  /// <inheritdoc/>
  public override IO<byte[]> Load()
  {
    return IO.liftAsync(async () =>
    {
      if (!File.Exists(_filePath))
      {
        throw new FileNotFoundException($"File not found for catalog entry '{Key}'", _filePath);
      }

      try
      {
        return await File.ReadAllBytesAsync(_filePath);
      }
      catch (IOException ex)
      {
        throw new InvalidOperationException(
          $"Failed to read binary file '{_filePath}' for catalog entry '{Key}'.",
          ex
        );
      }
    });
  }

  /// <inheritdoc/>
  public override IO<Unit> Save(byte[] data)
  {
    return IO.liftAsync(async () =>
    {
      if (data == null)
      {
        throw new ArgumentNullException(
          nameof(data),
          $"Cannot save null data to catalog entry '{Key}'"
        );
      }

      // Ensure directory exists
      var directory = Path.GetDirectoryName(_filePath);
      if (!string.IsNullOrEmpty(directory) && !Directory.Exists(directory))
      {
        Directory.CreateDirectory(directory);
      }

      await File.WriteAllBytesAsync(_filePath, data);
      return unit;
    });
  }

  /// <inheritdoc/>
  public override IO<bool> Exists()
  {
    return IO.liftAsync(async () => File.Exists(_filePath));
  }

  /// <inheritdoc/>
  public override IO<ValidationResult> InspectShallow(int sampleSize = 100)
  {
    return IO.liftAsync(async () =>
    {
      if (!File.Exists(_filePath))
      {
        return new ValidationResult(
          new[]
          {
            new ValidationError(Key, ValidationErrorType.NotFound, $"File not found: {_filePath}"),
          }
        );
      }

      try
      {
        // Read first 16 bytes for signature detection
        const int signatureSize = 16;
        byte[] signature;

        await using (var stream = File.OpenRead(_filePath))
        {
          var readSize = (int)Math.Min(stream.Length, signatureSize);
          signature = new byte[readSize];
          var bytesRead = 0;
          while (bytesRead < readSize)
          {
            var read = await stream.ReadAsync(signature.AsMemory(bytesRead, readSize - bytesRead));
            if (read == 0)
            {
              break;
            }
            bytesRead += read;
          }
        }

        // Detect file type from signature
        var detectedType = DetectFileType(signature);

        // If expected type is specified, validate it matches
        if (_expectedFileType.HasValue && detectedType != _expectedFileType.Value)
        {
          return new ValidationResult(
            new[]
            {
              new ValidationError(
                Key,
                ValidationErrorType.TypeMismatch,
                $"File type mismatch: Expected {_expectedFileType.Value} but detected {detectedType}",
                "File may be corrupted or have incorrect extension"
              ),
            }
          );
        }

        var fileSize = new FileInfo(_filePath).Length;
        return new ValidationResult(); // Success - no errors
      }
      catch (Exception ex)
      {
        return new ValidationResult(
          new[]
          {
            new ValidationError(
              Key,
              ValidationErrorType.InspectionFailure,
              "Failed to inspect file",
              ex.Message
            ),
          }
        );
      }
    });
  }

  /// <inheritdoc/>
  public override IO<ValidationResult> InspectDeep()
  {
    return IO.liftAsync(async () =>
    {
      try
      {
        // Read entire file to validate no I/O errors
        var content = await File.ReadAllBytesAsync(_filePath);

        if (content == null)
        {
          return new ValidationResult(
            new[]
            {
              new ValidationError(
                Key,
                ValidationErrorType.InspectionFailure,
                $"File read resulted in null: {_filePath}"
              ),
            }
          );
        }

        return new ValidationResult(); // Success - no errors
      }
      catch (IOException ex)
      {
        return new ValidationResult(
          new[]
          {
            new ValidationError(
              Key,
              ValidationErrorType.InspectionFailure,
              "I/O error reading file",
              ex.Message
            ),
          }
        );
      }
      catch (Exception ex)
      {
        return new ValidationResult(
          new[]
          {
            new ValidationError(
              Key,
              ValidationErrorType.InspectionFailure,
              "Failed to read entire file",
              ex.Message
            ),
          }
        );
      }
    });
  }

  /// <summary>
  /// Detects file type from binary signature (magic numbers).
  /// </summary>
  /// <param name="signature">First 16 bytes of the file</param>
  /// <returns>Detected file type, or Unknown if not recognized</returns>
  private static BinaryFileType DetectFileType(byte[] signature)
  {
    if (signature.Length < 4)
    {
      return BinaryFileType.Unknown;
    }

    return signature switch
    {
      // PNG: 89 50 4E 47 0D 0A 1A 0A
      [0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A, ..] => BinaryFileType.Png,
      // JPEG: FF D8 FF
      [0xFF, 0xD8, 0xFF, ..] => BinaryFileType.Jpeg,
      // GIF: 47 49 46 38
      [0x47, 0x49, 0x46, 0x38, ..] => BinaryFileType.Gif,
      // PDF: 25 50 44 46
      [0x25, 0x50, 0x44, 0x46, ..] => BinaryFileType.Pdf,
      // ZIP/JAR/DOCX: 50 4B 03 04 or 50 4B 05 06
      [0x50, 0x4B, 0x03 or 0x05, _, ..] => BinaryFileType.Zip,
      // GZIP: 1F 8B
      [0x1F, 0x8B, ..] => BinaryFileType.Gzip,
      // BMP: 42 4D
      [0x42, 0x4D, ..] => BinaryFileType.Bmp,
      // WebP: 52 49 46 46 ... 57 45 42 50
      [0x52, 0x49, 0x46, 0x46, _, _, _, _, 0x57, 0x45, 0x42, 0x50, ..] => BinaryFileType.WebP,
      // MP4: various, but often 66 74 79 70 at bytes 4-7
      [_, _, _, _, 0x66, 0x74, 0x79, 0x70, ..] => BinaryFileType.Mp4,
      _ => BinaryFileType.Unknown,
    };
  }
}

/// <summary>
/// Common binary file types that can be detected from file signatures.
/// </summary>
public enum BinaryFileType
{
  /// <summary>Unknown or unsupported file type</summary>
  Unknown,

  /// <summary>PNG image (89 50 4E 47)</summary>
  Png,

  /// <summary>JPEG image (FF D8 FF)</summary>
  Jpeg,

  /// <summary>GIF image (47 49 46 38)</summary>
  Gif,

  /// <summary>BMP image (42 4D)</summary>
  Bmp,

  /// <summary>WebP image (52 49 46 46 ... 57 45 42 50)</summary>
  WebP,

  /// <summary>PDF document (25 50 44 46)</summary>
  Pdf,

  /// <summary>ZIP archive (50 4B 03/05)</summary>
  Zip,

  /// <summary>GZIP compressed file (1F 8B)</summary>
  Gzip,

  /// <summary>MP4 video (66 74 79 70 at offset 4)</summary>
  Mp4,
}
