using System.Text;
using Flowthru.Data.Validation;
using LanguageExt;
using static LanguageExt.Prelude;

namespace Flowthru.Data.Implementations;

/// <summary>
/// File-based catalog entry for plaintext file storage.
/// Stores string content as text files.
/// </summary>
/// <remarks>
/// <para>
/// <strong>Schema Type:</strong> Uses <c>string</c> - the entire file content is loaded/saved as a single string.
/// </para>
/// <para>
/// <strong>Encoding Safety:</strong> Defaults to UTF-8 encoding. For binary or non-text files, encoding validation
/// will catch issues during inspection (if enabled). Use explicit encoding parameter for non-UTF-8 text files.
/// </para>
/// <para>
/// <strong>Use Cases:</strong>
/// - Markdown or HTML reports generated by pipelines
/// - Plaintext logs or diagnostic output
/// - Configuration files (JSON, YAML, XML as raw strings)
/// - Template files for text generation
/// - Unstructured text data for NLP ingestion
/// - Plotly JSON specifications
/// </para>
/// <para>
/// <strong>Validation:</strong> Implements <see cref="IShallowInspectable{T}"/> and <see cref="IDeepInspectable{T}"/>
/// to detect encoding issues before pipeline execution:
/// </para>
/// <list type="bullet">
/// <item><strong>Shallow:</strong> Validates file exists and first 4KB is valid in specified encoding</item>
/// <item><strong>Deep:</strong> Validates entire file content is valid in specified encoding</item>
/// </list>
/// <para>
/// <strong>Thread Safety:</strong> File I/O operations are inherently sequential. Concurrent access
/// may result in file locks or race conditions. Consider using separate file paths for concurrent writes.
/// </para>
/// <para>
/// <strong>Limitations:</strong>
/// - Not suitable for binary files (use BinaryFileCatalogEntry)
/// - Entire file loaded into memory (use dataset implementations for large tabular data)
/// - No built-in compression (use custom implementation if needed)
/// </para>
/// </remarks>
/// <example>
/// <code>
/// // In catalog - UTF-8 text file (default)
/// public ICatalogEntry&lt;string&gt; OutputReport =>
///     GetOrCreateEntry(() => new TextFileCatalogEntry(
///         "report",
///         $"{BasePath}/reports/output.md"));
/// 
/// // In catalog - specific encoding (e.g., Latin-1)
/// public ICatalogEntry&lt;string&gt; LegacyLog =>
///     GetOrCreateEntry(() => new TextFileCatalogEntry(
///         "legacy_log",
///         $"{BasePath}/logs/legacy.txt",
///         Encoding.Latin1));
/// 
/// // Usage in node
/// var reportContent = await catalog.OutputReport.Load().Run();
/// await catalog.OutputReport.Save("# Report\n\nGenerated content...").Run();
/// </code>
/// </example>
public class TextFileCatalogEntry : CatalogEntryBase<string>,
    IShallowInspectable<string>,
    IDeepInspectable<string> {
  private readonly string _filePath;
  private readonly Encoding _encoding;

  /// <summary>
  /// Creates a new text file catalog entry with UTF-8 encoding (default).
  /// </summary>
  /// <param name="key">Unique identifier for this catalog entry</param>
  /// <param name="filePath">Path to the file (absolute or relative to working directory)</param>
  public TextFileCatalogEntry(string key, string filePath)
      : this(key, filePath, Encoding.UTF8) {
  }

  /// <summary>
  /// Creates a new text file catalog entry with custom encoding.
  /// </summary>
  /// <param name="key">Unique identifier for this catalog entry</param>
  /// <param name="filePath">Path to the file (absolute or relative to working directory)</param>
  /// <param name="encoding">Text encoding to use for reading/writing the file</param>
  /// <remarks>
  /// Common encodings:
  /// - <see cref="Encoding.UTF8"/> - Default, recommended for new files
  /// - <see cref="Encoding.ASCII"/> - 7-bit ASCII only
  /// - <see cref="Encoding.Unicode"/> - UTF-16 Little Endian
  /// - <see cref="Encoding.UTF32"/> - UTF-32
  /// - <see cref="Encoding.Latin1"/> - ISO-8859-1, legacy Western European
  /// </remarks>
  public TextFileCatalogEntry(string key, string filePath, Encoding encoding)
      : base(key) {
    _filePath = filePath ?? throw new ArgumentNullException(nameof(filePath));
    _encoding = encoding ?? throw new ArgumentNullException(nameof(encoding));
  }

  /// <summary>
  /// Gets the file path for this catalog entry.
  /// </summary>
  public string FilePath => _filePath;

  /// <summary>
  /// Gets the text encoding used for reading/writing this file.
  /// </summary>
  public Encoding Encoding => _encoding;

  /// <inheritdoc/>
  public override Aff<string> Load() {
    return Aff(async () => {
      if (!File.Exists(_filePath)) {
        throw new FileNotFoundException(
            $"File not found for catalog entry '{Key}'", _filePath);
      }

      try {
        return await File.ReadAllTextAsync(_filePath, _encoding);
      } catch (DecoderFallbackException ex) {
        throw new InvalidOperationException(
            $"Failed to decode file '{_filePath}' as {_encoding.EncodingName} for catalog entry '{Key}'. " +
            "The file may contain binary data or use a different encoding. " +
            "Consider using a different encoding or validating the file with inspection.",
            ex);
      }
    });
  }

  /// <inheritdoc/>
  public override Aff<Unit> Save(string data) {
    return Aff(async () => {
      if (data == null) {
        throw new ArgumentNullException(nameof(data),
            $"Cannot save null data to catalog entry '{Key}'");
      }

      // Ensure directory exists
      var directory = Path.GetDirectoryName(_filePath);
      if (!string.IsNullOrEmpty(directory) && !Directory.Exists(directory)) {
        Directory.CreateDirectory(directory);
      }

      await File.WriteAllTextAsync(_filePath, data, _encoding);
      return unit;
    });
  }

  /// <inheritdoc/>
  public override Aff<bool> Exists() {
    return Aff(async () => File.Exists(_filePath));
  }

  /// <inheritdoc/>
  public override Aff<ValidationResult> InspectShallow(int sampleSize = 100) {
    return Aff(async () => {
      if (!File.Exists(_filePath)) {
        return new ValidationResult(new[] {
          new ValidationError(Key, ValidationErrorType.NotFound, $"File not found: {_filePath}")
        });
      }

      try {
        // Read first 4KB to check encoding validity
        const int previewSize = 4096;
        await using var stream = File.OpenRead(_filePath);
        var buffer = new byte[previewSize];
        var bytesRead = await stream.ReadAsync(buffer, 0, buffer.Length);

        // Try to decode the preview
        var preview = _encoding.GetString(buffer, 0, bytesRead);

        return new ValidationResult(); // Success - no errors
      } catch (DecoderFallbackException ex) {
        return new ValidationResult(new[] {
          new ValidationError(Key, ValidationErrorType.InvalidFormat,
            $"File contains invalid {_encoding.EncodingName} data", ex.Message)
        });
      } catch (Exception ex) {
        return new ValidationResult(new[] {
          new ValidationError(Key, ValidationErrorType.InspectionFailure, "Failed to read file", ex.Message)
        });
      }
    });
  }

  /// <inheritdoc/>
  public override Aff<ValidationResult> InspectDeep() {
    return Aff(async () => {
      if (!File.Exists(_filePath)) {
        return new ValidationResult(new[] {
          new ValidationError(Key, ValidationErrorType.NotFound, $"File not found: {_filePath}")
        });
      }

      try {
        // Read entire file to validate encoding
        var content = await File.ReadAllTextAsync(_filePath, _encoding);
        var fileSize = new FileInfo(_filePath).Length;

        return new ValidationResult(); // Success - no errors
      } catch (DecoderFallbackException ex) {
        return new ValidationResult(new[] {
          new ValidationError(Key, ValidationErrorType.InvalidFormat,
            $"File contains invalid {_encoding.EncodingName} data", ex.Message)
        });
      } catch (Exception ex) {
        return new ValidationResult(new[] {
          new ValidationError(Key, ValidationErrorType.InspectionFailure, "Failed to read file", ex.Message)
        });
      }
    });
  }
}
