using Flowthru.Data;
using UmapReferenceComparisons.Data._02_ModelOutputs.Schemas;

namespace UmapReferenceComparisons.Data;

public partial class Catalog
{
  // ============================================================================
  // Model Outputs - C# UMAP embeddings generated by pipeline nodes
  // ============================================================================

  public ICatalogEntry<IEnumerable<UmapEmbedding2D>> IrisCSharpOutput =>
    GetOrCreateEntry(
      () =>
        CatalogEntries.Enumerable.Parquet<UmapEmbedding2D>(
          label: "IrisCSharpOutput",
          filePath: $"{_basePath}/_02_ModelOutputs/Datasets/iris_csharp_output.parquet"
        )
    );

  public ICatalogEntry<IEnumerable<UmapEmbedding2D>> DigitsCSharpOutput =>
    GetOrCreateEntry(
      () =>
        CatalogEntries.Enumerable.Parquet<UmapEmbedding2D>(
          label: "DigitsCSharpOutput",
          filePath: $"{_basePath}/_02_ModelOutputs/Datasets/digits_csharp_output.parquet"
        )
    );

  public ICatalogEntry<IEnumerable<UmapEmbedding2D>> MnistCSharpOutput =>
    GetOrCreateEntry(
      () =>
        CatalogEntries.Enumerable.Parquet<UmapEmbedding2D>(
          label: "MnistCSharpOutput",
          filePath: $"{_basePath}/_02_ModelOutputs/Datasets/mnist_csharp_output.parquet"
        )
    );

  public ICatalogEntry<IEnumerable<UmapEmbedding2D>> FashionMnistCSharpOutput =>
    GetOrCreateEntry(
      () =>
        CatalogEntries.Enumerable.Parquet<UmapEmbedding2D>(
          label: "FashionMnistCSharpOutput",
          filePath: $"{_basePath}/_02_ModelOutputs/Datasets/fashion_mnist_csharp_output.parquet"
        )
    );

  public ICatalogEntry<IEnumerable<UmapEmbedding2D>> MnistTransformTrainCSharpOutput =>
    GetOrCreateEntry(
      () =>
        CatalogEntries.Enumerable.Parquet<UmapEmbedding2D>(
          label: "MnistTransformTrainCSharpOutput",
          filePath: $"{_basePath}/_02_ModelOutputs/Datasets/mnist_transform_train_csharp_output.parquet"
        )
    );

  public ICatalogEntry<IEnumerable<UmapEmbedding2D>> MnistTransformTestCSharpOutput =>
    GetOrCreateEntry(
      () =>
        CatalogEntries.Enumerable.Parquet<UmapEmbedding2D>(
          label: "MnistTransformTestCSharpOutput",
          filePath: $"{_basePath}/_02_ModelOutputs/Datasets/mnist_transform_test_csharp_output.parquet"
        )
    );
}
