using Flowthru.Core.Data;
using FlowthruCoverage.Data._01_Raw.Schemas;

namespace FlowthruCoverage.Data;

public partial class Catalog
{
  /// <summary>
  /// Staged Cobertura XML files, one per test or example project.
  /// Run the <c>_stage-coverage-xml</c> NX target before executing the pipeline.
  /// Each file is named <c>{ProjectName}.xml</c>.
  /// </summary>
  public IItem<Directory<CoberturaReport>> CoverageXmlFiles =>
    CreateItem(
      () =>
        ItemFactory.Enumerable.XmlDocuments<CoberturaReport>(
          label: "CoverageXmlFiles",
          directoryPath: $"{_basePath}/_01_Raw/Datasets"
        )
    );

  /// <summary>
  /// Repository project manifest generated by the <c>_generate-project-manifest</c> NX target.
  /// Maps each assembly name to its <c>ProjectType</c> and domain <c>Subgroup</c>.
  /// Used by <see cref="Flows.Reporting.Steps.ClassifyCoverageStep"/> to classify test columns
  /// and filter source-package rows.
  /// </summary>
  public IItem<IEnumerable<ProjectManifestEntry>> ProjectManifest =>
    CreateItem(
      () =>
        ItemFactory.Enumerable.Csv<ProjectManifestEntry>(
          label: "ProjectManifest",
          filePath: $"{_basePath}/_01_Raw/Datasets/project_manifest.csv"
        )
    );
}
