using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Flowthru.Core.SourceGenerators;

/// <summary>
/// Generates AddStep overloads for FlowBuilder supporting 0 to 8 inputs and 0 to 8 outputs.
/// Every (inputCount, outputCount) pair in the matrix emits three variants:
/// sync, async, and async-with-CancellationToken. There are no hand-written overloads —
/// this generator is the single source of truth for the AddStep surface.
/// </summary>
[Generator]
public class FlowBuilderGenerator : IIncrementalGenerator
{
  private const int MaxInputs = 8;
  private const int MaxOutputs = 8;

  private enum TransformVariant
  {
    Sync,
    Async,
    AsyncWithCancellation,
  }

  /// <inheritdoc/>
  public void Initialize(IncrementalGeneratorInitializationContext context)
  {
    // Only run this generator for the Flowthru assembly itself, not consuming projects
    var assemblyName = context.CompilationProvider.Select((c, _) => c.AssemblyName);

    context.RegisterSourceOutput(
      assemblyName,
      (ctx, name) =>
      {
        if (name != "Flowthru.Core")
        {
          return;
        }

        GenerateAddStepOverloads(ctx);
      }
    );
  }

  private static void GenerateAddStepOverloads(SourceProductionContext context)
  {
    var sb = new StringBuilder();

    // File header
    sb.AppendLine(
      """
      // <auto-generated/>
      #nullable enable

      using System;
      using System.Collections.Generic;
      using System.Threading;
      using System.Threading.Tasks;
      using Flowthru.Core.Graph;
      using Flowthru.Core.Steps;

      namespace Flowthru.Core.Flows;

      public partial class FlowBuilder
      {
      """
    );

    // Two API surfaces share the same overload body:
    //   plural: false → conventional `input:` / `output:` (singular) params,
    //                   empty side omitted. Full 0-8 × 0-8 matrix.
    //   plural: true  → explicit `inputs:` / `outputs:` (plural) params, empty
    //                   side typed as ValueTuple (caller passes
    //                   `default(ValueTuple)` as a deliberate signal). Emitted
    //                   only when at least one side is empty — when both sides
    //                   are populated the plural form would collide with the
    //                   singular signature.
    var variants = new[]
    {
      TransformVariant.Sync,
      TransformVariant.Async,
      TransformVariant.AsyncWithCancellation,
    };
    foreach (var plural in new[] { false, true })
    {
      for (int inputs = 0; inputs <= MaxInputs; inputs++)
      {
        for (int outputs = 0; outputs <= MaxOutputs; outputs++)
        {
          if (plural && inputs > 0 && outputs > 0)
          {
            continue;
          }

          foreach (var variant in variants)
          {
            GenerateAddStepOverload(sb, inputs, outputs, variant, plural);
            sb.AppendLine();
          }
        }
      }
    }

    sb.AppendLine("}");

    context.AddSource("FlowBuilder.Generated.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
  }

  /// <summary>
  /// Emits one AddStep overload. The <paramref name="plural"/> flag selects
  /// between two API surfaces that share the same body:
  /// <list type="bullet">
  /// <item><description>
  ///   <c>plural: false</c> — conventional <c>input:</c> / <c>output:</c>
  ///   singular parameters. Empty sides are omitted entirely.
  /// </description></item>
  /// <item><description>
  ///   <c>plural: true</c> — explicit <c>inputs:</c> / <c>outputs:</c> plural
  ///   parameters. Empty sides are typed as <see cref="System.ValueTuple"/>
  ///   so the caller passes <c>default(ValueTuple)</c> as a deliberate signal.
  /// </description></item>
  /// </list>
  /// </summary>
  private static void GenerateAddStepOverload(
    StringBuilder sb,
    int inputCount,
    int outputCount,
    TransformVariant variant,
    bool plural = false
  )
  {
    GenerateXmlDoc(sb, inputCount, outputCount, variant, plural);

    var typeParams = GenerateTypeParameters(inputCount, outputCount);
    var typeParamSection = string.IsNullOrEmpty(typeParams) ? "" : $"<{typeParams}>";
    var funcSignature = GenerateFuncSignature(inputCount, outputCount, variant);
    var inputParamName = plural ? "inputs" : "input";
    var outputParamName = plural ? "outputs" : "output";

    sb.AppendLine($"  public FlowBuilder AddStep{typeParamSection}(");
    sb.AppendLine("    string label,");
    sb.AppendLine($"    {funcSignature} transform,");

    // Singular form omits the empty side entirely; plural form types it as ValueTuple.
    if (inputCount > 0)
    {
      sb.AppendLine($"    {GenerateInputParameter(inputCount)} {inputParamName},");
    }
    else if (plural)
    {
      sb.AppendLine($"    ValueTuple {inputParamName},");
    }
    if (outputCount > 0)
    {
      sb.AppendLine($"    {GenerateOutputParameter(outputCount)} {outputParamName},");
    }
    else if (plural)
    {
      sb.AppendLine($"    ValueTuple {outputParamName},");
    }

    sb.AppendLine("    string description = \"\"");
    sb.AppendLine("  )");
    sb.AppendLine("  {");

    GenerateInputDeconstruction(sb, inputCount, inputParamName);
    GenerateOutputDeconstruction(sb, outputCount, outputParamName);

    var inputsArg = BuildNodeListExpression(inputCount, inputParamName, isInput: true);
    var outputsArg = BuildNodeListExpression(outputCount, outputParamName, isInput: false);

    sb.AppendLine(
      $$"""
          var flowStep = new FlowStep(
            label: label,
            description: description,
            step: transform,
            inputs: {{inputsArg}},
            outputs: {{outputsArg}},
            serviceDependencies: StepMetadataResolver.GetServiceDependencies(transform)
          );

          _flow.AddStep(flowStep);
          return this;
        }
      """
    );
  }

  /// <summary>
  /// Builds the C# expression used to populate the <c>FlowStep.inputs</c> or
  /// <c>FlowStep.outputs</c> list for a given arity. Reads as one of:
  /// <c>System.Array.Empty&lt;INode&gt;()</c> (arity 0),
  /// <c>new List&lt;INode&gt; { paramName }</c> (arity 1), or
  /// <c>new List&lt;INode&gt; { paramName1, paramName2, ... }</c> (arity ≥ 2,
  /// where each <c>paramNameN</c> is a deconstructed local).
  /// </summary>
  private static string BuildNodeListExpression(int count, string paramName, bool isInput)
  {
    if (count == 0)
    {
      return "System.Array.Empty<INode>()";
    }
    if (count == 1)
    {
      return $"new List<INode> {{ {paramName} }}";
    }
    var items = isInput ? GenerateInputsList(count) : GenerateOutputsList(count);
    return $"new List<INode> {{ {items} }}";
  }

  private static void GenerateXmlDoc(
    StringBuilder sb,
    int inputCount,
    int outputCount,
    TransformVariant variant,
    bool plural = false
  )
  {
    var variantDesc = variant switch
    {
      TransformVariant.Sync => " (synchronous transformation)",
      TransformVariant.Async => " (asynchronous transformation)",
      TransformVariant.AsyncWithCancellation =>
        " (asynchronous transformation with cancellation support)",
      _ => "",
    };

    var inputDesc =
      inputCount == 0
        ? "no inputs"
        : $"{inputCount} input{(inputCount == 1 ? "" : "s")}";
    var outputDesc =
      outputCount == 0
        ? "no outputs"
        : $"{outputCount} output{(outputCount == 1 ? "" : "s")}";

    sb.AppendLine("  /// <summary>");
    sb.AppendLine($"  /// Adds a step with {inputDesc} and {outputDesc}{variantDesc}.");
    sb.AppendLine("  /// </summary>");

    // Type parameter documentation
    for (int i = 1; i <= inputCount; i++)
    {
      sb.AppendLine($"  /// <typeparam name=\"TIn{i}\">Input type {i}</typeparam>");
    }
    for (int i = 1; i <= outputCount; i++)
    {
      sb.AppendLine($"  /// <typeparam name=\"TOut{i}\">Output type {i}</typeparam>");
    }

    var transformDesc = variant switch
    {
      TransformVariant.Sync => "Synchronous transformation function",
      TransformVariant.Async => "Asynchronous transformation function",
      TransformVariant.AsyncWithCancellation =>
        "Asynchronous transformation function with cancellation token",
      _ => "Transformation function",
    };

    sb.AppendLine("  /// <param name=\"label\">Unique identifier for this step</param>");
    sb.AppendLine($"  /// <param name=\"transform\">{transformDesc}</param>");

    if (plural)
    {
      sb.AppendLine(
        inputCount == 0
          ? "  /// <param name=\"inputs\">Explicit empty tuple (<c>()</c>) — the step has no inputs.</param>"
          : "  /// <param name=\"inputs\">Catalog item or tuple of catalog items providing input data.</param>"
      );
      sb.AppendLine(
        outputCount == 0
          ? "  /// <param name=\"outputs\">Explicit empty tuple (<c>()</c>) — the step has no outputs.</param>"
          : "  /// <param name=\"outputs\">Catalog item or tuple of catalog items to store output data.</param>"
      );
    }
    else
    {
      if (inputCount > 0)
      {
        sb.AppendLine(
          "  /// <param name=\"input\">Catalog item or tuple of catalog items providing input data</param>"
        );
      }
      if (outputCount > 0)
      {
        sb.AppendLine(
          "  /// <param name=\"output\">Catalog item or tuple of catalog items to store output data</param>"
        );
      }
    }
    sb.AppendLine(
      "  /// <param name=\"description\">Optional description of the step's purpose</param>"
    );
    sb.AppendLine("  /// <returns>This builder for method chaining</returns>");
  }

  private static string GenerateTypeParameters(int inputCount, int outputCount)
  {
    var parts = new List<string>();

    for (int i = 1; i <= inputCount; i++)
    {
      parts.Add($"TIn{i}");
    }
    for (int i = 1; i <= outputCount; i++)
    {
      parts.Add($"TOut{i}");
    }

    return string.Join(", ", parts);
  }

  private static string GenerateFuncSignature(
    int inputCount,
    int outputCount,
    TransformVariant variant
  )
  {
    string? inputType = inputCount switch
    {
      0 => null,
      1 => "TIn1",
      _ => $"({string.Join(", ", Enumerable.Range(1, inputCount).Select(i => $"TIn{i}"))})",
    };
    string? outputType = outputCount switch
    {
      0 => null,
      1 => "TOut1",
      _ => $"({string.Join(", ", Enumerable.Range(1, outputCount).Select(i => $"TOut{i}"))})",
    };

    if (variant == TransformVariant.Sync)
    {
      // Sync: Action[/<TIn>] for void-returning, Func<…> for value-returning.
      if (outputType is null)
      {
        return inputType is null ? "Action" : $"Action<{inputType}>";
      }
      return inputType is null ? $"Func<{outputType}>" : $"Func<{inputType}, {outputType}>";
    }

    // Async or async-with-CT: build a Func<…> with inputs, optional CT, then Task[/<TOut>].
    var returnType = outputType is null ? "Task" : $"Task<{outputType}>";
    var typeArgs = new List<string>();
    if (inputType is not null)
    {
      typeArgs.Add(inputType);
    }
    if (variant == TransformVariant.AsyncWithCancellation)
    {
      typeArgs.Add("CancellationToken");
    }
    typeArgs.Add(returnType);
    return $"Func<{string.Join(", ", typeArgs)}>";
  }

  private static string GenerateInputParameter(int inputCount)
  {
    if (inputCount == 1)
    {
      return "INode<TIn1>";
    }

    var types = string.Join(", ", Enumerable.Range(1, inputCount).Select(i => $"INode<TIn{i}>"));
    return $"({types})";
  }

  private static string GenerateOutputParameter(int outputCount)
  {
    if (outputCount == 1)
    {
      return "INode<TOut1>";
    }

    var types = string.Join(", ", Enumerable.Range(1, outputCount).Select(i => $"INode<TOut{i}>"));
    return $"({types})";
  }

  private static void GenerateInputDeconstruction(
    StringBuilder sb,
    int inputCount,
    string sourceName
  ) => GenerateTupleDeconstruction(sb, inputCount, "input", sourceName);

  private static void GenerateOutputDeconstruction(
    StringBuilder sb,
    int outputCount,
    string sourceName
  ) => GenerateTupleDeconstruction(sb, outputCount, "output", sourceName);

  /// <summary>
  /// Emits a deconstruction statement of the form
  /// <c>var (slot1, slot2, ...) = source;</c> when <paramref name="count"/> ≥ 2.
  /// For <paramref name="count"/> ≤ 1 the parameter is already a single value
  /// (or absent) and no deconstruction is needed.
  /// </summary>
  private static void GenerateTupleDeconstruction(
    StringBuilder sb,
    int count,
    string slotPrefix,
    string sourceName
  )
  {
    if (count <= 1)
    {
      return;
    }

    sb.Append("    var (");
    for (int i = 1; i <= count; i++)
    {
      if (i > 1)
      {
        sb.Append(", ");
      }
      sb.Append($"{slotPrefix}{i}");
    }
    sb.AppendLine($") = {sourceName};");
    sb.AppendLine();
  }

  private static string GenerateInputsList(int inputCount)
  {
    if (inputCount == 0)
    {
      return "";
    }

    if (inputCount == 1)
    {
      return "input";
    }

    return string.Join(", ", Enumerable.Range(1, inputCount).Select(i => $"input{i}"));
  }

  private static string GenerateOutputsList(int outputCount)
  {
    if (outputCount == 0)
    {
      return "";
    }

    if (outputCount == 1)
    {
      return "output";
    }

    return string.Join(", ", Enumerable.Range(1, outputCount).Select(i => $"output{i}"));
  }
}
