codecov:
  require_ci_to_pass: true
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: 80%
comment:
  layout: 'reach,diff,flags,components'
  behavior: default
  require_changes: false
flags:
  Flowthru.Analyzers.Tests:
    carryforward: true
  Flowthru.Extensions.EFCore.Tests:
    carryforward: true
  Flowthru.Extensions.GQL.Tests:
    carryforward: true
  Flowthru.Extensions.Python.Tests:
    carryforward: true
  Flowthru.Extensions.Spark.Tests:
    carryforward: true
  Flowthru.FUnit.Tests:
    carryforward: true
  Flowthru.Tests:
    carryforward: true
  Flowthru.Tests.Examples:
    carryforward: true
  Flowthru.Tests.Spark:
    carryforward: true
  Flowthru.Tests.Templates:
    carryforward: true
  KedroIrisFUnit:
    carryforward: true
  KedroSpaceflights.Custom:
    carryforward: true
  KedroSpaceflightsFUnit:
    carryforward: true
  SpaceflightsDistributed:
    carryforward: true
