scalar Decimal

type CompanyRecord {
  id: String!
  companyRating: Decimal!
  iataApproved: Boolean!
  companyLocation: String!
}

type ShuttleRecord {
  id: String!
  shuttleType: String!
  companyId: String!
  engines: Int!
  passengerCapacity: Int!
  crew: Int!
  price: Decimal!
  dCheckComplete: Boolean!
  moonClearanceComplete: Boolean!
}

type ReviewRecord {
  shuttleId: String!
  reviewScoresRating: Decimal!
}

input AddCompanyInput {
  id: String!
  companyRating: Decimal!
  iataApproved: Boolean!
  companyLocation: String!
}

input AddShuttleInput {
  id: String!
  shuttleType: String!
  companyId: String!
  engines: Int!
  passengerCapacity: Int!
  crew: Int!
  price: Decimal!
  dCheckComplete: Boolean!
  moonClearanceComplete: Boolean!
}

input AddReviewInput {
  shuttleId: String!
  reviewScoresRating: Decimal!
}

type Query {
  companies: [CompanyRecord!]!
  shuttles: [ShuttleRecord!]!
  reviews: [ReviewRecord!]!
}

type Mutation {
  addCompany(input: AddCompanyInput!): CompanyRecord!
  addShuttle(input: AddShuttleInput!): ShuttleRecord!
  addReview(input: AddReviewInput!): ReviewRecord!
}
