using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Flowthru.FUnit.SourceGenerators;

/// <summary>
/// Incremental source generator that:
/// <list type="number">
/// <item>Collects all classes annotated with <c>[FlowthruStep]</c> in the compilation.</item>
/// <item>Collects all methods annotated with <c>[StepTest(typeof(X))]</c> and maps them
///   to step types.</item>
/// <item>Emits a <c>StepTestRegistry</c> class mapping step types to test counts.</item>
/// <item>Emits a <c>FU001</c> warning for any <c>[FlowthruStep]</c> class with zero
///   <c>[StepTest]</c> methods in the project.</item>
/// </list>
/// </summary>
[Generator]
public class StepTestRegistryGenerator : IIncrementalGenerator
{
  private const string FlowthruStepAttributeFullName = "Flowthru.Core.Steps.FlowthruStepAttribute";
  private const string StepTestAttributeFullName = "Flowthru.FUnit.StepTestAttribute";

  private static readonly DiagnosticDescriptor Fu001 = new DiagnosticDescriptor(
    id: "FU001",
    title: "Step has no tests",
    messageFormat: "'{0}' is annotated with [FlowthruStep] but has no [StepTest] methods in this project. Pure function nodes without tests are potential failure hotspots.",
    category: "Flowthru.FUnit",
    defaultSeverity: DiagnosticSeverity.Warning,
    isEnabledByDefault: true
  );

  public void Initialize(IncrementalGeneratorInitializationContext context)
  {
    // Collect [FlowthruStep]-annotated class declarations
    var stepClasses = context
      .SyntaxProvider.CreateSyntaxProvider(
        predicate: static (node, _) =>
          node is ClassDeclarationSyntax c && c.AttributeLists.Count > 0,
        transform: static (ctx, _) =>
        {
          var classDecl = (ClassDeclarationSyntax)ctx.Node;
          var symbol = ctx.SemanticModel.GetDeclaredSymbol(classDecl) as INamedTypeSymbol;
          if (symbol is null)
            return null;

          var hasAttr = symbol
            .GetAttributes()
            .Any(a =>
              a.AttributeClass?.ToDisplayString() == "Flowthru.Core.Steps.FlowthruStepAttribute"
            );

          return hasAttr ? symbol : null;
        }
      )
      .Where(s => s is not null)
      .Collect();

    // Collect [StepTest(typeof(X))]-annotated methods → extract the step type argument
    var stepTestMethods = context
      .SyntaxProvider.CreateSyntaxProvider(
        predicate: static (node, _) =>
          node is MethodDeclarationSyntax m && m.AttributeLists.Count > 0,
        transform: static (ctx, _) =>
        {
          var method = (MethodDeclarationSyntax)ctx.Node;
          var symbol = ctx.SemanticModel.GetDeclaredSymbol(method) as IMethodSymbol;
          if (symbol is null)
            return null;

          foreach (var attr in symbol.GetAttributes())
          {
            if (attr.AttributeClass?.ToDisplayString() != "Flowthru.FUnit.StepTestAttribute")
              continue;

            // [StepTest(typeof(X))] — first constructor argument is the Type
            if (
              attr.ConstructorArguments.Length > 0
              && attr.ConstructorArguments[0].Value is INamedTypeSymbol stepType
            )
            {
              return stepType.ToDisplayString();
            }
          }

          return null;
        }
      )
      .Where(s => s is not null)
      .Collect();

    context.RegisterSourceOutput(
      stepClasses.Combine(stepTestMethods),
      (ctx, pair) => Execute(ctx, pair.Left!, pair.Right!)
    );
  }

  private static void Execute(
    SourceProductionContext context,
    IReadOnlyList<INamedTypeSymbol?> stepSymbols,
    IReadOnlyList<string?> testedStepNames
  )
  {
    // Build map: fully-qualified step name → test count
    var testCounts = testedStepNames
      .Where(n => n is not null)
      .GroupBy(n => n!)
      .ToDictionary(g => g.Key, g => g.Count());

    // Deduplicate step symbols (incremental pipelines may yield duplicates)
    var steps = stepSymbols
      .Where(s => s is not null)
      .Select(s => s!)
      .GroupBy(s => s.ToDisplayString())
      .Select(g => g.First())
      .ToList();

    if (steps.Count == 0)
      return;

    // Emit FU001 for each step with no tests
    foreach (var step in steps)
    {
      var fqn = step.ToDisplayString();
      if (!testCounts.TryGetValue(fqn, out var count) || count == 0)
      {
        var location = step.Locations.FirstOrDefault() ?? Location.None;
        context.ReportDiagnostic(Diagnostic.Create(Fu001, location, step.Name));
      }
    }

    // Emit StepTestRegistry
    var sb = new StringBuilder();
    sb.AppendLine(
      """
      // <auto-generated/>
      #nullable enable
      using System;
      using System.Collections.Generic;

      internal static class StepTestRegistry
      {
          public static IReadOnlyDictionary<Type, int> TestCounts { get; } =
              new Dictionary<Type, int>
              {
      """
    );

    foreach (var step in steps)
    {
      var fqn = step.ToDisplayString();
      var count = testCounts.TryGetValue(fqn, out var c) ? c : 0;
      sb.AppendLine($"          [typeof({fqn})] = {count},");
    }

    sb.AppendLine(
      """
              };
      }
      """
    );

    context.AddSource("StepTestRegistry.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
  }
}
