using Flowthru.Core.SourceGenerators.Flow;

namespace Flowthru.Core.SourceGenerators.Tests;

/// <summary>
/// Behavioural tests for <see cref="FlowBuilderGenerator"/>. The
/// generator emits the <c>AddStep&lt;…&gt;</c> overload matrix —
/// (1..5) × (1..5) inputs × outputs in three transform shapes, plus
/// zero-arity side-effect, source, and sink variants. It gates on the
/// presence of a <c>partial class Flowthru.Flow.FlowBuilder</c>
/// declaration in the consuming compilation so downstream consumer
/// projects (which only receive the analyzer reference) don't get a
/// free-floating partial.
/// </summary>
[TestFixture]
public class FlowBuilderGeneratorTests
{
  // Minimal partial-class stub that flips the generator's gating
  // predicate (ClassDeclarationSyntax named "FlowBuilder" with the
  // partial modifier, whose fully-qualified name resolves to
  // Flowthru.Flow.FlowBuilder). We don't need any members — the
  // generator only reads the symbol's display string.
  private const string FlowBuilderPartialStub = """
    namespace Flowthru.Flow
    {
      public partial class FlowBuilder { }
    }
    """;

  // ── Gating ─────────────────────────────────────────────────────────────

  [Test]
  public void NoFlowBuilderPartial_EmitsNothing()
  {
    // Consumer assemblies that reference the analyzer must NOT receive
    // a free-floating `partial class FlowBuilder` — without the stub
    // partial in source the generator stays silent.
    var result = AnalyzerTestHarness.RunGenerator(
      new FlowBuilderGenerator(),
      "namespace Sample { public class NotFlowBuilder { } }"
    );

    Assert.That(result.GeneratedSources, Is.Empty,
      "Generator should not emit unless a partial class Flowthru.Flow.FlowBuilder is in source. "
      + "Generated: " + string.Join(", ", result.GeneratedSources.Select(g => g.HintName)));
  }

  [Test]
  public void WrongNamespaceFlowBuilder_EmitsNothing()
  {
    // A partial class literally named FlowBuilder but in the wrong
    // namespace should NOT trigger emission — the generator's
    // transform compares the fully-qualified display string.
    var source = """
      namespace Some.Other.Place
      {
        public partial class FlowBuilder { }
      }
      """;

    var result = AnalyzerTestHarness.RunGenerator(new FlowBuilderGenerator(), source);

    Assert.That(result.GeneratedSources, Is.Empty,
      "Only Flowthru.Flow.FlowBuilder should trigger emission. Generated: "
      + string.Join(", ", result.GeneratedSources.Select(g => g.HintName)));
  }

  [Test]
  public void FlowBuilderPartialPresent_EmitsAtCanonicalHintName()
  {
    var result = AnalyzerTestHarness.RunGenerator(
      new FlowBuilderGenerator(),
      FlowBuilderPartialStub
    );

    Assert.That(result.GeneratedSources.Select(g => g.HintName), Has.Member("FlowBuilder.AddStep.g.cs"),
      "Generator should add the overload matrix under the expected hint name. Generated: "
      + string.Join(", ", result.GeneratedSources.Select(g => g.HintName)));
  }

  // ── Header / namespace ────────────────────────────────────────────────

  [Test]
  public void EmittedSource_HasAutoGeneratedHeaderAndExpectedNamespace()
  {
    var emitted = Emit();

    Assert.That(emitted, Does.Contain("// <auto-generated/>"));
    Assert.That(emitted, Does.Contain("#nullable enable"));
    Assert.That(emitted, Does.Contain("namespace Flowthru.Flow;"));
    Assert.That(emitted, Does.Contain("partial class FlowBuilder"));
  }

  // ── Matrix shape ──────────────────────────────────────────────────────

  [Test]
  public void EmittedMatrix_HasExpectedOverloadCount()
  {
    // The matrix is (1..5) × (1..5) × 3 transform shapes = 75 main
    // cells, plus 3 (0,0) side-effect variants, 5 × 3 = 15 source
    // variants, and 5 × 3 = 15 sink variants — 108 logical overloads.
    // Phase 8 doubles emission: every cell ships a visible form (no
    // codeVersion; identity resolved via StepMetadataResolver) AND a
    // hidden form ([EditorBrowsable(Never)], explicit codeVersion
    // parameter) so power users keep the escape hatch.
    // 108 × 2 = 216 generated overload signatures total.
    var emitted = Emit();
    var count = CountOccurrences(emitted, "public FlowBuilder AddStep");
    Assert.That(count, Is.EqualTo(216),
      "Expected (5x5x3 + 3 + 5x3 + 5x3) × 2 = 216 AddStep overloads (visible + hidden).");
  }

  [Test]
  public void EmittedMatrix_ContainsCornerCells()
  {
    var emitted = Emit();

    // 1×1 sync overload (no tuple parens — arity-1 collapses to the
    // underlying type both as TIn/TOut and as parameter shape).
    Assert.That(emitted,
      Does.Contain("public FlowBuilder AddStep<TIn1, TOut1>("),
      "The 1x1 overload should be emitted.");

    // 5×5 corner — proves MaxInputs and MaxOutputs are both 5.
    Assert.That(emitted,
      Does.Contain("public FlowBuilder AddStep<TIn1, TIn2, TIn3, TIn4, TIn5, TOut1, TOut2, TOut3, TOut4, TOut5>("),
      "The 5x5 overload should be emitted at the matrix bound.");

    // Mixed arity — 2x3 — proves the rectangular cells are emitted too.
    Assert.That(emitted,
      Does.Contain("public FlowBuilder AddStep<TIn1, TIn2, TOut1, TOut2, TOut3>("),
      "The 2x3 overload should be emitted.");
  }

  [Test]
  public void EmittedMatrix_DestructuresMultiInputsAndMultiOutputs()
  {
    var emitted = Emit();

    // The 2×N overloads destructure `inputs` into i1, i2 locals.
    Assert.That(emitted, Does.Contain("var (i1, i2) = inputs;"),
      "Multi-input overloads must destructure the inputs tuple.");
    // The N×2 overloads destructure `outputs` into o1, o2 locals.
    Assert.That(emitted, Does.Contain("var (o1, o2) = outputs;"),
      "Multi-output overloads must destructure the outputs tuple.");
  }

  [Test]
  public void EmittedMatrix_ArityOneUsesSingleAssignment()
  {
    var emitted = Emit();

    // Arity-1 inputs collapse to `var i1 = inputs;` rather than a
    // tuple deconstruction — the parameter is a bare IItem<TIn1>, not
    // a 1-tuple.
    Assert.That(emitted, Does.Contain("var i1 = inputs;"),
      "Arity-1 input overloads should assign directly, not destructure.");
    Assert.That(emitted, Does.Contain("var o1 = outputs;"),
      "Arity-1 output overloads should assign directly, not destructure.");
  }

  // ── Transform-shape variants ──────────────────────────────────────────

  [Test]
  public void EmittedMatrix_IncludesSyncAsyncAndAsyncCtVariants()
  {
    var emitted = Emit();

    // Sync: Func<TIn, TOut> — bare function signature.
    Assert.That(emitted, Does.Contain("global::System.Func<TIn1, TOut1> transform"),
      "Sync overload should expose a Func<TIn, TOut> transform parameter.");

    // Async: Func<TIn, Task<TOut>>.
    Assert.That(emitted,
      Does.Contain("global::System.Func<TIn1, global::System.Threading.Tasks.Task<TOut1>> transform"),
      "Async overload should expose a Func<TIn, Task<TOut>> transform.");

    // Async + CT: Func<TIn, CancellationToken, Task<TOut>>.
    Assert.That(emitted,
      Does.Contain("global::System.Func<TIn1, global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task<TOut1>> transform"),
      "Async-with-CT overload should accept a CancellationToken before the Task<TOut>.");
  }

  [Test]
  public void EmittedMatrix_LiftsSyncTransformViaFlowIo()
  {
    var emitted = Emit();
    // The body of every sync overload wraps the user transform in
    // FlowIO.Lift with a "step:" + label call.
    Assert.That(emitted, Does.Contain("global::Flowthru.Prelude.FlowIO.Lift"),
      "Sync overload bodies should wrap the transform via FlowIO.Lift.");
    Assert.That(emitted, Does.Contain("\"step:\" + label"),
      "The lifted scope should embed the step label.");
  }

  // ── Zero-arity special cases ──────────────────────────────────────────

  [Test]
  public void SideEffectVariants_ExposeActionAndFuncTaskTransforms()
  {
    var emitted = Emit();

    // (0, 0) sync visible: plain Action — no codeVersion (resolved
    // implicitly via StepMetadataResolver per Phase 8).
    Assert.That(emitted,
      Does.Contain("AddStep(string label, global::System.Action transform)"),
      "(0,0) side-effect visible overload should accept an Action transform.");

    // (0, 0) async visible: Func<Task>.
    Assert.That(emitted,
      Does.Contain("AddStep(string label, global::System.Func<global::System.Threading.Tasks.Task> transform)"),
      "(0,0) async visible overload should accept a Func<Task> transform.");

    // (0, 0) async + CT visible: Func<CancellationToken, Task>.
    Assert.That(emitted,
      Does.Contain("AddStep(string label, global::System.Func<global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task> transform)"),
      "(0,0) async-with-CT visible overload should accept Func<CancellationToken, Task>.");
  }

  [Test]
  public void ZeroArityBody_UsesEmptyItemArrays()
  {
    var emitted = Emit();
    // The (0,0) body plugs both IItem arrays with Array.Empty<IItem>().
    Assert.That(emitted,
      Does.Contain("global::System.Array.Empty<global::Flowthru.Data.Catalog.IItem>()"),
      "Zero-arity bodies must use Array.Empty<IItem>() for the missing side.");
  }

  [Test]
  public void SourceVariants_ExposeFuncOutputTransforms()
  {
    var emitted = Emit();

    // (0, 1) sync: Func<TOut1> — no input parameter.
    Assert.That(emitted, Does.Contain("global::System.Func<TOut1> transform"),
      "(0,n) source overload should expose Func<TOut> with no input parameter.");
  }

  [Test]
  public void SinkVariants_ExposeActionInputTransforms()
  {
    var emitted = Emit();

    // (1, 0) sync: Action<TIn1>.
    Assert.That(emitted, Does.Contain("global::System.Action<TIn1> transform"),
      "(m,0) sink overload should expose Action<TIn> with no output parameter.");
  }

  // ── Null-arg guard ────────────────────────────────────────────────────

  [Test]
  public void EveryOverload_GuardsNullTransform()
  {
    var emitted = Emit();
    var guardCount = CountOccurrences(
      emitted,
      "if (transform is null) throw new global::System.ArgumentNullException(nameof(transform));"
    );
    // Visible + hidden = 216 overloads, each guards a null transform.
    Assert.That(guardCount, Is.EqualTo(216),
      "Every emitted overload (visible + hidden) should guard a null transform.");
  }

  // ── CodeVersion threading (Phase 4) ───────────────────────────────────

  [Test]
  public void EveryHiddenOverload_AcceptsCodeVersionParameter()
  {
    var emitted = Emit();
    // Phase 8 split emission: visible overloads have no codeVersion
    // (the resolver finds it via StepMetadataResolver), while hidden
    // overloads — marked [EditorBrowsable(Never)] for power-user
    // access — accept an explicit `string? codeVersion`. The hidden
    // form makes the param required-named (no `= null` default) so
    // overload resolution between visible and hidden stays
    // unambiguous: a 4-positional call picks the visible form; a
    // call with `codeVersion: "..."` picks the hidden one.
    // Counting `string? codeVersion)` (no leading indent) catches both
    // multi-line emit shapes (typed matrix) and inline ones (zero-arity
    // side-effect cells) without false positives — visible overloads
    // omit the parameter entirely.
    var hiddenCount = CountOccurrences(emitted, "string? codeVersion)");
    Assert.That(hiddenCount, Is.EqualTo(108),
      "Every hidden AddStep overload (108 of 216 total) should accept the explicit codeVersion parameter.");
  }

  [Test]
  public void EveryOverload_ThreadsCodeVersionToStepConstructor()
  {
    var emitted = Emit();
    // Every emitted body should pass `codeVersion: codeVersion` to
    // the underlying Step<TIn, TOut> constructor. If a cell forgets
    // the assignment, downstream consumers see null and treat the
    // step as cache-miss — exactly the failure mode the threading
    // exists to prevent.
    var threadCount = CountOccurrences(emitted, "codeVersion: codeVersion");
    Assert.That(threadCount, Is.EqualTo(108),
      "Every emitted body should pass codeVersion: codeVersion to the Step constructor.");
  }

  // ── helpers ───────────────────────────────────────────────────────────

  private static string Emit()
  {
    var result = AnalyzerTestHarness.RunGenerator(
      new FlowBuilderGenerator(),
      FlowBuilderPartialStub
    );
    var match = result.GeneratedSources
      .FirstOrDefault(g => g.HintName == "FlowBuilder.AddStep.g.cs");
    Assert.That(match.Source, Is.Not.Null,
      "FlowBuilder.AddStep.g.cs should be emitted under the canonical hint name. Got: "
      + string.Join(", ", result.GeneratedSources.Select(g => g.HintName)));
    return match.Source;
  }

  private static int CountOccurrences(string haystack, string needle)
  {
    if (string.IsNullOrEmpty(needle)) return 0;
    var count = 0;
    var index = 0;
    while ((index = haystack.IndexOf(needle, index, StringComparison.Ordinal)) != -1)
    {
      count++;
      index += needle.Length;
    }
    return count;
  }
}
