using Flowthru.Core.SourceGenerators.Step;
using Flowthru.Step;

namespace Flowthru.Core.SourceGenerators.Tests;

/// <summary>
/// Behavioural tests for <see cref="StepMetadataGenerator"/>. The
/// generator emits a <c>{ClassName}_Metadata</c> companion next to every
/// <c>[FlowthruStep]</c>-decorated static class, exposing the class
/// name, label (defaulting to the class name), and <c>StepTraits</c>
/// derived from the attribute's named arguments.
/// </summary>
[TestFixture]
public class StepMetadataGeneratorTests
{
  // ── Default attribute ─────────────────────────────────────────────────

  [Test]
  public void BareFlowthruStep_EmitsMetadataWithClassNameAsLabel()
  {
    // No named arguments — Label defaults to the class name, both
    // trait booleans default to false.
    var source = """
      using Flowthru.Step;
      namespace Sample;

      [FlowthruStep]
      public static class FooStep { }
      """;

    var emitted = EmitFirstSource(source);

    Assert.That(emitted, Does.Contain("public static class FooStep_Metadata"),
      "Companion must be named `{ClassName}_Metadata`.");
    Assert.That(emitted, Does.Contain("public const string ClassName = \"FooStep\";"));
    Assert.That(emitted, Does.Contain("public const string Label = \"FooStep\";"),
      "Label should default to the class name when no Label= argument is given.");
    Assert.That(emitted, Does.Contain("IsIdempotent = false,"));
    Assert.That(emitted, Does.Contain("HasSideEffects = false,"));
  }

  // ── Explicit Label ────────────────────────────────────────────────────

  [Test]
  public void LabelOverride_AppearsInGeneratedConstant()
  {
    var source = """
      using Flowthru.Step;
      namespace Sample;

      [FlowthruStep(Label = "Custom Label")]
      public static class FooStep { }
      """;

    var emitted = EmitFirstSource(source);
    Assert.That(emitted, Does.Contain("public const string Label = \"Custom Label\";"),
      "The Label named argument should override the class-name default.");
    Assert.That(emitted, Does.Contain("public const string ClassName = \"FooStep\";"),
      "ClassName must still reflect the actual class name even when Label is overridden.");
  }

  // ── Trait flags ───────────────────────────────────────────────────────

  [Test]
  public void IsIdempotentTrue_AppearsInStepTraits()
  {
    var source = """
      using Flowthru.Step;
      namespace Sample;

      [FlowthruStep(IsIdempotent = true)]
      public static class FooStep { }
      """;

    var emitted = EmitFirstSource(source);
    Assert.That(emitted, Does.Contain("IsIdempotent = true,"));
    Assert.That(emitted, Does.Contain("HasSideEffects = false,"),
      "Unset named arguments must remain at their false default.");
  }

  [Test]
  public void HasSideEffectsTrue_AppearsInStepTraits()
  {
    var source = """
      using Flowthru.Step;
      namespace Sample;

      [FlowthruStep(HasSideEffects = true)]
      public static class FooStep { }
      """;

    var emitted = EmitFirstSource(source);
    Assert.That(emitted, Does.Contain("HasSideEffects = true,"));
    Assert.That(emitted, Does.Contain("IsIdempotent = false,"));
  }

  // ── Global namespace ──────────────────────────────────────────────────

  [Test]
  public void StepInGlobalNamespace_EmitsWithoutNamespaceBlockAndShortHintName()
  {
    var source = """
      using Flowthru.Step;

      [FlowthruStep]
      public static class GlobalStep { }
      """;

    var result = AnalyzerTestHarness.RunGenerator(
      new StepMetadataGenerator(),
      source,
      typeof(FlowthruStepAttribute).Assembly
    );

    var match = result.GeneratedSources
      .FirstOrDefault(g => g.HintName == "GlobalStep_Metadata.g.cs");
    Assert.That(match.Source, Is.Not.Null,
      "A global-namespace step should emit at the short hint name. Generated: "
      + string.Join(", ", result.GeneratedSources.Select(g => g.HintName)));
    Assert.That(match.Source, Does.Not.Contain("namespace "),
      "Generated file for a global-namespace step must not contain a namespace block.");
  }

  // ── Hint-name / header ────────────────────────────────────────────────

  [Test]
  public void EmittedSource_HasAutoGeneratedHeaderAndNamespacedHintName()
  {
    var source = """
      using Flowthru.Step;
      namespace Sample.Steps;

      [FlowthruStep]
      public static class FooStep { }
      """;

    var result = AnalyzerTestHarness.RunGenerator(
      new StepMetadataGenerator(),
      source,
      typeof(FlowthruStepAttribute).Assembly
    );

    var match = result.GeneratedSources
      .FirstOrDefault(g => g.HintName == "Sample.Steps.FooStep_Metadata.g.cs");
    Assert.That(match.Source, Is.Not.Null,
      "Hint name should be `{Namespace}.{ClassName}_Metadata.g.cs`. Generated: "
      + string.Join(", ", result.GeneratedSources.Select(g => g.HintName)));
    Assert.That(match.Source, Does.Contain("// <auto-generated/>"));
    Assert.That(match.Source, Does.Contain("#nullable enable"));
    Assert.That(match.Source, Does.Contain("namespace Sample.Steps;"));
  }

  // ── Label escaping ────────────────────────────────────────────────────

  [Test]
  public void LabelWithQuote_IsBackslashEscapedInGeneratedString()
  {
    var source = """"
      using Flowthru.Step;
      namespace Sample;

      [FlowthruStep(Label = "Has\"Quote")]
      public static class FooStep { }
      """";

    var emitted = EmitFirstSource(source);
    Assert.That(emitted, Does.Contain(@"Label = ""Has\""Quote"""),
      "Double quotes in the Label argument must be backslash-escaped.");
  }

  // ── helper ────────────────────────────────────────────────────────────

  private static string EmitFirstSource(string source)
  {
    var result = AnalyzerTestHarness.RunGenerator(
      new StepMetadataGenerator(),
      source,
      typeof(FlowthruStepAttribute).Assembly
    );
    Assert.That(result.GeneratedSources, Is.Not.Empty,
      "Expected at least one generated metadata companion. Diagnostics: "
      + string.Join("; ", result.Diagnostics.Select(d => d.GetMessage())));
    return result.GeneratedSources[0].Source;
  }
}
