using Flowthru.Core.Abstractions;

namespace FlowthruCoverage.Data._01_Raw.Schemas;

/// <summary>
/// One row from the project manifest CSV generated by the <c>_generate-project-manifest</c> NX target.
/// Maps an assembly name to its role in the repository and its domain subgroup.
/// </summary>
[FlowthruSchema]
public partial record ProjectManifestEntry
{
  /// <summary>Assembly / project name (e.g. <c>Flowthru.Core</c>, <c>Flowthru.Core.Tests</c>).</summary>
  public required string AssemblyName { get; init; }

  /// <summary>
  /// Role of the project:
  /// <list type="bullet">
  ///   <item><c>Library</c> — source package under <c>src/</c></item>
  ///   <item><c>LibraryTest</c> — unit/component test under <c>tests/core|extensions|misc</c></item>
  ///   <item><c>IntegrationTest</c> — integration or helper test under <c>tests/helpers|integration</c></item>
  ///   <item><c>Example</c> — example pipeline under <c>examples/</c></item>
  /// </list>
  /// </summary>
  public required string ProjectType { get; init; }

  /// <summary>
  /// Domain subgroup — <c>Core</c>, <c>Extensions</c>, or <c>Misc</c> for library and library-test
  /// projects; empty string for integration tests and examples.
  /// </summary>
  public required string Subgroup { get; init; }
}
