using Flowthru.Data.Schema;

namespace FlowthruCoverage.Data._01_Raw.Schemas;

/// <summary>
/// One row from the src-inventory CSV — a ground-truth listing of every
/// <c>.cs</c> file under <c>src/</c>, generated by the
/// <c>generate-src-inventory.sh</c> pre-pipeline script.
/// </summary>
/// <remarks>
/// <para>
/// The icicle step uses this to surface src projects whose test project has
/// produced no coverage data (e.g. the test project has zero <c>.cs</c>
/// files, so <c>dotnet test</c> emits no Cobertura output). Without the
/// inventory those projects would be invisible in the report; with it, they
/// appear as synthetic 0%-coverage nodes — visible at the top of the
/// cold-spots checklist.
/// </para>
/// <para>
/// <strong>Denominator caveat:</strong> <c>TotalLines</c> is a raw line count
/// (<c>wc -l</c>), not coverlet's "instrumentable lines" definition (which
/// excludes blanks, comments, and synthesized rows). Inventory rows therefore
/// have a slightly inflated denominator vs. covered rows, but the values are
/// internally consistent within a project — a project either uses coverlet's
/// numbers (when at least one test ran) or the inventory's, never a mix.
/// </para>
/// </remarks>
[FlowthruSchema]
public partial record SrcInventoryEntry
{
  /// <summary>Assembly / project name the file belongs to (e.g. <c>Flowthru.Core</c>).</summary>
  public required string AssemblyName { get; init; }

  /// <summary>Path to the <c>.cs</c> file relative to the project directory, using <c>/</c> separators.</summary>
  public required string RelativePath { get; init; }

  /// <summary>Raw line count of the file (<c>wc -l</c>).</summary>
  public required int TotalLines { get; init; }
}
