<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Flowthru/Flowthru.csproj" />
    <ProjectReference Include="../../src/Flowthru.Integrations.MLNet/Flowthru.Integrations.MLNet.csproj" />
    <ProjectReference Include="../../src/Flowthru.Extensions.ML/Flowthru.Extensions.ML.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.ML.Tokenizers" Version="1.0.3" />
    <PackageReference Include="Plotly.NET" Version="5.1.0" />
    <PackageReference Include="Plotly.NET.CSharp" Version="0.13.0" />
    <PackageReference Include="Plotly.NET.ImageExport" Version="6.1.0" />
  </ItemGroup>

</Project>
