using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Flowthru.Core.SourceGenerators.Catalog;

/// <summary>
/// Incremental source generator that emits <c>partial</c> property bodies
/// for catalog properties annotated with <c>[JsonItem("path")]</c>. The
/// generated body wires <c>ItemFactory.Enumerable.Json&lt;TRow&gt;</c>
/// or <c>ItemFactory.Singleton.Json&lt;T&gt;</c> with the property's
/// name as the label and the path from the attribute argument.
/// </summary>
[Generator]
public sealed class CatalogPropertyGenerator : IIncrementalGenerator
{
  private const string AttributeFullName = "Flowthru.Data.Catalog.JsonItemAttribute";

  /// <inheritdoc/>
  public void Initialize(IncrementalGeneratorInitializationContext context)
  {
    var candidates = context
      .SyntaxProvider.ForAttributeWithMetadataName(
        AttributeFullName,
        predicate: static (node, _) => node is PropertyDeclarationSyntax,
        transform: static (ctx, _) => ExtractCatalogProperty(ctx)
      )
      .Where(static info => info != null)
      .Select(static (info, _) => info!);

    // Group emissions by containing class so we emit one partial per class.
    var grouped = candidates.Collect();

    context.RegisterSourceOutput(
      grouped,
      static (ctx, items) => Emit(ctx, items)
    );
  }

  private static CatalogPropertyInfo? ExtractCatalogProperty(GeneratorAttributeSyntaxContext ctx)
  {
    if (ctx.TargetSymbol is not IPropertySymbol propertySymbol)
    {
      return null;
    }
    if (ctx.TargetNode is not PropertyDeclarationSyntax propertyDeclaration)
    {
      return null;
    }
    if (!propertyDeclaration.Modifiers.Any(SyntaxKind.PartialKeyword))
    {
      return null;
    }

    var containingType = propertySymbol.ContainingType;
    if (containingType is null)
    {
      return null;
    }

    // Path from the attribute argument.
    var attribute = propertySymbol
      .GetAttributes()
      .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == AttributeFullName);
    if (attribute is null || attribute.ConstructorArguments.Length == 0)
    {
      return null;
    }
    var path = attribute.ConstructorArguments[0].Value as string;
    if (string.IsNullOrEmpty(path))
    {
      return null;
    }

    // Determine the "shape" of the property: IItem<IEnumerable<TRow>> vs IItem<T>.
    if (propertySymbol.Type is not INamedTypeSymbol namedType)
    {
      return null;
    }
    if (namedType.ConstructedFrom.ToDisplayString() != "Flowthru.Data.Catalog.IItem<T>")
    {
      // Either not IItem<T> at all, or a derived form we don't recognize.
      return null;
    }
    if (namedType.TypeArguments.Length != 1)
    {
      return null;
    }

    var inner = namedType.TypeArguments[0];
    string schemaTypeFqn;
    bool isEnumerable;

    if (
      inner is INamedTypeSymbol innerNamed
      && innerNamed.IsGenericType
      && innerNamed.ConstructedFrom.ToDisplayString() == "System.Collections.Generic.IEnumerable<T>"
      && innerNamed.TypeArguments.Length == 1
    )
    {
      isEnumerable = true;
      schemaTypeFqn = innerNamed.TypeArguments[0].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
    }
    else
    {
      isEnumerable = false;
      schemaTypeFqn = inner.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
    }

    var namespaceName = containingType.ContainingNamespace.IsGlobalNamespace
      ? ""
      : containingType.ContainingNamespace.ToDisplayString();

    return new CatalogPropertyInfo(
      ContainingNamespace: namespaceName,
      ContainingTypeName: containingType.Name,
      ContainingTypeKind: GetTypeKind(containingType),
      PropertyName: propertySymbol.Name,
      SchemaTypeFqn: schemaTypeFqn,
      IsEnumerable: isEnumerable,
      Path: path!
    );
  }

  private static string GetTypeKind(INamedTypeSymbol type)
  {
    if (type.IsRecord)
    {
      return type.IsValueType ? "record struct" : "record";
    }
    if (type.IsValueType)
    {
      return "struct";
    }
    return "class";
  }

  private static void Emit(SourceProductionContext ctx, ImmutableArray<CatalogPropertyInfo> items)
  {
    if (items.IsDefaultOrEmpty)
    {
      return;
    }

    // Group by containing type so each class gets one generated partial file.
    var byType = items.GroupBy(i => (i.ContainingNamespace, i.ContainingTypeName, i.ContainingTypeKind));
    foreach (var group in byType)
    {
      var (ns, typeName, typeKind) = group.Key;
      var sb = new StringBuilder();
      sb.AppendLine("// <auto-generated/>");
      sb.AppendLine("#nullable enable");
      sb.AppendLine();
      sb.AppendLine("using global::Flowthru.Data.Catalog;");
      sb.AppendLine();
      if (!string.IsNullOrEmpty(ns))
      {
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
      }
      sb.AppendLine($"partial {typeKind} {typeName}");
      sb.AppendLine("{");

      foreach (var item in group)
      {
        var pathLiteral = SymbolDisplayFormatExt.EscapeStringLiteral(item.Path);
        if (item.IsEnumerable)
        {
          sb.AppendLine(
            $"  public partial global::Flowthru.Data.Catalog.IItem<global::System.Collections.Generic.IEnumerable<{item.SchemaTypeFqn}>> {item.PropertyName} =>"
          );
          sb.AppendLine(
            $"    CreateItem(() => global::Flowthru.Data.Catalog.ItemFactory.Enumerable.Json<{item.SchemaTypeFqn}>(\"{item.PropertyName}\", \"{pathLiteral}\"));"
          );
        }
        else
        {
          sb.AppendLine(
            $"  public partial global::Flowthru.Data.Catalog.IItem<{item.SchemaTypeFqn}> {item.PropertyName} =>"
          );
          sb.AppendLine(
            $"    CreateItem(() => global::Flowthru.Data.Catalog.ItemFactory.Singleton.Json<{item.SchemaTypeFqn}>(\"{item.PropertyName}\", \"{pathLiteral}\"));"
          );
        }
        sb.AppendLine();
      }

      sb.AppendLine("}");

      var fileName = string.IsNullOrEmpty(ns)
        ? $"{typeName}.JsonItems.g.cs"
        : $"{ns}.{typeName}.JsonItems.g.cs";
      ctx.AddSource(fileName, SourceText.From(sb.ToString(), Encoding.UTF8));
    }
  }
}

internal sealed record CatalogPropertyInfo(
  string ContainingNamespace,
  string ContainingTypeName,
  string ContainingTypeKind,
  string PropertyName,
  string SchemaTypeFqn,
  bool IsEnumerable,
  string Path
);

internal static class SymbolDisplayFormatExt
{
  public static string EscapeStringLiteral(string value) =>
    value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
