#!/usr/bin/env node
// Ingest docs/{tutorials,guides,explanation,reference} → src/content/docs/docs/
//
// `docs/` is the canonical source of truth. Two modes per file:
//
//   passthrough — file already starts with `---\n…\n---\n`. The frontmatter
//   is preserved verbatim, the body is left intact (no H1 stripping — the
//   author is expected to have written the page without a top-level H1, per
//   the convention in docs/CONTRIBUTING.md).
//
//   synthesize — no frontmatter present. ONLY allowed under reference/, since
//   that subtree is generated by docfx and ships without YAML. Title comes
//   from the first H1 (with docfx `<a id="…"></a>` anchors stripped);
//   description from the first non-heading paragraph. The H1 is removed
//   since Starlight renders the title from frontmatter.
//
// Hand-written sections (tutorials, guides, explanation) MUST carry their
// own frontmatter — synthesis there would mask contributors' missing-
// frontmatter mistakes. Missing frontmatter under those sections fails
// ingestion with a pointer to the source file.
//
// Either way, the docfx anchor pattern is stripped from the body since it
// also leaks into prose paragraphs in some generated pages.
//
// Source path is configurable via FLOWTHRU_DOCS_DIR. Default resolves to
// `<repo>/docs` when run from `src/website`.

import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import { existsSync, readFileSync, statSync } from "node:fs";
import { dirname, join, posix, relative, resolve, sep } from "node:path";
import { fileURLToPath } from "node:url";
import { maskCode } from "../../../scripts/lib/markdown-code.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const PROJECT_ROOT = resolve(HERE, "..");

const DOCS_SRC = resolve(
  process.env.FLOWTHRU_DOCS_DIR ?? resolve(PROJECT_ROOT, "..", "..", "docs"),
);
const DOCS_OUT = resolve(PROJECT_ROOT, "src", "content", "docs", "docs");

// reference/ is the only section where YAML frontmatter is synthesized; the
// hand-written sections must carry their own.
const SECTIONS = ["tutorials", "guides", "explanation", "reference"];
const SYNTHESIS_ALLOWED = new Set(["reference"]);

// Path fragments to exclude from ingestion. `reference/misc/external/` holds
// third-party repos kept around for cross-reference but not part of the
// Flowthru documentation surface.
const EXCLUDE_FRAGMENTS = [`${"reference"}/misc/external/`];

function isExcluded(absPath) {
  const norm = absPath.split(sep).join("/");
  return EXCLUDE_FRAGMENTS.some((frag) => norm.includes(`/${frag}`));
}

const FRONTMATTER_RE = /^---\r?\n([\s\S]*?)\r?\n---\r?\n?/;
const DOCFX_ANCHOR_RE = /<a\s+id="[^"]*"\s*><\/a>\s*/gi;

// ── Internal-link interceptor ────────────────────────────────────────
// Rewrites markdown links on their way into the Starlight content tree so they
// resolve on the deployed site regardless of how an author wrote them:
//   - resolves INSIDE docs/ → site-internal. Root-anchored `/docs/...` links
//     get the Astro base prefix + slug normalisation; file-relative links are
//     left untouched for Astro to resolve.
//   - ESCAPES docs/ (repo source: src/, examples/, CONTRIBUTING.md, …) →
//     rewritten to an absolute GitHub URL (blob for files, tree for dirs), so a
//     contributor page can reference source with a natural relative path and
//     still render correctly both on GitHub and on the deployed site.
// Links inside fenced or inline code are never touched. The companion lint
// (docs:_test:link-audit) enforces the authoring *style*; this makes any style
// resolve correctly, so site-correctness doesn't depend on the migration.
const REPO_ROOT = resolve(DOCS_SRC, "..");
const GH = "https://github.com/chaoticgoodcomputing/flowthru";
const GH_BRANCH = "main"; // docs deploy ref; mirrors the released docs
const SITE_BASE = (() => {
  try {
    const cfg = readFileSync(resolve(PROJECT_ROOT, "astro.config.mjs"), "utf8");
    const m = /base:\s*["']([^"']+)["']/.exec(cfg);
    return (m ? m[1] : "/flowthru").replace(/\/+$/, "");
  } catch {
    return "/flowthru";
  }
})();

function rewriteOneLink(url, relPath) {
  if (/^(?:[a-z][a-z0-9+.-]*:|#|\/\/)/i.test(url)) return url; // external / anchor-only / protocol-relative
  const hash = url.indexOf("#");
  const path = hash >= 0 ? url.slice(0, hash) : url;
  const anchor = hash >= 0 ? url.slice(hash) : "";
  if (!path) return url;

  let repoRel;
  if (path.startsWith("/")) {
    repoRel = posix.normalize(path.slice(1)); // repo-root-anchored
  } else {
    const fileDir = posix.dirname(relPath.split(sep).join("/"));
    repoRel = posix.normalize(posix.join("docs", fileDir, path));
  }
  const clean = repoRel.replace(/\/+$/, "");
  const inDocs = clean === "docs" || clean.startsWith("docs/");

  if (inDocs) {
    if (!path.startsWith("/")) return url; // relative in-docs link — Astro resolves it
    const slug = clean.replace(/\.md$/, "").replace(/\/index$/, "");
    return `${SITE_BASE}/${slug}/${anchor}`;
  }

  // Escapes docs/ → GitHub source URL.
  let isDir = false;
  try {
    isDir = existsSync(resolve(REPO_ROOT, clean)) && statSync(resolve(REPO_ROOT, clean)).isDirectory();
  } catch {
    /* unresolved on disk — default to blob */
  }
  return `${GH}/${isDir ? "tree" : "blob"}/${GH_BRANCH}/${clean}${anchor}`;
}

function rewriteLinks(body, relPath) {
  // Mask code once (length-preserving), then rewrite links in the ORIGINAL body
  // but skip any whose `](` token falls in a masked (code) region — so links in
  // fenced/inline code are left verbatim, while a prose link whose text holds
  // inline code (e.g. [`FlowIO`](/src/…)) is still rewritten (its `](` is intact).
  const masked = maskCode(body);
  return body.replace(/\]\(([^)]+)\)/g, (full, inner, offset) => {
    if (masked.substr(offset, 2) !== "](") return full; // inside code — leave verbatim
    const sp = inner.match(/^(\S+)(\s.*)?$/);
    if (!sp) return full;
    return `](${rewriteOneLink(sp[1], relPath)}${sp[2] || ""})`;
  });
}

async function walk(dir) {
  const out = [];
  let entries;
  try {
    entries = await readdir(dir, { withFileTypes: true });
  } catch (err) {
    if (err.code === "ENOENT") return out;
    throw err;
  }
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (isExcluded(full)) continue;
    if (entry.isDirectory()) {
      out.push(...(await walk(full)));
    } else if (entry.isFile() && entry.name.endsWith(".md")) {
      out.push(full);
    }
  }
  return out;
}

function passthrough(raw, relPath) {
  const match = FRONTMATTER_RE.exec(raw);
  if (!match) return null;
  let body = raw.slice(match[0].length).replace(DOCFX_ANCHOR_RE, "");
  body = rewriteLinks(body, relPath);
  return `---\n${match[1]}\n---\n${body}`;
}

function synthesize(raw) {
  const lines = raw.replace(/\r\n/g, "\n").split("\n");

  let h1Index = -1;
  let title = "Untitled";
  for (let i = 0; i < lines.length; i++) {
    const m = /^#\s+(.+?)\s*$/.exec(lines[i]);
    if (m) {
      h1Index = i;
      title = m[1].replace(DOCFX_ANCHOR_RE, "").trim();
      break;
    }
  }

  let description = "";
  for (let i = h1Index >= 0 ? h1Index + 1 : 0; i < lines.length; i++) {
    const line = lines[i].trim();
    if (!line) continue;
    if (line.startsWith("#")) continue;
    if (line.startsWith("---")) continue;
    if (line.startsWith("```")) continue;
    if (line.startsWith("<")) continue;
    description = line
      .replace(/`([^`]+)`/g, "$1")
      .replace(/\*\*([^*]+)\*\*/g, "$1")
      .replace(/\*([^*]+)\*/g, "$1")
      .replace(/\[([^\]]+)\]\([^)]+\)/g, "$1")
      .slice(0, 200)
      .trim();
    break;
  }

  if (h1Index >= 0) lines.splice(h1Index, 1);
  while (lines.length && lines[0].trim() === "") lines.shift();

  const fm = ["---", `title: ${JSON.stringify(title)}`];
  if (description) fm.push(`description: ${JSON.stringify(description)}`);
  fm.push("---", "");
  return fm.join("\n") + lines.join("\n").replace(DOCFX_ANCHOR_RE, "");
}

async function ingest() {
  // Only wipe the mirrored section directories — preserves any hand-authored
  // Starlight chrome that lives at the docs collection root (e.g. index.mdx).
  await mkdir(DOCS_OUT, { recursive: true });
  for (const section of SECTIONS) {
    await rm(join(DOCS_OUT, section), { recursive: true, force: true });
  }

  const stats = { passthrough: 0, synthesized: 0 };
  const missingFrontmatter = [];

  for (const section of SECTIONS) {
    const files = await walk(join(DOCS_SRC, section));
    for (const file of files) {
      const rel = relative(DOCS_SRC, file);
      const dest = join(DOCS_OUT, rel);
      await mkdir(dirname(dest), { recursive: true });
      const raw = await readFile(file, "utf8");

      const passed = passthrough(raw, rel);
      if (passed) {
        await writeFile(dest, passed, "utf8");
        stats.passthrough++;
        continue;
      }

      if (SYNTHESIS_ALLOWED.has(section)) {
        await writeFile(dest, synthesize(raw), "utf8");
        stats.synthesized++;
        continue;
      }

      missingFrontmatter.push(relative(resolve(PROJECT_ROOT, "..", ".."), file));
    }
  }

  if (missingFrontmatter.length) {
    console.error(
      `[ingest-docs] ${missingFrontmatter.length} hand-written page(s) missing YAML frontmatter:`,
    );
    for (const f of missingFrontmatter) console.error(`  ${f}`);
    console.error(
      "\nEvery page under docs/{tutorials,guides,explanation}/ must start with a `---` block.\nSee docs/CONTRIBUTING.md for the frontmatter contract.",
    );
    process.exit(1);
  }

  console.log(
    `[ingest-docs] ${stats.passthrough} passthrough, ${stats.synthesized} synthesized → ${DOCS_OUT}`,
  );
}

ingest().catch((err) => {
  console.error("[ingest-docs] failed:", err);
  process.exit(1);
});
