using Flowthru.Core.Data;
using UmapReferenceComparisons.Data._01_Raw.Schemas;

namespace UmapReferenceComparisons.Data;

public partial class Catalog
{
  // ============================================================================
  // Model Outputs - C# UMAP embeddings generated by pipeline nodes
  // ============================================================================

  public IItem<IEnumerable<UmapOutputRow>> IrisCSharpOutput =>
    CreateItem(
      () =>
        ItemFactory.Enumerable.Parquet<UmapOutputRow>(
          label: "IrisCSharpOutput",
          filePath: $"{_basePath}/_02_ModelOutputs/Datasets/iris_csharp_output.parquet"
        )
    );

  public IItem<IEnumerable<UmapOutputRow>> DigitsCSharpOutput =>
    CreateItem(
      () =>
        ItemFactory.Enumerable.Parquet<UmapOutputRow>(
          label: "DigitsCSharpOutput",
          filePath: $"{_basePath}/_02_ModelOutputs/Datasets/digits_csharp_output.parquet"
        )
    );

  public IItem<IEnumerable<UmapOutputRow>> MnistCSharpOutput =>
    CreateItem(
      () =>
        ItemFactory.Enumerable.Parquet<UmapOutputRow>(
          label: "MnistCSharpOutput",
          filePath: $"{_basePath}/_02_ModelOutputs/Datasets/mnist_csharp_output.parquet"
        )
    );

  public IItem<IEnumerable<UmapOutputRow>> FashionMnistCSharpOutput =>
    CreateItem(
      () =>
        ItemFactory.Enumerable.Parquet<UmapOutputRow>(
          label: "FashionMnistCSharpOutput",
          filePath: $"{_basePath}/_02_ModelOutputs/Datasets/fashion_mnist_csharp_output.parquet"
        )
    );

  public IItem<IEnumerable<UmapOutputRow>> MnistTransformTrainCSharpOutput =>
    CreateItem(
      () =>
        ItemFactory.Enumerable.Parquet<UmapOutputRow>(
          label: "MnistTransformTrainCSharpOutput",
          filePath: $"{_basePath}/_02_ModelOutputs/Datasets/mnist_transform_train_csharp_output.parquet"
        )
    );

  public IItem<IEnumerable<UmapOutputRow>> MnistTransformTestCSharpOutput =>
    CreateItem(
      () =>
        ItemFactory.Enumerable.Parquet<UmapOutputRow>(
          label: "MnistTransformTestCSharpOutput",
          filePath: $"{_basePath}/_02_ModelOutputs/Datasets/mnist_transform_test_csharp_output.parquet"
        )
    );
}
