<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" Version="4.12.0" />
    <PackageReference Include="NUnit" Version="4.2.2" />
    <PackageReference Include="Microsoft.ML" Version="4.0.3" />
    <PackageReference Include="LanguageExt.Core" Version="5.0.0-beta-54" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Flowthru" Version="*" />
    <!-- Needs direct reference to SourceGenerators for testing source generators -->
    <ProjectReference Include="../../src/Flowthru.SourceGenerators/Flowthru.SourceGenerators.csproj"
                      ReferenceOutputAssembly="true" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework" />
  </ItemGroup>

</Project>
