using Flowthru.Data.Catalog;
using Flowthru.Data.Storage.EFCore;
using SpaceflightsEFCore.Data._07_ModelOutput.Schemas;

namespace SpaceflightsEFCore.Data;

/// <summary>
/// Model output data layer: Model predictions and scores.
/// Contains results generated by trained models during inference.
/// </summary>
public partial class Catalog
{
  /// <summary>
  /// Evaluation metrics for the trained model (R², MAE, etc).
  /// </summary>
  public IItem<ModelMetrics> ModelMetrics =>
    CreateItem(
      () =>
        ItemFactory.Singleton.EFCore<ModelMetrics, SpaceflightsDbContext>(
          label: "ModelMetrics",
          contextFactory: _contextFactory
        )
    );

  /// <summary>
  /// Model predictions on the test set with actual vs predicted prices.
  /// </summary>
  public IItem<IEnumerable<ModelPredictions>> ModelPredictions =>
    CreateItem(
      () =>
        ItemFactory.Enumerable.EFCore<ModelPredictions, SpaceflightsDbContext>(
          label: "ModelPredictions",
          contextFactory: _contextFactory
        )
    );
}
