using Flowthru.Data;
using Flowthru.Extensions.EFCore.Data;
using KedroSpaceflights.Data._07_ModelOutput.Schemas;

namespace KedroSpaceflights.Data;

/// <summary>
/// Model output data layer: Model predictions and scores.
/// Contains results generated by trained models during inference.
/// </summary>
public partial class Catalog
{
  /// <summary>
  /// Evaluation metrics for the trained model (R², MAE, etc).
  /// </summary>
  public ICatalogEntry<ModelMetrics> ModelMetrics =>
    GetOrCreateEntry(
      () =>
        EFCoreCatalogEntries.Single.EFCore<ModelMetrics>(label: "ModelMetrics", context: _dbContext)
    );

  /// <summary>
  /// Model predictions on the test set with actual vs predicted prices.
  /// </summary>
  public ICatalogEntry<IEnumerable<ModelPredictions>> ModelPredictions =>
    GetOrCreateEntry(
      () =>
        EFCoreCatalogEntries.Enumerable.EFCore<ModelPredictions>(
          label: "ModelPredictions",
          context: _dbContext
        )
    );
}
