using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Flowthru.Core.SourceGenerators.Flow;

/// <summary>
/// Emits the typed <c>AddStep&lt;…&gt;</c> overload matrix on
/// <c>partial class FlowBuilder</c>. Per §2.4 / §4.3, each overload
/// takes a user transform plus the typed input/output items and
/// constructs an arity-agnostic <c>Step&lt;TIn, TOut&gt;</c>; the
/// generator's job is to spell out the load/save closures for each
/// combination of input/output arity and to provide sync, async, and
/// async-with-cancellation-token variants.
/// </summary>
/// <remarks>
/// <para>
/// Initial emission covers arity (1..5) × (1..5) inputs × outputs,
/// with three transform shapes per cell — 75 overloads total. The
/// matrix can be widened to (0..8)×(0..8) in a later phase without
/// changing this file's structure (just bump the limits and add the
/// zero-arity special case).
/// </para>
/// <para>
/// All emissions are unconditional — the generator does not depend on
/// any user syntax — so we use
/// <see cref="IncrementalGeneratorInitializationContext.RegisterPostInitializationOutput"/>.
/// </para>
/// </remarks>
[Generator]
public sealed class FlowBuilderGenerator : IIncrementalGenerator
{
  private const int MinInputs = 1;
  private const int MaxInputs = 5;
  private const int MinOutputs = 1;
  private const int MaxOutputs = 5;

  /// <inheritdoc/>
  public void Initialize(IncrementalGeneratorInitializationContext context)
  {
    // Only emit overloads when the current compilation defines the
    // FlowBuilder partial class — otherwise downstream test/extension
    // projects (which carry the source-gen as an analyzer reference)
    // would receive a free-floating `partial class FlowBuilder` that
    // can't see the hand-written `Add(IStepNode)`.
    var hasFlowBuilder = context
      .SyntaxProvider.CreateSyntaxProvider(
        predicate: static (node, _) =>
          node is ClassDeclarationSyntax cds
          && cds.Identifier.ValueText == "FlowBuilder"
          && cds.Modifiers.Any(SyntaxKind.PartialKeyword),
        transform: static (ctx, _) =>
        {
          var symbol = ctx.SemanticModel.GetDeclaredSymbol(ctx.Node);
          return symbol?.ToDisplayString() == "Flowthru.Flow.FlowBuilder";
        }
      )
      .Where(static match => match)
      .Collect();

    context.RegisterSourceOutput(hasFlowBuilder, static (ctx, matches) =>
    {
      if (matches.IsDefaultOrEmpty) return;
      var src = EmitOverloads();
      ctx.AddSource("FlowBuilder.AddStep.g.cs", SourceText.From(src, Encoding.UTF8));
    });
  }

  private static string EmitOverloads()
  {
    var sb = new StringBuilder();
    sb.AppendLine("// <auto-generated/>");
    sb.AppendLine("#nullable enable");
    sb.AppendLine();
    sb.AppendLine("using global::System;");
    sb.AppendLine("using global::System.Collections.Generic;");
    sb.AppendLine("using global::System.Threading;");
    sb.AppendLine("using global::System.Threading.Tasks;");
    sb.AppendLine("using global::Flowthru.Data.Catalog;");
    sb.AppendLine("using global::Flowthru.Prelude;");
    sb.AppendLine("using global::Flowthru.Step;");
    sb.AppendLine();
    sb.AppendLine("namespace Flowthru.Flow;");
    sb.AppendLine();
    sb.AppendLine("partial class FlowBuilder");
    sb.AppendLine("{");

    for (var m = MinInputs; m <= MaxInputs; m++)
    {
      for (var n = MinOutputs; n <= MaxOutputs; n++)
      {
        EmitOverloadCell(sb, m, n);
      }
    }

    // Zero-arity emissions — the (0, 0), (0, n>=1), and (m>=1, 0) shapes
    // need distinct transform signatures (Action / Action<TIn> / Func<TOut>)
    // and inline FlowUnit substitution for the missing side, so they're
    // emitted by dedicated helpers rather than the regular matrix loop.
    EmitSideEffectOverloadVariants(sb);
    for (var n = MinOutputs; n <= MaxOutputs; n++) EmitSourceOverloadVariants(sb, n);
    for (var m = MinInputs; m <= MaxInputs; m++) EmitSinkOverloadVariants(sb, m);

    sb.AppendLine("}");
    return sb.ToString();
  }

  private static void EmitOverloadCell(StringBuilder sb, int m, int n)
  {
    EmitSyncOverload(sb, m, n);
    EmitAsyncOverload(sb, m, n);
    EmitAsyncCtOverload(sb, m, n);
  }

  private static void EmitSyncOverload(StringBuilder sb, int m, int n)
  {
    var (tinTypeParams, toutTypeParams) = TypeParams(m, n);
    var tinType = TupleOrSingle("TIn", m);
    var toutType = TupleOrSingle("TOut", n);
    var typeParams = string.Join(", ", tinTypeParams.Concat(toutTypeParams));

    var inputParams = string.Join(", ",
      Enumerable.Range(1, m).Select(i => $"global::Flowthru.Data.Catalog.IItem<TIn{i}> input{i}"));
    var outputParams = string.Join(", ",
      Enumerable.Range(1, n).Select(i => $"global::Flowthru.Data.Catalog.IItem<TOut{i}> output{i}"));

    sb.AppendLine($"  public FlowBuilder AddStep<{typeParams}>(");
    sb.AppendLine("    string label,");
    sb.AppendLine($"    global::System.Func<{tinType}, {toutType}> transform,");
    sb.AppendLine($"    {inputParams},");
    sb.AppendLine($"    {outputParams})");
    sb.AppendLine("  {");
    EmitBody(sb, m, n, tinType, toutType,
      transformInvocation: $"global::Flowthru.Prelude.FlowIO.Lift<{toutType}>(() => transform(input), \"step:\" + label)");
    sb.AppendLine("  }");
    sb.AppendLine();
  }

  private static void EmitAsyncOverload(StringBuilder sb, int m, int n)
  {
    var (tinTypeParams, toutTypeParams) = TypeParams(m, n);
    var tinType = TupleOrSingle("TIn", m);
    var toutType = TupleOrSingle("TOut", n);
    var typeParams = string.Join(", ", tinTypeParams.Concat(toutTypeParams));

    var inputParams = string.Join(", ",
      Enumerable.Range(1, m).Select(i => $"global::Flowthru.Data.Catalog.IItem<TIn{i}> input{i}"));
    var outputParams = string.Join(", ",
      Enumerable.Range(1, n).Select(i => $"global::Flowthru.Data.Catalog.IItem<TOut{i}> output{i}"));

    sb.AppendLine($"  public FlowBuilder AddStep<{typeParams}>(");
    sb.AppendLine("    string label,");
    sb.AppendLine($"    global::System.Func<{tinType}, global::System.Threading.Tasks.Task<{toutType}>> transform,");
    sb.AppendLine($"    {inputParams},");
    sb.AppendLine($"    {outputParams})");
    sb.AppendLine("  {");
    EmitBody(sb, m, n, tinType, toutType,
      transformInvocation: "global::Flowthru.Prelude.FlowIO.LiftAsync(_ => transform(input))");
    sb.AppendLine("  }");
    sb.AppendLine();
  }

  private static void EmitAsyncCtOverload(StringBuilder sb, int m, int n)
  {
    var (tinTypeParams, toutTypeParams) = TypeParams(m, n);
    var tinType = TupleOrSingle("TIn", m);
    var toutType = TupleOrSingle("TOut", n);
    var typeParams = string.Join(", ", tinTypeParams.Concat(toutTypeParams));

    var inputParams = string.Join(", ",
      Enumerable.Range(1, m).Select(i => $"global::Flowthru.Data.Catalog.IItem<TIn{i}> input{i}"));
    var outputParams = string.Join(", ",
      Enumerable.Range(1, n).Select(i => $"global::Flowthru.Data.Catalog.IItem<TOut{i}> output{i}"));

    sb.AppendLine($"  public FlowBuilder AddStep<{typeParams}>(");
    sb.AppendLine("    string label,");
    sb.AppendLine($"    global::System.Func<{tinType}, global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task<{toutType}>> transform,");
    sb.AppendLine($"    {inputParams},");
    sb.AppendLine($"    {outputParams})");
    sb.AppendLine("  {");
    EmitBody(sb, m, n, tinType, toutType,
      transformInvocation: "global::Flowthru.Prelude.FlowIO.LiftAsync(ct => transform(input, ct))");
    sb.AppendLine("  }");
    sb.AppendLine();
  }

  private static (string[] tin, string[] tout) TypeParams(int m, int n) =>
    (
      Enumerable.Range(1, m).Select(i => $"TIn{i}").ToArray(),
      Enumerable.Range(1, n).Select(i => $"TOut{i}").ToArray()
    );

  private static string TupleOrSingle(string prefix, int arity)
  {
    if (arity == 1) return $"{prefix}1";
    var inner = string.Join(", ", Enumerable.Range(1, arity).Select(i => $"{prefix}{i}"));
    return $"({inner})";
  }

  /// <summary>
  /// Emit the body of a generated AddStep overload — the load
  /// closure that reads each input, the save closure that writes
  /// each output, and the call to <c>Add(new Step&lt;…&gt;(…))</c>.
  /// </summary>
  private static void EmitBody(
    StringBuilder sb,
    int m,
    int n,
    string tinType,
    string toutType,
    string transformInvocation
  )
  {
    // loadInputs closure — sequence inputs through bind
    sb.AppendLine($"    global::System.Func<global::Flowthru.Prelude.FlowIO<{tinType}>> loadInputs = () =>");
    if (m == 1)
    {
      sb.AppendLine("      input1.Load();");
    }
    else
    {
      sb.Append("      ");
      for (var i = 1; i <= m; i++)
      {
        sb.Append($"input{i}.Load().Bind(v{i} =>\n      ");
      }
      var values = string.Join(", ", Enumerable.Range(1, m).Select(i => $"v{i}"));
      sb.Append($"global::Flowthru.Prelude.FlowIO.Pure<{tinType}>(({values}))");
      for (var i = 1; i <= m; i++)
      {
        sb.Append(")");
      }
      sb.AppendLine(";");
    }

    // saveOutputs closure — sequence saves through bind
    sb.AppendLine($"    global::System.Func<{toutType}, global::Flowthru.Prelude.FlowIO<global::Flowthru.Prelude.FlowUnit>> saveOutputs = output =>");
    if (n == 1)
    {
      sb.AppendLine("      output1.Save(output);");
    }
    else
    {
      sb.Append("      ");
      for (var i = 1; i <= n; i++)
      {
        if (i < n)
        {
          sb.Append($"output{i}.Save(output.Item{i}).Bind(_ =>\n      ");
        }
        else
        {
          sb.Append($"output{i}.Save(output.Item{i})");
        }
      }
      for (var i = 1; i < n; i++)
      {
        sb.Append(")");
      }
      sb.AppendLine(";");
    }

    var inputsArray = string.Join(", ",
      Enumerable.Range(1, m).Select(i => $"input{i}"));
    var outputsArray = string.Join(", ",
      Enumerable.Range(1, n).Select(i => $"output{i}"));

    sb.AppendLine($"    return Add(new global::Flowthru.Step.Step<{tinType}, {toutType}>(");
    sb.AppendLine("      label,");
    sb.AppendLine($"      input => {transformInvocation},");
    sb.AppendLine($"      new global::Flowthru.Data.Catalog.IItem[] {{ {inputsArray} }},");
    sb.AppendLine($"      new global::Flowthru.Data.Catalog.IItem[] {{ {outputsArray} }},");
    sb.AppendLine("      loadInputs,");
    sb.AppendLine("      saveOutputs,");
    sb.AppendLine("      flowLabel: this.Label));");
  }

  // ────────────────────────────────────────────────────────────────────────
  // Zero-arity overloads
  //
  // (0, 0) — pure side-effect step (no IO, just runs the transform).
  // (0, n) — source step (no inputs, produces N outputs).
  // (m, 0) — sink step (consumes M inputs, no outputs).
  //
  // Each shape gets sync / async / async-with-CT variants. The missing
  // side is plugged with FlowUnit so the underlying Step<TIn, TOut>
  // shape stays uniform — TIn = FlowUnit when m=0, TOut = FlowUnit when
  // n=0. The transform is wrapped to handle the void return / ignored
  // parameter accordingly.
  // ────────────────────────────────────────────────────────────────────────

  private static void EmitSideEffectOverloadVariants(StringBuilder sb)
  {
    // (0, 0) — Action / Func<Task> / Func<CancellationToken, Task>.

    // Sync: Action.
    sb.AppendLine("  public FlowBuilder AddStep(string label, global::System.Action transform)");
    sb.AppendLine("  {");
    EmitZeroArityBody(sb,
      "FlowUnit",
      "FlowUnit",
      transformInvocation: "global::Flowthru.Prelude.FlowIO.Lift<global::Flowthru.Prelude.FlowUnit>(() => { transform(); return global::Flowthru.Prelude.FlowUnit.Default; }, \"step:\" + label)"
    );
    sb.AppendLine("  }");
    sb.AppendLine();

    // Async: Func<Task>.
    sb.AppendLine("  public FlowBuilder AddStep(string label, global::System.Func<global::System.Threading.Tasks.Task> transform)");
    sb.AppendLine("  {");
    EmitZeroArityBody(sb,
      "FlowUnit",
      "FlowUnit",
      transformInvocation: "global::Flowthru.Prelude.FlowIO.LiftAsync<global::Flowthru.Prelude.FlowUnit>(async _ => { await transform().ConfigureAwait(false); return global::Flowthru.Prelude.FlowUnit.Default; }, \"step:\" + label)"
    );
    sb.AppendLine("  }");
    sb.AppendLine();

    // Async + CT: Func<CancellationToken, Task>.
    sb.AppendLine("  public FlowBuilder AddStep(string label, global::System.Func<global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task> transform)");
    sb.AppendLine("  {");
    EmitZeroArityBody(sb,
      "FlowUnit",
      "FlowUnit",
      transformInvocation: "global::Flowthru.Prelude.FlowIO.LiftAsync<global::Flowthru.Prelude.FlowUnit>(async ct => { await transform(ct).ConfigureAwait(false); return global::Flowthru.Prelude.FlowUnit.Default; }, \"step:\" + label)"
    );
    sb.AppendLine("  }");
    sb.AppendLine();
  }

  private static void EmitSourceOverloadVariants(StringBuilder sb, int n)
  {
    // (0, n>=1) — produces N outputs from no inputs.
    var toutTypeParams = string.Join(", ", Enumerable.Range(1, n).Select(i => $"TOut{i}"));
    var toutType = TupleOrSingle("TOut", n);
    var outputParams = string.Join(", ",
      Enumerable.Range(1, n).Select(i => $"global::Flowthru.Data.Catalog.IItem<TOut{i}> output{i}"));

    // Sync: Func<TOut>.
    sb.AppendLine($"  public FlowBuilder AddStep<{toutTypeParams}>(");
    sb.AppendLine("    string label,");
    sb.AppendLine($"    global::System.Func<{toutType}> transform,");
    sb.AppendLine($"    {outputParams})");
    sb.AppendLine("  {");
    EmitSourceBody(sb, n, toutType,
      transformInvocation: $"global::Flowthru.Prelude.FlowIO.Lift<{toutType}>(() => transform(), \"step:\" + label)"
    );
    sb.AppendLine("  }");
    sb.AppendLine();

    // Async: Func<Task<TOut>>.
    sb.AppendLine($"  public FlowBuilder AddStep<{toutTypeParams}>(");
    sb.AppendLine("    string label,");
    sb.AppendLine($"    global::System.Func<global::System.Threading.Tasks.Task<{toutType}>> transform,");
    sb.AppendLine($"    {outputParams})");
    sb.AppendLine("  {");
    EmitSourceBody(sb, n, toutType,
      transformInvocation: $"global::Flowthru.Prelude.FlowIO.LiftAsync<{toutType}>(_ => transform(), \"step:\" + label)"
    );
    sb.AppendLine("  }");
    sb.AppendLine();

    // Async + CT: Func<CancellationToken, Task<TOut>>.
    sb.AppendLine($"  public FlowBuilder AddStep<{toutTypeParams}>(");
    sb.AppendLine("    string label,");
    sb.AppendLine($"    global::System.Func<global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task<{toutType}>> transform,");
    sb.AppendLine($"    {outputParams})");
    sb.AppendLine("  {");
    EmitSourceBody(sb, n, toutType,
      transformInvocation: $"global::Flowthru.Prelude.FlowIO.LiftAsync<{toutType}>(ct => transform(ct), \"step:\" + label)"
    );
    sb.AppendLine("  }");
    sb.AppendLine();
  }

  private static void EmitSinkOverloadVariants(StringBuilder sb, int m)
  {
    // (m>=1, 0) — consumes M inputs, no outputs.
    var tinTypeParams = string.Join(", ", Enumerable.Range(1, m).Select(i => $"TIn{i}"));
    var tinType = TupleOrSingle("TIn", m);
    var inputParams = string.Join(", ",
      Enumerable.Range(1, m).Select(i => $"global::Flowthru.Data.Catalog.IItem<TIn{i}> input{i}"));

    // Sync: Action<TIn>.
    sb.AppendLine($"  public FlowBuilder AddStep<{tinTypeParams}>(");
    sb.AppendLine("    string label,");
    sb.AppendLine($"    global::System.Action<{tinType}> transform,");
    sb.AppendLine($"    {inputParams})");
    sb.AppendLine("  {");
    EmitSinkBody(sb, m, tinType,
      transformInvocation: "global::Flowthru.Prelude.FlowIO.Lift<global::Flowthru.Prelude.FlowUnit>(() => { transform(input); return global::Flowthru.Prelude.FlowUnit.Default; }, \"step:\" + label)"
    );
    sb.AppendLine("  }");
    sb.AppendLine();

    // Async: Func<TIn, Task>.
    sb.AppendLine($"  public FlowBuilder AddStep<{tinTypeParams}>(");
    sb.AppendLine("    string label,");
    sb.AppendLine($"    global::System.Func<{tinType}, global::System.Threading.Tasks.Task> transform,");
    sb.AppendLine($"    {inputParams})");
    sb.AppendLine("  {");
    EmitSinkBody(sb, m, tinType,
      transformInvocation: "global::Flowthru.Prelude.FlowIO.LiftAsync<global::Flowthru.Prelude.FlowUnit>(async _ => { await transform(input).ConfigureAwait(false); return global::Flowthru.Prelude.FlowUnit.Default; }, \"step:\" + label)"
    );
    sb.AppendLine("  }");
    sb.AppendLine();

    // Async + CT: Func<TIn, CancellationToken, Task>.
    sb.AppendLine($"  public FlowBuilder AddStep<{tinTypeParams}>(");
    sb.AppendLine("    string label,");
    sb.AppendLine($"    global::System.Func<{tinType}, global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task> transform,");
    sb.AppendLine($"    {inputParams})");
    sb.AppendLine("  {");
    EmitSinkBody(sb, m, tinType,
      transformInvocation: "global::Flowthru.Prelude.FlowIO.LiftAsync<global::Flowthru.Prelude.FlowUnit>(async ct => { await transform(input, ct).ConfigureAwait(false); return global::Flowthru.Prelude.FlowUnit.Default; }, \"step:\" + label)"
    );
    sb.AppendLine("  }");
    sb.AppendLine();
  }

  /// <summary>
  /// Emit body for (0, 0) — neither inputs nor outputs. TIn = TOut =
  /// FlowUnit; loadInputs and saveOutputs are both no-ops.
  /// </summary>
  private static void EmitZeroArityBody(
    StringBuilder sb,
    string _tinType,
    string _toutType,
    string transformInvocation
  )
  {
    sb.AppendLine("    global::System.Func<global::Flowthru.Prelude.FlowIO<global::Flowthru.Prelude.FlowUnit>> loadInputs = () => global::Flowthru.Prelude.FlowIO.Pure(global::Flowthru.Prelude.FlowUnit.Default);");
    sb.AppendLine("    global::System.Func<global::Flowthru.Prelude.FlowUnit, global::Flowthru.Prelude.FlowIO<global::Flowthru.Prelude.FlowUnit>> saveOutputs = _ => global::Flowthru.Prelude.FlowIO.Pure(global::Flowthru.Prelude.FlowUnit.Default);");
    sb.AppendLine("    return Add(new global::Flowthru.Step.Step<global::Flowthru.Prelude.FlowUnit, global::Flowthru.Prelude.FlowUnit>(");
    sb.AppendLine("      label,");
    sb.AppendLine($"      input => {transformInvocation},");
    sb.AppendLine("      global::System.Array.Empty<global::Flowthru.Data.Catalog.IItem>(),");
    sb.AppendLine("      global::System.Array.Empty<global::Flowthru.Data.Catalog.IItem>(),");
    sb.AppendLine("      loadInputs,");
    sb.AppendLine("      saveOutputs,");
    sb.AppendLine("      flowLabel: this.Label));");
  }

  /// <summary>
  /// Emit body for (0, n) — source step. TIn = FlowUnit; saveOutputs
  /// fans out to N output items.
  /// </summary>
  private static void EmitSourceBody(
    StringBuilder sb,
    int n,
    string toutType,
    string transformInvocation
  )
  {
    sb.AppendLine("    global::System.Func<global::Flowthru.Prelude.FlowIO<global::Flowthru.Prelude.FlowUnit>> loadInputs = () => global::Flowthru.Prelude.FlowIO.Pure(global::Flowthru.Prelude.FlowUnit.Default);");
    sb.AppendLine($"    global::System.Func<{toutType}, global::Flowthru.Prelude.FlowIO<global::Flowthru.Prelude.FlowUnit>> saveOutputs = output =>");
    if (n == 1)
    {
      sb.AppendLine("      output1.Save(output);");
    }
    else
    {
      sb.Append("      ");
      for (var i = 1; i <= n; i++)
      {
        if (i < n) sb.Append($"output{i}.Save(output.Item{i}).Bind(_ =>\n      ");
        else sb.Append($"output{i}.Save(output.Item{i})");
      }
      for (var i = 1; i < n; i++) sb.Append(")");
      sb.AppendLine(";");
    }

    var outputsArray = string.Join(", ", Enumerable.Range(1, n).Select(i => $"output{i}"));
    sb.AppendLine($"    return Add(new global::Flowthru.Step.Step<global::Flowthru.Prelude.FlowUnit, {toutType}>(");
    sb.AppendLine("      label,");
    sb.AppendLine($"      input => {transformInvocation},");
    sb.AppendLine("      global::System.Array.Empty<global::Flowthru.Data.Catalog.IItem>(),");
    sb.AppendLine($"      new global::Flowthru.Data.Catalog.IItem[] {{ {outputsArray} }},");
    sb.AppendLine("      loadInputs,");
    sb.AppendLine("      saveOutputs,");
    sb.AppendLine("      flowLabel: this.Label));");
  }

  /// <summary>
  /// Emit body for (m, 0) — sink step. TOut = FlowUnit; saveOutputs
  /// is a no-op.
  /// </summary>
  private static void EmitSinkBody(
    StringBuilder sb,
    int m,
    string tinType,
    string transformInvocation
  )
  {
    sb.AppendLine($"    global::System.Func<global::Flowthru.Prelude.FlowIO<{tinType}>> loadInputs = () =>");
    if (m == 1)
    {
      sb.AppendLine("      input1.Load();");
    }
    else
    {
      sb.Append("      ");
      for (var i = 1; i <= m; i++) sb.Append($"input{i}.Load().Bind(v{i} =>\n      ");
      var values = string.Join(", ", Enumerable.Range(1, m).Select(i => $"v{i}"));
      sb.Append($"global::Flowthru.Prelude.FlowIO.Pure<{tinType}>(({values}))");
      for (var i = 1; i <= m; i++) sb.Append(")");
      sb.AppendLine(";");
    }

    sb.AppendLine("    global::System.Func<global::Flowthru.Prelude.FlowUnit, global::Flowthru.Prelude.FlowIO<global::Flowthru.Prelude.FlowUnit>> saveOutputs = _ => global::Flowthru.Prelude.FlowIO.Pure(global::Flowthru.Prelude.FlowUnit.Default);");
    var inputsArray = string.Join(", ", Enumerable.Range(1, m).Select(i => $"input{i}"));
    sb.AppendLine($"    return Add(new global::Flowthru.Step.Step<{tinType}, global::Flowthru.Prelude.FlowUnit>(");
    sb.AppendLine("      label,");
    sb.AppendLine($"      input => {transformInvocation},");
    sb.AppendLine($"      new global::Flowthru.Data.Catalog.IItem[] {{ {inputsArray} }},");
    sb.AppendLine("      global::System.Array.Empty<global::Flowthru.Data.Catalog.IItem>(),");
    sb.AppendLine("      loadInputs,");
    sb.AppendLine("      saveOutputs,");
    sb.AppendLine("      flowLabel: this.Label));");
  }
}
