using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Flowthru.Core.SourceGenerators.Flow;

/// <summary>
/// Emits the typed <c>AddStep&lt;…&gt;</c> overload matrix on
/// <c>partial class FlowBuilder</c>. Per §2.4 / §4.3, each overload
/// takes a user transform plus the typed input/output items and
/// constructs an arity-agnostic <c>Step&lt;TIn, TOut&gt;</c>; the
/// generator's job is to spell out the load/save closures for each
/// combination of input/output arity and to provide sync, async, and
/// async-with-cancellation-token variants.
/// </summary>
/// <remarks>
/// <para>
/// Initial emission covers arity (1..5) × (1..5) inputs × outputs,
/// with three transform shapes per cell — 75 overloads total. The
/// matrix can be widened to (0..8)×(0..8) in a later phase without
/// changing this file's structure (just bump the limits and add the
/// zero-arity special case).
/// </para>
/// <para>
/// All emissions are unconditional — the generator does not depend on
/// any user syntax — so we use
/// <see cref="IncrementalGeneratorInitializationContext.RegisterPostInitializationOutput"/>.
/// </para>
/// </remarks>
[Generator]
public sealed class FlowBuilderGenerator : IIncrementalGenerator
{
  private const int MinInputs = 1;
  private const int MaxInputs = 5;
  private const int MinOutputs = 1;
  private const int MaxOutputs = 5;

  /// <inheritdoc/>
  public void Initialize(IncrementalGeneratorInitializationContext context)
  {
    // Only emit overloads when the current compilation defines the
    // FlowBuilder partial class — otherwise downstream test/extension
    // projects (which carry the source-gen as an analyzer reference)
    // would receive a free-floating `partial class FlowBuilder` that
    // can't see the hand-written `Add(IStepNode)`.
    var hasFlowBuilder = context
      .SyntaxProvider.CreateSyntaxProvider(
        predicate: static (node, _) =>
          node is ClassDeclarationSyntax cds
          && cds.Identifier.ValueText == "FlowBuilder"
          && cds.Modifiers.Any(SyntaxKind.PartialKeyword),
        transform: static (ctx, _) =>
        {
          var symbol = ctx.SemanticModel.GetDeclaredSymbol(ctx.Node);
          return symbol?.ToDisplayString() == "Flowthru.Flow.FlowBuilder";
        }
      )
      .Where(static match => match)
      .Collect();

    context.RegisterSourceOutput(hasFlowBuilder, static (ctx, matches) =>
    {
      if (matches.IsDefaultOrEmpty) return;
      var src = EmitOverloads();
      ctx.AddSource("FlowBuilder.AddStep.g.cs", SourceText.From(src, Encoding.UTF8));
    });
  }

  private static string EmitOverloads()
  {
    var sb = new StringBuilder();
    sb.AppendLine("// <auto-generated/>");
    sb.AppendLine("#nullable enable");
    sb.AppendLine();
    sb.AppendLine("using global::System;");
    sb.AppendLine("using global::System.Collections.Generic;");
    sb.AppendLine("using global::System.Threading;");
    sb.AppendLine("using global::System.Threading.Tasks;");
    sb.AppendLine("using global::Flowthru.Data.Catalog;");
    sb.AppendLine("using global::Flowthru.Prelude;");
    sb.AppendLine("using global::Flowthru.Step;");
    sb.AppendLine();
    sb.AppendLine("namespace Flowthru.Flow;");
    sb.AppendLine();
    sb.AppendLine("partial class FlowBuilder");
    sb.AppendLine("{");

    for (var m = MinInputs; m <= MaxInputs; m++)
    {
      for (var n = MinOutputs; n <= MaxOutputs; n++)
      {
        EmitOverloadCell(sb, m, n);
      }
    }

    // Zero-arity emissions — the (0, 0), (0, n>=1), and (m>=1, 0) shapes
    // need distinct transform signatures (Action / Action<TIn> / Func<TOut>)
    // and inline FlowUnit substitution for the missing side, so they're
    // emitted by dedicated helpers rather than the regular matrix loop.
    // Each helper emits BOTH visible (no codeVersion) and hidden (with
    // codeVersion + [EditorBrowsable(Never)]) overloads, mirroring the
    // dual-emission pattern for the typed matrix above.
    EmitSideEffectOverloadVariants(sb, advanced: false);
    EmitSideEffectOverloadVariants(sb, advanced: true);
    for (var n = MinOutputs; n <= MaxOutputs; n++) EmitSourceOverloadVariants(sb, n, advanced: false);
    for (var n = MinOutputs; n <= MaxOutputs; n++) EmitSourceOverloadVariants(sb, n, advanced: true);
    for (var m = MinInputs; m <= MaxInputs; m++) EmitSinkOverloadVariants(sb, m, advanced: false);
    for (var m = MinInputs; m <= MaxInputs; m++) EmitSinkOverloadVariants(sb, m, advanced: true);

    sb.AppendLine("}");
    return sb.ToString();
  }

  private static void EmitOverloadCell(StringBuilder sb, int m, int n)
  {
    // Each cell emits two signatures per transform shape:
    //   - Visible (no codeVersion param; resolves via StepMetadataResolver)
    //   - Hidden (explicit codeVersion param; [EditorBrowsable(Never)])
    // Overload resolution is unambiguous because the hidden form makes
    // codeVersion a required-named parameter — a 4-positional call sees
    // only the visible form, while `codeVersion: "..."` selects the
    // hidden one.
    EmitSyncOverload(sb, m, n, advanced: false);
    EmitSyncOverload(sb, m, n, advanced: true);
    EmitAsyncOverload(sb, m, n, advanced: false);
    EmitAsyncOverload(sb, m, n, advanced: true);
    EmitAsyncCtOverload(sb, m, n, advanced: false);
    EmitAsyncCtOverload(sb, m, n, advanced: true);
  }

  /// <summary>
  /// Per Phase 8: visible overloads omit <c>codeVersion</c> entirely
  /// and resolve identity via <see cref="StepMetadataResolver"/> at
  /// the call site. Hidden overloads accept an explicit
  /// <c>codeVersion</c> and are decorated with
  /// <see cref="EditorBrowsableAttribute"/> so they don't pollute the
  /// completion list flow developers see.
  /// </summary>
  private const string HiddenAttribute =
    "[global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]";

  private static string CodeVersionExpr(bool advanced) =>
    advanced
      ? "codeVersion"
      : "global::Flowthru.Step.StepMetadataResolver.ResolveFromDelegate(transform)";

  private static void EmitSyncOverload(StringBuilder sb, int m, int n, bool advanced)
  {
    var (tinTypeParams, toutTypeParams) = TypeParams(m, n);
    var tinType = TupleOrSingle("TIn", m);
    var toutType = TupleOrSingle("TOut", n);
    var typeParams = string.Join(", ", tinTypeParams.Concat(toutTypeParams));
    var inputsParam = ItemTupleParam("TIn", m, "inputs");
    var outputsParam = ItemTupleParam("TOut", n, "outputs");

    if (advanced) sb.AppendLine($"  {HiddenAttribute}");
    sb.AppendLine($"  public FlowBuilder AddStep<{typeParams}>(");
    sb.AppendLine("    string label,");
    sb.AppendLine($"    global::System.Func<{tinType}, {toutType}> transform,");
    sb.AppendLine($"    {inputsParam},");
    sb.Append($"    {outputsParam}");
    sb.AppendLine(advanced ? "," : ")");
    if (advanced)
    {
      sb.AppendLine("    string? codeVersion)");
    }
    sb.AppendLine("  {");
    EmitBody(sb, m, n, tinType, toutType,
      codeVersionExpr: CodeVersionExpr(advanced),
      transformInvocation: $"global::Flowthru.Prelude.FlowIO.Lift<{toutType}>(() => transform(input), \"step:\" + label)");
    sb.AppendLine("  }");
    sb.AppendLine();
  }

  private static void EmitAsyncOverload(StringBuilder sb, int m, int n, bool advanced)
  {
    var (tinTypeParams, toutTypeParams) = TypeParams(m, n);
    var tinType = TupleOrSingle("TIn", m);
    var toutType = TupleOrSingle("TOut", n);
    var typeParams = string.Join(", ", tinTypeParams.Concat(toutTypeParams));
    var inputsParam = ItemTupleParam("TIn", m, "inputs");
    var outputsParam = ItemTupleParam("TOut", n, "outputs");

    if (advanced) sb.AppendLine($"  {HiddenAttribute}");
    sb.AppendLine($"  public FlowBuilder AddStep<{typeParams}>(");
    sb.AppendLine("    string label,");
    sb.AppendLine($"    global::System.Func<{tinType}, global::System.Threading.Tasks.Task<{toutType}>> transform,");
    sb.AppendLine($"    {inputsParam},");
    sb.Append($"    {outputsParam}");
    sb.AppendLine(advanced ? "," : ")");
    if (advanced)
    {
      sb.AppendLine("    string? codeVersion)");
    }
    sb.AppendLine("  {");
    EmitBody(sb, m, n, tinType, toutType,
      codeVersionExpr: CodeVersionExpr(advanced),
      transformInvocation: "global::Flowthru.Prelude.FlowIO.LiftAsync(_ => transform(input))");
    sb.AppendLine("  }");
    sb.AppendLine();
  }

  private static void EmitAsyncCtOverload(StringBuilder sb, int m, int n, bool advanced)
  {
    var (tinTypeParams, toutTypeParams) = TypeParams(m, n);
    var tinType = TupleOrSingle("TIn", m);
    var toutType = TupleOrSingle("TOut", n);
    var typeParams = string.Join(", ", tinTypeParams.Concat(toutTypeParams));
    var inputsParam = ItemTupleParam("TIn", m, "inputs");
    var outputsParam = ItemTupleParam("TOut", n, "outputs");

    if (advanced) sb.AppendLine($"  {HiddenAttribute}");
    sb.AppendLine($"  public FlowBuilder AddStep<{typeParams}>(");
    sb.AppendLine("    string label,");
    sb.AppendLine($"    global::System.Func<{tinType}, global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task<{toutType}>> transform,");
    sb.AppendLine($"    {inputsParam},");
    sb.Append($"    {outputsParam}");
    sb.AppendLine(advanced ? "," : ")");
    if (advanced)
    {
      sb.AppendLine("    string? codeVersion)");
    }
    sb.AppendLine("  {");
    EmitBody(sb, m, n, tinType, toutType,
      codeVersionExpr: CodeVersionExpr(advanced),
      transformInvocation: "global::Flowthru.Prelude.FlowIO.LiftAsync(ct => transform(input, ct))");
    sb.AppendLine("  }");
    sb.AppendLine();
  }

  /// <summary>
  /// Render the parameter declaration for a tuple-shaped <c>inputs</c> /
  /// <c>outputs</c> parameter. Arity 1 collapses to a single value (no
  /// surrounding tuple parens) since C# treats a 1-tuple as identical to
  /// the underlying type at the parameter signature.
  /// </summary>
  private static string ItemTupleParam(string typeParamPrefix, int arity, string name)
  {
    if (arity == 1)
      return $"global::Flowthru.Data.Catalog.IItem<{typeParamPrefix}1> {name}";
    var inner = string.Join(", ",
      Enumerable.Range(1, arity).Select(i => $"global::Flowthru.Data.Catalog.IItem<{typeParamPrefix}{i}>"));
    return $"({inner}) {name}";
  }

  private static (string[] tin, string[] tout) TypeParams(int m, int n) =>
    (
      Enumerable.Range(1, m).Select(i => $"TIn{i}").ToArray(),
      Enumerable.Range(1, n).Select(i => $"TOut{i}").ToArray()
    );

  private static string TupleOrSingle(string prefix, int arity)
  {
    if (arity == 1) return $"{prefix}1";
    var inner = string.Join(", ", Enumerable.Range(1, arity).Select(i => $"{prefix}{i}"));
    return $"({inner})";
  }

  /// <summary>
  /// Emit the body of a generated AddStep overload — the load
  /// closure that reads each input, the save closure that writes
  /// each output, and the call to <c>Add(new Step&lt;…&gt;(…))</c>.
  /// </summary>
  /// <remarks>
  /// Inputs are destructured from the <c>inputs</c> parameter (a tuple
  /// when m &gt; 1, a single <c>IItem</c> when m = 1) into local
  /// <c>i1..im</c> bindings; outputs likewise into <c>o1..on</c>. The
  /// load/save closures then sequence those locals via
  /// <c>FlowIO.Bind</c>, identical to the prior numbered-parameter
  /// shape — just sourced from the tuple's <c>.Item1</c>/<c>.Item2</c>
  /// projections instead of independent parameters.
  /// </remarks>
  private static void EmitBody(
    StringBuilder sb,
    int m,
    int n,
    string tinType,
    string toutType,
    string codeVersionExpr,
    string transformInvocation
  )
  {
    EmitTransformNullGuard(sb);
    // Destructure inputs / outputs into local IItem<TInI> / IItem<TOutI> bindings
    EmitInputDestructuring(sb, m);
    EmitOutputDestructuring(sb, n);

    // loadInputs closure — sequence inputs through bind
    sb.AppendLine($"    global::System.Func<global::Flowthru.Prelude.FlowIO<{tinType}>> loadInputs = () =>");
    if (m == 1)
    {
      sb.AppendLine("      i1.Load();");
    }
    else
    {
      sb.Append("      ");
      for (var i = 1; i <= m; i++)
      {
        sb.Append($"i{i}.Load().Bind(v{i} =>\n      ");
      }
      var values = string.Join(", ", Enumerable.Range(1, m).Select(i => $"v{i}"));
      sb.Append($"global::Flowthru.Prelude.FlowIO.Pure<{tinType}>(({values}))");
      for (var i = 1; i <= m; i++)
      {
        sb.Append(")");
      }
      sb.AppendLine(";");
    }

    // saveOutputs closure — sequence saves through bind
    sb.AppendLine($"    global::System.Func<{toutType}, global::Flowthru.Prelude.FlowIO<global::Flowthru.Prelude.FlowUnit>> saveOutputs = output =>");
    if (n == 1)
    {
      sb.AppendLine("      o1.Save(output);");
    }
    else
    {
      sb.Append("      ");
      for (var i = 1; i <= n; i++)
      {
        if (i < n)
        {
          sb.Append($"o{i}.Save(output.Item{i}).Bind(_ =>\n      ");
        }
        else
        {
          sb.Append($"o{i}.Save(output.Item{i})");
        }
      }
      for (var i = 1; i < n; i++)
      {
        sb.Append(")");
      }
      sb.AppendLine(";");
    }

    var inputsArray = string.Join(", ",
      Enumerable.Range(1, m).Select(i => $"i{i}"));
    var outputsArray = string.Join(", ",
      Enumerable.Range(1, n).Select(i => $"o{i}"));

    sb.AppendLine($"    return Add(new global::Flowthru.Step.Step<{tinType}, {toutType}>(");
    sb.AppendLine("      label,");
    sb.AppendLine($"      input => {transformInvocation},");
    sb.AppendLine($"      new global::Flowthru.Data.Catalog.IItem[] {{ {inputsArray} }},");
    sb.AppendLine($"      new global::Flowthru.Data.Catalog.IItem[] {{ {outputsArray} }},");
    sb.AppendLine("      loadInputs,");
    // FlowLabel is stamped centrally by FlowBuilder.Add via IStepNode.OnAddedToFlow;
    // emitting `flowLabel: this.Label` here would duplicate that responsibility.
    // codeVersion either comes from the StepMetadataResolver-driven
    // auto-discovery (visible overload) or is threaded verbatim from
    // the caller (hidden overload). Either way the step's identity
    // reaches IStepNode for the cache-plan phase.
    sb.AppendLine("      saveOutputs,");
    sb.AppendLine($"      codeVersion: {codeVersionExpr}));");
  }

  /// <summary>
  /// Emit a null-arg guard for the <c>transform</c> parameter. Null
  /// transforms are a caller-contract violation (programming error), so
  /// the standard .NET ArgumentNullException is the right shape — the
  /// no-throw analyzer (FT5002) whitelists Argument*Exception for
  /// precisely this case. Surfaces the error at the AddStep call site
  /// instead of deferring to the captured-closure dereference.
  /// </summary>
  private static void EmitTransformNullGuard(StringBuilder sb)
  {
    sb.AppendLine("    if (transform is null) throw new global::System.ArgumentNullException(nameof(transform));");
  }

  /// <summary>Destructure the <c>inputs</c> parameter into <c>i1..iM</c> locals.</summary>
  private static void EmitInputDestructuring(StringBuilder sb, int m)
  {
    if (m == 1)
    {
      sb.AppendLine("    var i1 = inputs;");
    }
    else
    {
      var lhs = string.Join(", ", Enumerable.Range(1, m).Select(i => $"i{i}"));
      sb.AppendLine($"    var ({lhs}) = inputs;");
    }
  }

  /// <summary>Destructure the <c>outputs</c> parameter into <c>o1..oN</c> locals.</summary>
  private static void EmitOutputDestructuring(StringBuilder sb, int n)
  {
    if (n == 1)
    {
      sb.AppendLine("    var o1 = outputs;");
    }
    else
    {
      var lhs = string.Join(", ", Enumerable.Range(1, n).Select(i => $"o{i}"));
      sb.AppendLine($"    var ({lhs}) = outputs;");
    }
  }

  // ────────────────────────────────────────────────────────────────────────
  // Zero-arity overloads
  //
  // (0, 0) — pure side-effect step (no IO, just runs the transform).
  // (0, n) — source step (no inputs, produces N outputs).
  // (m, 0) — sink step (consumes M inputs, no outputs).
  //
  // Each shape gets sync / async / async-with-CT variants. The missing
  // side is plugged with FlowUnit so the underlying Step<TIn, TOut>
  // shape stays uniform — TIn = FlowUnit when m=0, TOut = FlowUnit when
  // n=0. The transform is wrapped to handle the void return / ignored
  // parameter accordingly.
  // ────────────────────────────────────────────────────────────────────────

  private static void EmitSideEffectOverloadVariants(StringBuilder sb, bool advanced)
  {
    // (0, 0) — Action / Func<Task> / Func<CancellationToken, Task>.
    var signatureCodeVersion = advanced ? ", string? codeVersion" : "";
    var attr = advanced ? HiddenAttribute + " " : "";

    // Sync: Action.
    if (advanced) sb.AppendLine($"  {HiddenAttribute}");
    sb.AppendLine($"  public FlowBuilder AddStep(string label, global::System.Action transform{signatureCodeVersion})");
    sb.AppendLine("  {");
    EmitZeroArityBody(sb,
      "FlowUnit",
      "FlowUnit",
      codeVersionExpr: CodeVersionExpr(advanced),
      transformInvocation: "global::Flowthru.Prelude.FlowIO.Lift<global::Flowthru.Prelude.FlowUnit>(() => { transform(); return global::Flowthru.Prelude.FlowUnit.Default; }, \"step:\" + label)"
    );
    sb.AppendLine("  }");
    sb.AppendLine();

    // Async: Func<Task>.
    if (advanced) sb.AppendLine($"  {HiddenAttribute}");
    sb.AppendLine($"  public FlowBuilder AddStep(string label, global::System.Func<global::System.Threading.Tasks.Task> transform{signatureCodeVersion})");
    sb.AppendLine("  {");
    EmitZeroArityBody(sb,
      "FlowUnit",
      "FlowUnit",
      codeVersionExpr: CodeVersionExpr(advanced),
      transformInvocation: "global::Flowthru.Prelude.FlowIO.LiftAsync<global::Flowthru.Prelude.FlowUnit>(async _ => { await transform().ConfigureAwait(false); return global::Flowthru.Prelude.FlowUnit.Default; }, \"step:\" + label)"
    );
    sb.AppendLine("  }");
    sb.AppendLine();

    // Async + CT: Func<CancellationToken, Task>.
    if (advanced) sb.AppendLine($"  {HiddenAttribute}");
    sb.AppendLine($"  public FlowBuilder AddStep(string label, global::System.Func<global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task> transform{signatureCodeVersion})");
    sb.AppendLine("  {");
    EmitZeroArityBody(sb,
      "FlowUnit",
      "FlowUnit",
      codeVersionExpr: CodeVersionExpr(advanced),
      transformInvocation: "global::Flowthru.Prelude.FlowIO.LiftAsync<global::Flowthru.Prelude.FlowUnit>(async ct => { await transform(ct).ConfigureAwait(false); return global::Flowthru.Prelude.FlowUnit.Default; }, \"step:\" + label)"
    );
    sb.AppendLine("  }");
    sb.AppendLine();
  }

  private static void EmitSourceOverloadVariants(StringBuilder sb, int n, bool advanced)
  {
    // (0, n>=1) — produces N outputs from no inputs.
    var toutTypeParams = string.Join(", ", Enumerable.Range(1, n).Select(i => $"TOut{i}"));
    var toutType = TupleOrSingle("TOut", n);
    var outputsParam = ItemTupleParam("TOut", n, "outputs");

    // Sync: Func<TOut>.
    if (advanced) sb.AppendLine($"  {HiddenAttribute}");
    sb.AppendLine($"  public FlowBuilder AddStep<{toutTypeParams}>(");
    sb.AppendLine("    string label,");
    sb.AppendLine($"    global::System.Func<{toutType}> transform,");
    sb.Append($"    {outputsParam}");
    sb.AppendLine(advanced ? "," : ")");
    if (advanced) sb.AppendLine("    string? codeVersion)");
    sb.AppendLine("  {");
    EmitSourceBody(sb, n, toutType,
      codeVersionExpr: CodeVersionExpr(advanced),
      transformInvocation: $"global::Flowthru.Prelude.FlowIO.Lift<{toutType}>(() => transform(), \"step:\" + label)"
    );
    sb.AppendLine("  }");
    sb.AppendLine();

    // Async: Func<Task<TOut>>.
    if (advanced) sb.AppendLine($"  {HiddenAttribute}");
    sb.AppendLine($"  public FlowBuilder AddStep<{toutTypeParams}>(");
    sb.AppendLine("    string label,");
    sb.AppendLine($"    global::System.Func<global::System.Threading.Tasks.Task<{toutType}>> transform,");
    sb.Append($"    {outputsParam}");
    sb.AppendLine(advanced ? "," : ")");
    if (advanced) sb.AppendLine("    string? codeVersion)");
    sb.AppendLine("  {");
    EmitSourceBody(sb, n, toutType,
      codeVersionExpr: CodeVersionExpr(advanced),
      transformInvocation: $"global::Flowthru.Prelude.FlowIO.LiftAsync<{toutType}>(_ => transform(), \"step:\" + label)"
    );
    sb.AppendLine("  }");
    sb.AppendLine();

    // Async + CT: Func<CancellationToken, Task<TOut>>.
    if (advanced) sb.AppendLine($"  {HiddenAttribute}");
    sb.AppendLine($"  public FlowBuilder AddStep<{toutTypeParams}>(");
    sb.AppendLine("    string label,");
    sb.AppendLine($"    global::System.Func<global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task<{toutType}>> transform,");
    sb.Append($"    {outputsParam}");
    sb.AppendLine(advanced ? "," : ")");
    if (advanced) sb.AppendLine("    string? codeVersion)");
    sb.AppendLine("  {");
    EmitSourceBody(sb, n, toutType,
      codeVersionExpr: CodeVersionExpr(advanced),
      transformInvocation: $"global::Flowthru.Prelude.FlowIO.LiftAsync<{toutType}>(ct => transform(ct), \"step:\" + label)"
    );
    sb.AppendLine("  }");
    sb.AppendLine();
  }

  private static void EmitSinkOverloadVariants(StringBuilder sb, int m, bool advanced)
  {
    // (m>=1, 0) — consumes M inputs, no outputs.
    var tinTypeParams = string.Join(", ", Enumerable.Range(1, m).Select(i => $"TIn{i}"));
    var tinType = TupleOrSingle("TIn", m);
    var inputsParam = ItemTupleParam("TIn", m, "inputs");

    // Sync: Action<TIn>.
    if (advanced) sb.AppendLine($"  {HiddenAttribute}");
    sb.AppendLine($"  public FlowBuilder AddStep<{tinTypeParams}>(");
    sb.AppendLine("    string label,");
    sb.AppendLine($"    global::System.Action<{tinType}> transform,");
    sb.Append($"    {inputsParam}");
    sb.AppendLine(advanced ? "," : ")");
    if (advanced) sb.AppendLine("    string? codeVersion)");
    sb.AppendLine("  {");
    EmitSinkBody(sb, m, tinType,
      codeVersionExpr: CodeVersionExpr(advanced),
      transformInvocation: "global::Flowthru.Prelude.FlowIO.Lift<global::Flowthru.Prelude.FlowUnit>(() => { transform(input); return global::Flowthru.Prelude.FlowUnit.Default; }, \"step:\" + label)"
    );
    sb.AppendLine("  }");
    sb.AppendLine();

    // Async: Func<TIn, Task>.
    if (advanced) sb.AppendLine($"  {HiddenAttribute}");
    sb.AppendLine($"  public FlowBuilder AddStep<{tinTypeParams}>(");
    sb.AppendLine("    string label,");
    sb.AppendLine($"    global::System.Func<{tinType}, global::System.Threading.Tasks.Task> transform,");
    sb.Append($"    {inputsParam}");
    sb.AppendLine(advanced ? "," : ")");
    if (advanced) sb.AppendLine("    string? codeVersion)");
    sb.AppendLine("  {");
    EmitSinkBody(sb, m, tinType,
      codeVersionExpr: CodeVersionExpr(advanced),
      transformInvocation: "global::Flowthru.Prelude.FlowIO.LiftAsync<global::Flowthru.Prelude.FlowUnit>(async _ => { await transform(input).ConfigureAwait(false); return global::Flowthru.Prelude.FlowUnit.Default; }, \"step:\" + label)"
    );
    sb.AppendLine("  }");
    sb.AppendLine();

    // Async + CT: Func<TIn, CancellationToken, Task>.
    if (advanced) sb.AppendLine($"  {HiddenAttribute}");
    sb.AppendLine($"  public FlowBuilder AddStep<{tinTypeParams}>(");
    sb.AppendLine("    string label,");
    sb.AppendLine($"    global::System.Func<{tinType}, global::System.Threading.CancellationToken, global::System.Threading.Tasks.Task> transform,");
    sb.Append($"    {inputsParam}");
    sb.AppendLine(advanced ? "," : ")");
    if (advanced) sb.AppendLine("    string? codeVersion)");
    sb.AppendLine("  {");
    EmitSinkBody(sb, m, tinType,
      codeVersionExpr: CodeVersionExpr(advanced),
      transformInvocation: "global::Flowthru.Prelude.FlowIO.LiftAsync<global::Flowthru.Prelude.FlowUnit>(async ct => { await transform(input, ct).ConfigureAwait(false); return global::Flowthru.Prelude.FlowUnit.Default; }, \"step:\" + label)"
    );
    sb.AppendLine("  }");
    sb.AppendLine();
  }

  /// <summary>
  /// Emit body for (0, 0) — neither inputs nor outputs. TIn = TOut =
  /// FlowUnit; loadInputs and saveOutputs are both no-ops.
  /// </summary>
  private static void EmitZeroArityBody(
    StringBuilder sb,
    string _tinType,
    string _toutType,
    string codeVersionExpr,
    string transformInvocation
  )
  {
    EmitTransformNullGuard(sb);
    sb.AppendLine("    global::System.Func<global::Flowthru.Prelude.FlowIO<global::Flowthru.Prelude.FlowUnit>> loadInputs = () => global::Flowthru.Prelude.FlowIO.Pure(global::Flowthru.Prelude.FlowUnit.Default);");
    sb.AppendLine("    global::System.Func<global::Flowthru.Prelude.FlowUnit, global::Flowthru.Prelude.FlowIO<global::Flowthru.Prelude.FlowUnit>> saveOutputs = _ => global::Flowthru.Prelude.FlowIO.Pure(global::Flowthru.Prelude.FlowUnit.Default);");
    sb.AppendLine("    return Add(new global::Flowthru.Step.Step<global::Flowthru.Prelude.FlowUnit, global::Flowthru.Prelude.FlowUnit>(");
    sb.AppendLine("      label,");
    sb.AppendLine($"      input => {transformInvocation},");
    sb.AppendLine("      global::System.Array.Empty<global::Flowthru.Data.Catalog.IItem>(),");
    sb.AppendLine("      global::System.Array.Empty<global::Flowthru.Data.Catalog.IItem>(),");
    sb.AppendLine("      loadInputs,");
    // FlowLabel is stamped centrally by FlowBuilder.Add via IStepNode.OnAddedToFlow;
    // emitting `flowLabel: this.Label` here would duplicate that responsibility.
    sb.AppendLine("      saveOutputs,");
    sb.AppendLine($"      codeVersion: {codeVersionExpr}));");
  }

  /// <summary>
  /// Emit body for (0, n) — source step. TIn = FlowUnit; saveOutputs
  /// fans out to N output items destructured from <c>outputs</c>.
  /// </summary>
  private static void EmitSourceBody(
    StringBuilder sb,
    int n,
    string toutType,
    string codeVersionExpr,
    string transformInvocation
  )
  {
    EmitTransformNullGuard(sb);
    EmitOutputDestructuring(sb, n);
    sb.AppendLine("    global::System.Func<global::Flowthru.Prelude.FlowIO<global::Flowthru.Prelude.FlowUnit>> loadInputs = () => global::Flowthru.Prelude.FlowIO.Pure(global::Flowthru.Prelude.FlowUnit.Default);");
    sb.AppendLine($"    global::System.Func<{toutType}, global::Flowthru.Prelude.FlowIO<global::Flowthru.Prelude.FlowUnit>> saveOutputs = output =>");
    if (n == 1)
    {
      sb.AppendLine("      o1.Save(output);");
    }
    else
    {
      sb.Append("      ");
      for (var i = 1; i <= n; i++)
      {
        if (i < n) sb.Append($"o{i}.Save(output.Item{i}).Bind(_ =>\n      ");
        else sb.Append($"o{i}.Save(output.Item{i})");
      }
      for (var i = 1; i < n; i++) sb.Append(")");
      sb.AppendLine(";");
    }

    var outputsArray = string.Join(", ", Enumerable.Range(1, n).Select(i => $"o{i}"));
    sb.AppendLine($"    return Add(new global::Flowthru.Step.Step<global::Flowthru.Prelude.FlowUnit, {toutType}>(");
    sb.AppendLine("      label,");
    sb.AppendLine($"      input => {transformInvocation},");
    sb.AppendLine("      global::System.Array.Empty<global::Flowthru.Data.Catalog.IItem>(),");
    sb.AppendLine($"      new global::Flowthru.Data.Catalog.IItem[] {{ {outputsArray} }},");
    sb.AppendLine("      loadInputs,");
    // FlowLabel is stamped centrally by FlowBuilder.Add via IStepNode.OnAddedToFlow;
    // emitting `flowLabel: this.Label` here would duplicate that responsibility.
    sb.AppendLine("      saveOutputs,");
    sb.AppendLine($"      codeVersion: {codeVersionExpr}));");
  }

  /// <summary>
  /// Emit body for (m, 0) — sink step. TOut = FlowUnit; saveOutputs
  /// is a no-op. Inputs are destructured from <c>inputs</c>.
  /// </summary>
  private static void EmitSinkBody(
    StringBuilder sb,
    int m,
    string tinType,
    string codeVersionExpr,
    string transformInvocation
  )
  {
    EmitTransformNullGuard(sb);
    EmitInputDestructuring(sb, m);
    sb.AppendLine($"    global::System.Func<global::Flowthru.Prelude.FlowIO<{tinType}>> loadInputs = () =>");
    if (m == 1)
    {
      sb.AppendLine("      i1.Load();");
    }
    else
    {
      sb.Append("      ");
      for (var i = 1; i <= m; i++) sb.Append($"i{i}.Load().Bind(v{i} =>\n      ");
      var values = string.Join(", ", Enumerable.Range(1, m).Select(i => $"v{i}"));
      sb.Append($"global::Flowthru.Prelude.FlowIO.Pure<{tinType}>(({values}))");
      for (var i = 1; i <= m; i++) sb.Append(")");
      sb.AppendLine(";");
    }

    sb.AppendLine("    global::System.Func<global::Flowthru.Prelude.FlowUnit, global::Flowthru.Prelude.FlowIO<global::Flowthru.Prelude.FlowUnit>> saveOutputs = _ => global::Flowthru.Prelude.FlowIO.Pure(global::Flowthru.Prelude.FlowUnit.Default);");
    var inputsArray = string.Join(", ", Enumerable.Range(1, m).Select(i => $"i{i}"));
    sb.AppendLine($"    return Add(new global::Flowthru.Step.Step<{tinType}, global::Flowthru.Prelude.FlowUnit>(");
    sb.AppendLine("      label,");
    sb.AppendLine($"      input => {transformInvocation},");
    sb.AppendLine($"      new global::Flowthru.Data.Catalog.IItem[] {{ {inputsArray} }},");
    sb.AppendLine("      global::System.Array.Empty<global::Flowthru.Data.Catalog.IItem>(),");
    sb.AppendLine("      loadInputs,");
    // FlowLabel is stamped centrally by FlowBuilder.Add via IStepNode.OnAddedToFlow;
    // emitting `flowLabel: this.Label` here would duplicate that responsibility.
    sb.AppendLine("      saveOutputs,");
    sb.AppendLine($"      codeVersion: {codeVersionExpr}));");
  }
}
