using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Flowthru.Core.SourceGenerators.Step;

/// <summary>
/// Emits a <c>{StepClassName}_Metadata</c> companion record next to
/// every <c>[FlowthruStep]</c>-decorated static class. The companion
/// carries identification (class name, label) plus the
/// <c>StepTraits</c> taken from the attribute, so diagnostics tooling
/// and architecture tests can iterate every step in an assembly
/// without instantiating it.
/// </summary>
/// <remarks>
/// <para>
/// Per §2.4, the companion is the source-of-truth for per-step
/// metadata that doesn't fit inside <c>NodeTraits</c>. <c>NodeTraits</c>
/// stays universal; <c>StepTraits</c> is step-specific and lives on
/// the companion.
/// </para>
/// </remarks>
[Generator]
public sealed class StepMetadataGenerator : IIncrementalGenerator
{
  private const string AttributeFullName = "Flowthru.Step.FlowthruStepAttribute";

  /// <inheritdoc/>
  public void Initialize(IncrementalGeneratorInitializationContext context)
  {
    var candidates = context
      .SyntaxProvider.ForAttributeWithMetadataName(
        AttributeFullName,
        predicate: static (node, _) => node is ClassDeclarationSyntax,
        transform: static (ctx, _) => ExtractStepInfo(ctx)
      )
      .Where(static info => info != null)
      .Select(static (info, _) => info!);

    context.RegisterSourceOutput(candidates, static (ctx, info) => Emit(ctx, info));
  }

  private static StepInfo? ExtractStepInfo(GeneratorAttributeSyntaxContext ctx)
  {
    if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol) return null;

    var attribute = typeSymbol
      .GetAttributes()
      .FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == AttributeFullName);
    if (attribute is null) return null;

    string? label = null;
    var isIdempotent = false;
    var hasSideEffects = false;
    foreach (var named in attribute.NamedArguments)
    {
      switch (named.Key)
      {
        case "Label":
          label = named.Value.Value as string;
          break;
        case "IsIdempotent":
          isIdempotent = named.Value.Value is true;
          break;
        case "HasSideEffects":
          hasSideEffects = named.Value.Value is true;
          break;
      }
    }

    var ns = typeSymbol.ContainingNamespace.IsGlobalNamespace
      ? ""
      : typeSymbol.ContainingNamespace.ToDisplayString();

    return new StepInfo(
      Namespace: ns,
      ClassName: typeSymbol.Name,
      Label: label ?? typeSymbol.Name,
      IsIdempotent: isIdempotent,
      HasSideEffects: hasSideEffects
    );
  }

  private static void Emit(SourceProductionContext ctx, StepInfo info)
  {
    var sb = new StringBuilder();
    sb.AppendLine("// <auto-generated/>");
    sb.AppendLine("#nullable enable");
    sb.AppendLine();
    sb.AppendLine("using global::Flowthru.Step;");
    sb.AppendLine();
    if (!string.IsNullOrEmpty(info.Namespace))
    {
      sb.AppendLine($"namespace {info.Namespace};");
      sb.AppendLine();
    }
    sb.AppendLine($"/// <summary>Generated metadata companion for <see cref=\"{info.ClassName}\"/>.</summary>");
    sb.AppendLine($"public static class {info.ClassName}_Metadata");
    sb.AppendLine("{");
    sb.AppendLine($"  public const string ClassName = \"{Escape(info.ClassName)}\";");
    sb.AppendLine($"  public const string Label = \"{Escape(info.Label)}\";");
    sb.AppendLine();
    sb.AppendLine("  public static readonly global::Flowthru.Step.StepTraits Traits = new()");
    sb.AppendLine("  {");
    sb.AppendLine($"    IsIdempotent = {(info.IsIdempotent ? "true" : "false")},");
    sb.AppendLine($"    HasSideEffects = {(info.HasSideEffects ? "true" : "false")},");
    sb.AppendLine("  };");
    sb.AppendLine("}");

    var fileName = string.IsNullOrEmpty(info.Namespace)
      ? $"{info.ClassName}_Metadata.g.cs"
      : $"{info.Namespace}.{info.ClassName}_Metadata.g.cs";
    ctx.AddSource(fileName, SourceText.From(sb.ToString(), Encoding.UTF8));
  }

  private static string Escape(string value) =>
    value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}

internal sealed record StepInfo(
  string Namespace,
  string ClassName,
  string Label,
  bool IsIdempotent,
  bool HasSideEffects
);
