using Flowthru.Data;
using KedroSpaceflights.Data._07_ModelOutput.Schemas;

namespace KedroSpaceflights.Data;

/// <summary>
/// Model output data layer: Model predictions and scores.
/// Contains results generated by trained models during inference.
/// </summary>
public partial class Catalog
{
  /// <summary>
  /// Evaluation metrics for the trained regression model.
  /// </summary>
  public IItem<ModelMetrics> ModelMetrics =>
    CreateItem(
      () =>
        Items.Single.Json<ModelMetrics>(
          label: "ModelMetrics",
          filePath: $"{_basePath}/_07_ModelOutput/Datasets/model_metrics.json"
        )
    );

  /// <summary>
  /// Model predictions containing actual and predicted values from the test set.
  /// Used for generating confusion matrices and prediction accuracy visualizations.
  /// </summary>
  public IItem<IEnumerable<ModelPredictions>> ModelPredictions =>
    CreateItem(
      () =>
        Items.Enumerable.Json<ModelPredictions>(
          label: "ModelPredictions",
          filePath: $"{_basePath}/_07_ModelOutput/Datasets/model_predictions.json"
        )
    );
}
