using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Flowthru.Extensions.Python.SourceGenerators;

/// <summary>
/// Generates AddPythonStep overloads for FlowBuilder supporting up to 8 inputs and 8 outputs.
/// </summary>
/// <remarks>
/// <para>
/// <strong>Phase 5 implementation:</strong>
/// Mirrors FlowBuilderGenerator's combinatorial approach but for Python steps.
/// Each overload accepts executor and runtime parameters and delegates to PythonStepWrapper.
/// </para>
/// <para>
/// Sync-only in Phase 5 — async support deferred to Phase 6.
/// </para>
/// </remarks>
[Generator]
public class PythonStepGenerator : IIncrementalGenerator
{
  private const int MaxInputs = 8;
  private const int MaxOutputs = 8;

  public void Initialize(IncrementalGeneratorInitializationContext context)
  {
    // Run for any project that references Flowthru.Extensions.Python
    // (unlike FlowBuilderGenerator which only runs for the core Flowthru assembly)
    context.RegisterPostInitializationOutput(ctx => GenerateAddPythonStep(ctx));
  }

  private static void GenerateAddPythonStep(IncrementalGeneratorPostInitializationContext context)
  {
    var sb = new StringBuilder();

    // File header
    sb.AppendLine(
      """
      // <auto-generated/>
      #nullable enable

      using Flowthru.Data;
      using Flowthru.Extensions.Python.Execution;
      using Flowthru.Extensions.Python.Steps;
      using Flowthru.Extensions.Python.Runtime;
      using Flowthru.Flows;

      namespace Flowthru.Extensions.Python.Steps;

      public static partial class PythonStepFactory
      {
      """
    );

    // Generate overloads for all combinations except 1x1 (hand-written)
    for (int inputs = 1; inputs <= MaxInputs; inputs++)
    {
      for (int outputs = 1; outputs <= MaxOutputs; outputs++)
      {
        // Skip 1x1 - it's hand-written for clarity
        if (inputs == 1 && outputs == 1)
        {
          continue;
        }

        // Generate sync version only (Phase 5)
        GenerateAddPythonStep(sb, inputs, outputs);
        sb.AppendLine();
      }
    }

    sb.AppendLine("}");

    context.AddSource(
      "PythonStepFactory.Generated.cs",
      SourceText.From(sb.ToString(), Encoding.UTF8)
    );
  }

  private static void GenerateAddPythonStep(StringBuilder sb, int inputCount, int outputCount)
  {
    // Generate XML documentation
    GenerateXmlDoc(sb, inputCount, outputCount);

    // Generate type parameters and method signature
    var typeParams = GenerateTypeParameters(inputCount, outputCount);
    var inputParam = GenerateInputParameter(inputCount);
    var outputParam = GenerateOutputParameter(outputCount);

    // Input/Output tuple types for wrapper instantiation
    var inputTupleType = GenerateInputTupleType(inputCount);
    var outputTupleType = GenerateOutputTupleType(outputCount);

    sb.AppendLine(
      $$"""
        public static FlowBuilder AddPythonStep<{{typeParams}}>(
          this FlowBuilder builder,
          string label,
          string module,
          string function,
          {{inputParam}} input,
          {{outputParam}} output,
          IPythonExecutor executor,
          string description = ""
        )
        {
      """
    );

    // Generate input deconstruction if needed
    GenerateInputDeconstruction(sb, inputCount);

    // Generate output deconstruction if needed
    GenerateOutputDeconstruction(sb, outputCount);

    // Generate inputs and outputs lists for AddStep
    var inputsList = GenerateInputsList(inputCount);
    var outputsList = GenerateOutputsList(outputCount);

    // Parameter validation
    sb.AppendLine(
      """
          if (builder == null)
          {
            throw new System.ArgumentNullException(nameof(builder));
          }

          if (string.IsNullOrWhiteSpace(label))
          {
            throw new System.ArgumentException("Label cannot be null or whitespace.", nameof(label));
          }

          if (string.IsNullOrWhiteSpace(module))
          {
            throw new System.ArgumentException("Module name cannot be null or whitespace.", nameof(module));
          }

          if (string.IsNullOrWhiteSpace(function))
          {
            throw new System.ArgumentException("Function name cannot be null or whitespace.", nameof(function));
          }

          if (executor == null)
          {
            throw new System.ArgumentNullException(nameof(executor));
          }

      """
    );

    // Create wrapper with tuple types
    sb.AppendLine(
      $$"""
          var wrapper = new PythonStepWrapper<{{inputTupleType}}, {{outputTupleType}}>(executor, module, function);
          executor.ValidateStep(module, function);

          // Delegate to existing AddStep infrastructure
          return builder.AddStep(
            label: label,
            transform: wrapper.GetTransform(),
            input: input,
            output: output,
            description: description
          );
        }
      """
    );
  }

  private static void GenerateXmlDoc(StringBuilder sb, int inputCount, int outputCount)
  {
    sb.AppendLine(
      $"""
        /// <summary>
        /// Adds a Python step with {inputCount} input{(
        inputCount == 1 ? "" : "s"
      )} and {outputCount} output{(outputCount == 1 ? "" : "s")}.
        /// </summary>
      """
    );

    // Type parameter documentation
    for (int i = 1; i <= inputCount; i++)
    {
      sb.AppendLine($"  /// <typeparam name=\"TIn{i}\">Input type {i}</typeparam>");
    }
    for (int i = 1; i <= outputCount; i++)
    {
      sb.AppendLine($"  /// <typeparam name=\"TOut{i}\">Output type {i}</typeparam>");
    }

    // Parameter documentation
    sb.AppendLine(
      """
        /// <param name="builder">Flow builder instance</param>
        /// <param name="label">Unique identifier for this step</param>
        /// <param name="module">Dotted Python module name (e.g., "Flows.DataScience.train_model")</param>
        /// <param name="function">Python function name within the module</param>
        /// <param name="input">Catalog item or tuple of catalog items providing input data</param>
        /// <param name="output">Catalog item or tuple of catalog items to store output data</param>
        /// <param name="executor">Python executor for invoking the function</param>
        /// <param name="description">Optional step description</param>
        /// <returns>This builder for method chaining</returns>
      """
    );
  }

  private static string GenerateTypeParameters(int inputCount, int outputCount)
  {
    var parts = new List<string>();

    for (int i = 1; i <= inputCount; i++)
    {
      parts.Add($"TIn{i}");
    }
    for (int i = 1; i <= outputCount; i++)
    {
      parts.Add($"TOut{i}");
    }

    return string.Join(", ", parts);
  }

  private static string GenerateInputParameter(int inputCount)
  {
    if (inputCount == 1)
    {
      return "IItem<TIn1>";
    }

    var types = string.Join(", ", Enumerable.Range(1, inputCount).Select(i => $"IItem<TIn{i}>"));
    return $"({types})";
  }

  private static string GenerateOutputParameter(int outputCount)
  {
    if (outputCount == 1)
    {
      return "IItem<TOut1>";
    }

    var types = string.Join(", ", Enumerable.Range(1, outputCount).Select(i => $"IItem<TOut{i}>"));
    return $"({types})";
  }

  private static string GenerateInputTupleType(int inputCount)
  {
    if (inputCount == 1)
    {
      return "TIn1";
    }

    var types = string.Join(", ", Enumerable.Range(1, inputCount).Select(i => $"TIn{i}"));
    return $"({types})";
  }

  private static string GenerateOutputTupleType(int outputCount)
  {
    if (outputCount == 1)
    {
      return "TOut1";
    }

    var types = string.Join(", ", Enumerable.Range(1, outputCount).Select(i => $"TOut{i}"));
    return $"({types})";
  }

  private static void GenerateInputDeconstruction(StringBuilder sb, int inputCount)
  {
    if (inputCount <= 1)
    {
      return;
    }

    sb.Append("    var (");
    for (int i = 1; i <= inputCount; i++)
    {
      if (i > 1)
      {
        sb.Append(", ");
      }
      sb.Append($"input{i}");
    }
    sb.AppendLine(") = input;");
    sb.AppendLine();
  }

  private static void GenerateOutputDeconstruction(StringBuilder sb, int outputCount)
  {
    if (outputCount <= 1)
    {
      return;
    }

    sb.Append("    var (");
    for (int i = 1; i <= outputCount; i++)
    {
      if (i > 1)
      {
        sb.Append(", ");
      }
      sb.Append($"output{i}");
    }
    sb.AppendLine(") = output;");
    sb.AppendLine();
  }

  private static string GenerateInputsList(int inputCount)
  {
    if (inputCount == 1)
    {
      return "input";
    }

    return string.Join(", ", Enumerable.Range(1, inputCount).Select(i => $"input{i}"));
  }

  private static string GenerateOutputsList(int outputCount)
  {
    if (outputCount == 1)
    {
      return "output";
    }

    return string.Join(", ", Enumerable.Range(1, outputCount).Select(i => $"output{i}"));
  }
}
