using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Flowthru.Extensions.Python.SourceGenerators;

/// <summary>
/// Emits the multi-arity <c>AddPythonStep</c> overload matrix on the
/// <c>partial class PythonStepFactory</c> declared by hand for the
/// 1×1 case in <c>Flowthru.Step.Python.PythonStepFactory</c>.
/// Generates 1..8 inputs × 1..8 outputs (skipping the 1×1 cell that's
/// already hand-written for clarity).
/// </summary>
/// <remarks>
/// <para>
/// Each generated overload constructs a <c>PythonStep&lt;TIn,TOut&gt;</c>
/// directly — no wrapper, no synthetic <c>FlowStep</c>. That step is
/// then added to the <c>FlowBuilder</c> via the public
/// <c>FlowBuilder.Add(IStepNode)</c> entry. Construction is pure (no
/// IO) per the audit refactor; environmental checks land in
/// <c>PythonStepValidationHook</c> at pre-flight.
/// </para>
/// </remarks>
[Generator]
public class PythonStepGenerator : IIncrementalGenerator
{
  private const int MaxInputs = 8;
  private const int MaxOutputs = 8;

  /// <inheritdoc/>
  public void Initialize(IncrementalGeneratorInitializationContext context)
  {
    // These overloads are pre-compiled into Flowthru.Extensions.Python.dll, so
    // they must only be generated during the extension's own build — not for
    // consumer projects. Emitting them via the analyzer on consumers produces
    // duplicate partial-class declarations that cause CS0121 (ambiguous call)
    // at every AddPythonStep call site.
    context.RegisterSourceOutput(
      context.CompilationProvider,
      (ctx, compilation) =>
      {
        if (compilation.AssemblyName != "Flowthru.Extensions.Python") return;
        EmitMatrix(ctx);
      }
    );
  }

  private static void EmitMatrix(SourceProductionContext context)
  {
    var sb = new StringBuilder();

    sb.AppendLine(
      """
      // <auto-generated/>
      #nullable enable

      using global::Flowthru.Data.Catalog;
      using global::Flowthru.Step.Python;
      using global::Flowthru.Validation.Runtime;

      namespace Flowthru.Flow;

      public static partial class PythonStepFactory
      {
      """
    );

    for (int inputs = 1; inputs <= MaxInputs; inputs++)
    {
      for (int outputs = 1; outputs <= MaxOutputs; outputs++)
      {
        if (inputs == 1 && outputs == 1) continue;
        EmitOverload(sb, inputs, outputs);
        sb.AppendLine();
      }
    }

    sb.AppendLine("}");
    context.AddSource("PythonStepFactory.Generated.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
  }

  private static void EmitOverload(StringBuilder sb, int inputCount, int outputCount)
  {
    EmitXmlDoc(sb, inputCount, outputCount);

    var typeParams = TypeParams(inputCount, outputCount);
    var inputParam = InputParameter(inputCount);
    var outputParam = OutputParameter(outputCount);
    var inputTuple = InputTupleType(inputCount);
    var outputTuple = OutputTupleType(outputCount);

    sb.AppendLine(
      $$"""
        public static FlowBuilder AddPythonStep<{{typeParams}}>(
          this FlowBuilder builder,
          string label,
          string module,
          string function,
          {{inputParam}} input,
          {{outputParam}} output,
          IPythonExecutor executor,
          System.Collections.Generic.IReadOnlyList<ServiceRef>? services = null
        )
        {
          if (builder == null) throw new System.ArgumentNullException(nameof(builder));
          if (string.IsNullOrWhiteSpace(label))
            throw new System.ArgumentException("Label cannot be null or whitespace.", nameof(label));
          if (string.IsNullOrWhiteSpace(module))
            throw new System.ArgumentException("Module name cannot be null or whitespace.", nameof(module));
          if (string.IsNullOrWhiteSpace(function))
            throw new System.ArgumentException("Function name cannot be null or whitespace.", nameof(function));
          if (executor == null) throw new System.ArgumentNullException(nameof(executor));
        """
    );

    EmitInputDeconstruction(sb, inputCount);
    EmitOutputDeconstruction(sb, outputCount);

    var inputsListExpr = InputsListExpression(inputCount);
    var outputsListExpr = OutputsListExpression(outputCount);
    var loadInputsExpr = LoadInputsExpression(inputCount);
    var saveOutputsExpr = SaveOutputsExpression(outputCount, outputTuple);

    sb.AppendLine(
      $$"""
          var step = new global::Flowthru.Step.Python.PythonStep<{{inputTuple}}, {{outputTuple}}>(
            label: label,
            moduleName: module,
            functionName: function,
            transform: tin => executor.Invoke<{{inputTuple}}, {{outputTuple}}>(module, function, tin),
            inputs: new global::Flowthru.Data.Catalog.IItem[] { {{inputsListExpr}} },
            outputs: new global::Flowthru.Data.Catalog.IItem[] { {{outputsListExpr}} },
            loadInputs: () => {{loadInputsExpr}},
            saveOutputs: {{saveOutputsExpr}},
            serviceDependencies: services
            // FlowLabel is stamped centrally by FlowBuilder.Add via
            // IStepNode.OnAddedToFlow — generators no longer need to
            // thread the label through every constructor call.
          );
          return builder.Add(step);
        }
      """
    );
  }

  // ── Code-fragment helpers ─────────────────────────────────────────────

  private static string TypeParams(int inputCount, int outputCount)
  {
    var parts = new List<string>();
    for (int i = 1; i <= inputCount; i++) parts.Add($"TIn{i}");
    for (int i = 1; i <= outputCount; i++) parts.Add($"TOut{i}");
    return string.Join(", ", parts);
  }

  private static string InputParameter(int inputCount)
  {
    if (inputCount == 1) return "IItem<TIn1>";
    var types = string.Join(", ", Enumerable.Range(1, inputCount).Select(i => $"IItem<TIn{i}>"));
    return $"({types})";
  }

  private static string OutputParameter(int outputCount)
  {
    if (outputCount == 1) return "IItem<TOut1>";
    var types = string.Join(", ", Enumerable.Range(1, outputCount).Select(i => $"IItem<TOut{i}>"));
    return $"({types})";
  }

  private static string InputTupleType(int inputCount)
  {
    if (inputCount == 1) return "TIn1";
    return $"({string.Join(", ", Enumerable.Range(1, inputCount).Select(i => $"TIn{i}"))})";
  }

  private static string OutputTupleType(int outputCount)
  {
    if (outputCount == 1) return "TOut1";
    return $"({string.Join(", ", Enumerable.Range(1, outputCount).Select(i => $"TOut{i}"))})";
  }

  private static void EmitInputDeconstruction(StringBuilder sb, int inputCount)
  {
    if (inputCount <= 1) return;
    sb.Append("    var (");
    for (int i = 1; i <= inputCount; i++)
    {
      if (i > 1) sb.Append(", ");
      sb.Append($"input{i}");
    }
    sb.AppendLine(") = input;");
  }

  private static void EmitOutputDeconstruction(StringBuilder sb, int outputCount)
  {
    if (outputCount <= 1) return;
    sb.Append("    var (");
    for (int i = 1; i <= outputCount; i++)
    {
      if (i > 1) sb.Append(", ");
      sb.Append($"output{i}");
    }
    sb.AppendLine(") = output;");
  }

  private static string InputsListExpression(int inputCount)
  {
    if (inputCount == 1) return "input";
    return string.Join(", ", Enumerable.Range(1, inputCount).Select(i => $"input{i}"));
  }

  private static string OutputsListExpression(int outputCount)
  {
    if (outputCount == 1) return "output";
    return string.Join(", ", Enumerable.Range(1, outputCount).Select(i => $"output{i}"));
  }

  /// <summary>
  /// Build the <c>loadInputs</c> closure body. For arity 1 this is
  /// just <c>input.Load()</c>; for arity ≥ 2 it sequences each
  /// item's <c>Load()</c> in a single FlowIO LINQ chain that yields
  /// a typed value tuple.
  /// </summary>
  private static string LoadInputsExpression(int inputCount)
  {
    if (inputCount == 1) return "input.Load()";

    // from a in input1.Load() from b in input2.Load() ... select (a, b, ...)
    var sb = new StringBuilder();
    var letters = Enumerable.Range(0, inputCount).Select(i => $"v{i + 1}").ToArray();
    for (int i = 1; i <= inputCount; i++)
    {
      sb.Append($"from {letters[i - 1]} in input{i}.Load() ");
    }
    sb.Append($"select ({string.Join(", ", letters)})");
    return sb.ToString();
  }

  /// <summary>
  /// Build the <c>saveOutputs</c> closure body. For arity 1 this is
  /// just <c>out_ =&gt; output.Save(out_)</c>; for arity ≥ 2 it
  /// destructures the output tuple and chains each item's
  /// <c>Save</c> in a FlowIO sequence yielding <c>FlowUnit</c>.
  /// </summary>
  private static string SaveOutputsExpression(int outputCount, string outputTupleType)
  {
    if (outputCount == 1) return "out_ => output.Save(out_)";

    // out_ => { var (o1, o2, ...) = out_; return from _ in output1.Save(o1) from __ in output2.Save(o2) ... select FlowUnit.Default; }
    var letters = Enumerable.Range(0, outputCount).Select(i => $"o{i + 1}").ToArray();
    var dummies = Enumerable.Range(0, outputCount).Select(i => $"_x{i + 1}").ToArray();
    var sb = new StringBuilder();
    sb.Append("out_ => { var (");
    sb.Append(string.Join(", ", letters));
    sb.Append(") = out_; return ");
    for (int i = 1; i <= outputCount; i++)
    {
      sb.Append($"from {dummies[i - 1]} in output{i}.Save({letters[i - 1]}) ");
    }
    sb.Append("select global::Flowthru.Prelude.FlowUnit.Default; }");
    return sb.ToString();
  }

  // ── XML doc emission ──────────────────────────────────────────────────

  private static void EmitXmlDoc(StringBuilder sb, int inputCount, int outputCount)
  {
    sb.AppendLine(
      $"""
        /// <summary>
        /// Adds a Python step with {inputCount} input{(inputCount == 1 ? "" : "s")} and {outputCount} output{(outputCount == 1 ? "" : "s")}.
        /// Construction is pure — module-import, decorator-presence, and schema-agreement
        /// checks are deferred to the pre-flight <c>PythonStepValidationHook</c>.
        /// </summary>
      """
    );
    for (int i = 1; i <= inputCount; i++) sb.AppendLine($"  /// <typeparam name=\"TIn{i}\">Input type {i}.</typeparam>");
    for (int i = 1; i <= outputCount; i++) sb.AppendLine($"  /// <typeparam name=\"TOut{i}\">Output type {i}.</typeparam>");
    sb.AppendLine(
      """
        /// <param name="builder">Flow builder.</param>
        /// <param name="label">Unique step label.</param>
        /// <param name="module">Dotted Python module name.</param>
        /// <param name="function">Function name within the module.</param>
        /// <param name="input">Catalog item or tuple of catalog items providing input.</param>
        /// <param name="output">Catalog item or tuple of catalog items receiving output.</param>
        /// <param name="executor">Python executor (subprocess or in-process).</param>
        /// <param name="services">Optional declared service dependencies.</param>
      """
    );
  }
}
