using System;
using System.Collections.Generic;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Flowthru.Extensions.Python.SourceGenerators;

/// <summary>
/// Discovers Python files marked as <c>AdditionalFiles</c> in the
/// consuming project, parses every <c>@step(...)</c> decorator, and
/// emits a strongly-typed factory method per discovered step that
/// returns a <c>PythonStep&lt;TIn,TOut&gt;</c>. The schema names in
/// the decorator are resolved against the consuming compilation's
/// <c>[FlowthruSchema]</c>-decorated record types — unresolved names
/// surface as build errors (FT2xxx range), giving the user the
/// strongest possible compile-time agreement between the Python and
/// C# sides.
/// </summary>
/// <remarks>
/// <para>
/// Decorator authoring grammar — both forms accepted:
/// </para>
/// <code>
/// @step(inputs=[FeatureVectorSchema], outputs=[ModelWeightsSchema])
/// @step(inputs=["FeatureVectorSchema"], outputs=["ModelWeightsSchema"])
/// </code>
/// <para>
/// <strong>Generated factory shape:</strong>
/// </para>
/// <code>
/// public static IItem&lt;...&gt; TrainModel(IPythonExecutor executor, IItem&lt;TIn&gt; input, IItem&lt;TOut&gt; output)
///   =&gt; ...constructs PythonStep&lt;TIn,TOut&gt;...
/// </code>
/// </remarks>
[Generator]
[ExcludeFromCodeCoverage]
public class PythonStepFactoryGenerator : IIncrementalGenerator
{
  // Diagnostic identifiers — FT2xxx range (composition / wiring).
  private static readonly DiagnosticDescriptor SchemaNotFound = new(
    id: "FT2007",
    title: "Python decorator references unknown schema",
    messageFormat: "Schema '{0}' referenced in @step decorator is not a [FlowthruSchema]-decorated type in the consuming compilation",
    category: "Flowthru.Python",
    DiagnosticSeverity.Error,
    isEnabledByDefault: true
  );

  /// <inheritdoc/>
  public void Initialize(IncrementalGeneratorInitializationContext context)
  {
    // Discover all .py AdditionalFiles in the consuming project.
    var pythonSteps = context.AdditionalTextsProvider
      .Where(file => file.Path.EndsWith(".py"))
      .Select((file, ct) =>
      {
        var content = file.GetText(ct)?.ToString();
        if (string.IsNullOrEmpty(content)) return null;
        return ParsePythonStep(file.Path, content!);
      })
      .Where(step => step is not null)
      .Select((step, _) => step!)
      .Collect();

    // Combine with the compilation's [FlowthruSchema] type registry.
    var combined = context.CompilationProvider.Combine(pythonSteps);

    context.RegisterSourceOutput(combined, (ctx, pair) =>
    {
      var (compilation, steps) = pair;
      if (steps.Length == 0) return;

      var schemaIndex = BuildSchemaIndex(compilation);
      var sb = new StringBuilder();
      sb.AppendLine(
        """
        // <auto-generated/>
        #nullable enable

        using global::Flowthru.Data.Catalog;
        using global::Flowthru.Step.Python;
        using global::Flowthru.Validation.Runtime;

        namespace Flowthru.Extensions.Python.Generated;

        /// <summary>
        /// Compile-time-discovered factory methods for Python steps.
        /// Each method returns a <c>PythonStep&lt;TIn,TOut&gt;</c> ready
        /// to add to a <c>FlowBuilder</c> via <c>builder.Add(step)</c>.
        /// Schemas referenced in the @step decorator are resolved
        /// against the consuming project's [FlowthruSchema] types; a
        /// missing schema is a build error.
        /// </summary>
        public static class PythonSteps
        {
        """
      );

      foreach (var step in steps)
      {
        EmitFactory(ctx, sb, step!, schemaIndex);
      }

      sb.AppendLine("}");
      ctx.AddSource("PythonSteps.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    });
  }

  // ── Decorator parsing ─────────────────────────────────────────────────

  private static PythonStepInfo? ParsePythonStep(string filePath, string content)
  {
    // Match @step(inputs=[...], outputs=[...]) with optional services=[...].
    // The bracket contents are handed to ParseSchemaList which accepts
    // both string literals AND bare identifiers.
    var decoratorPattern =
      @"@step\s*\(\s*inputs\s*=\s*(\[[^\]]*\])\s*,\s*outputs\s*=\s*(\[[^\]]*\]|None)"
      + @"(?:\s*,\s*services\s*=\s*\[[^\]]*\])?\s*\)";
    var functionPattern = @"def\s+(\w+)\s*\(";

    var decoratorMatch = Regex.Match(content, decoratorPattern);
    if (!decoratorMatch.Success) return null;

    var functionMatch = Regex.Match(content.Substring(decoratorMatch.Index), functionPattern);
    if (!functionMatch.Success) return null;

    var functionName = functionMatch.Groups[1].Value;
    var inputsRaw = decoratorMatch.Groups[1].Value;
    var outputsRaw = decoratorMatch.Groups[2].Value;

    var inputs = ParseSchemaList(inputsRaw);
    var outputs = outputsRaw == "None" ? new List<string>() : ParseSchemaList(outputsRaw);
    var modulePath = DeriveModulePath(filePath);

    return new PythonStepInfo(functionName, modulePath, inputs, outputs);
  }

  /// <summary>
  /// Extract identifier or string-literal entries from the
  /// bracket-delimited decorator argument. Accepts both
  /// <c>["FeatureVectorSchema"]</c> and <c>[FeatureVectorSchema]</c>
  /// forms; the resulting list contains schema names regardless of
  /// authoring style.
  /// </summary>
  private static List<string> ParseSchemaList(string raw)
  {
    // Match either a quoted string or a bare identifier (incl. dotted).
    var pattern = @"""([^""]+)""|([A-Za-z_][A-Za-z0-9_\.]*)";
    var matches = Regex.Matches(raw, pattern);
    var result = new List<string>();
    foreach (Match m in matches)
    {
      if (m.Groups[1].Success)
      {
        var s = m.Groups[1].Value;
        if (!string.IsNullOrWhiteSpace(s)) result.Add(s);
      }
      else if (m.Groups[2].Success)
      {
        var s = m.Groups[2].Value;
        // Skip None and reserved-ish words.
        if (s == "None" || s == "True" || s == "False") continue;
        // Take the rightmost segment so `Module.Schema` resolves to `Schema`.
        var dotIdx = s.LastIndexOf('.');
        result.Add(dotIdx < 0 ? s : s.Substring(dotIdx + 1));
      }
    }
    return result;
  }

  private static string DeriveModulePath(string filePath)
  {
    // Walk from the first "Flows" or "Steps" anchor downward and
    // produce a dotted module path with the .py suffix stripped.
    var parts = filePath.Replace('\\', '/').Split('/');
    var relevant = new List<string>();
    var capturing = false;
    foreach (var part in parts)
    {
      if (part == "Flows" || capturing)
      {
        capturing = true;
        if (part.EndsWith(".py")) relevant.Add(part.Substring(0, part.Length - 3));
        else if (!string.IsNullOrEmpty(part)) relevant.Add(part);
      }
    }
    return string.Join(".", relevant);
  }

  // ── Schema lookup ─────────────────────────────────────────────────────

  /// <summary>
  /// Index every <c>[FlowthruSchema]</c>-decorated type in the
  /// compilation by its short name (the same name that the Python
  /// <c>@step(inputs=[Foo])</c> decorator captures via
  /// <c>__qualname__</c>). Used by <see cref="EmitFactory"/> to
  /// resolve decorator references and report unknowns as
  /// <see cref="SchemaNotFound"/> diagnostics.
  /// </summary>
  private static Dictionary<string, INamedTypeSymbol> BuildSchemaIndex(Compilation compilation)
  {
    var index = new Dictionary<string, INamedTypeSymbol>(StringComparer.Ordinal);
    var attrType = compilation.GetTypeByMetadataName("Flowthru.Data.Schema.FlowthruSchemaAttribute");
    if (attrType is null) return index;

    foreach (var type in EnumerateAllTypes(compilation.GlobalNamespace))
    {
      foreach (var attr in type.GetAttributes())
      {
        if (SymbolEqualityComparer.Default.Equals(attr.AttributeClass, attrType))
        {
          index[type.Name] = type;
          break;
        }
      }
    }
    return index;
  }

  private static IEnumerable<INamedTypeSymbol> EnumerateAllTypes(INamespaceSymbol root)
  {
    foreach (var member in root.GetMembers())
    {
      if (member is INamespaceSymbol ns)
      {
        foreach (var inner in EnumerateAllTypes(ns)) yield return inner;
      }
      else if (member is INamedTypeSymbol nt)
      {
        yield return nt;
        foreach (var nested in nt.GetTypeMembers()) yield return nested;
      }
    }
  }

  // ── Factory emission ──────────────────────────────────────────────────

  private static void EmitFactory(
    SourceProductionContext ctx,
    StringBuilder sb,
    PythonStepInfo step,
    Dictionary<string, INamedTypeSymbol> schemaIndex
  )
  {
    var inputTypes = new List<string>();
    var anyMissing = false;
    foreach (var schemaName in step.Inputs)
    {
      var typeRef = ResolveSchemaReference(ctx, schemaName, schemaIndex, ref anyMissing);
      inputTypes.Add(typeRef);
    }
    var outputTypes = new List<string>();
    foreach (var schemaName in step.Outputs)
    {
      var typeRef = ResolveSchemaReference(ctx, schemaName, schemaIndex, ref anyMissing);
      outputTypes.Add(typeRef);
    }
    if (anyMissing) return; // Diagnostics already emitted; skip generation.

    var inputTuple = JoinAsTupleOrSingle(inputTypes);
    var outputTuple = JoinAsTupleOrSingle(outputTypes);
    var methodName = ToPascalCase(step.FunctionName);

    sb.AppendLine(
      $$"""
        /// <summary>
        /// Compile-time factory for the Python step <c>{{step.ModulePath}}.{{step.FunctionName}}</c>.
        /// Schemas resolved at build time against [FlowthruSchema] types in this compilation.
        /// </summary>
        public static global::Flowthru.Step.Python.PythonStep<{{inputTuple}}, {{outputTuple}}> {{methodName}}(
          string label,
          global::Flowthru.Step.Python.IPythonExecutor executor,
          {{EmitInputItemParameters(inputTypes)}},
          {{EmitOutputItemParameters(outputTypes)}},
          System.Collections.Generic.IReadOnlyList<global::Flowthru.Validation.Runtime.ServiceRef>? services = null
        )
        {
          return new global::Flowthru.Step.Python.PythonStep<{{inputTuple}}, {{outputTuple}}>(
            label: label,
            moduleName: "{{step.ModulePath}}",
            functionName: "{{step.FunctionName}}",
            transform: tin => executor.Invoke<{{inputTuple}}, {{outputTuple}}>("{{step.ModulePath}}", "{{step.FunctionName}}", tin),
            inputs: new global::Flowthru.Data.Catalog.IItem[] { {{string.Join(", ", Enumerable.Range(1, inputTypes.Count).Select(i => $"input{i}"))}} },
            outputs: new global::Flowthru.Data.Catalog.IItem[] { {{string.Join(", ", Enumerable.Range(1, outputTypes.Count).Select(i => $"output{i}"))}} },
            loadInputs: () => {{LoadInputsExpr(inputTypes.Count)}},
            saveOutputs: {{SaveOutputsExpr(outputTypes.Count)}},
            serviceDependencies: services
          );
        }
        """
    );
    sb.AppendLine();
  }

  private static string ResolveSchemaReference(
    SourceProductionContext ctx,
    string schemaName,
    Dictionary<string, INamedTypeSymbol> schemaIndex,
    ref bool anyMissing
  )
  {
    // Wire-format primitives the user can write directly; map to canonical C# types.
    if (schemaName == "bytes") return "byte[]";
    if (schemaName == "str") return "string";
    if (schemaName == "int") return "int";
    if (schemaName == "float") return "double";
    if (schemaName == "bool") return "bool";
    if (schemaName == "object") return "object";

    if (!schemaIndex.TryGetValue(schemaName, out var symbol))
    {
      ctx.ReportDiagnostic(Diagnostic.Create(SchemaNotFound, location: Location.None, schemaName));
      anyMissing = true;
      return $"/* unresolved: {schemaName} */ object";
    }

    return $"global::System.Collections.Generic.IEnumerable<{symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>";
  }

  private static string JoinAsTupleOrSingle(List<string> types)
  {
    if (types.Count == 0) return "object";
    if (types.Count == 1) return types[0];
    return $"({string.Join(", ", types)})";
  }

  private static string EmitInputItemParameters(List<string> inputTypes) =>
    string.Join(", ", inputTypes.Select((t, i) => $"global::Flowthru.Data.Catalog.IItem<{t}> input{i + 1}"));

  private static string EmitOutputItemParameters(List<string> outputTypes) =>
    string.Join(", ", outputTypes.Select((t, i) => $"global::Flowthru.Data.Catalog.IItem<{t}> output{i + 1}"));

  private static string LoadInputsExpr(int n)
  {
    if (n == 1) return "input1.Load()";
    var letters = Enumerable.Range(1, n).Select(i => $"v{i}").ToArray();
    var sb = new StringBuilder();
    for (int i = 1; i <= n; i++) sb.Append($"from {letters[i - 1]} in input{i}.Load() ");
    sb.Append($"select ({string.Join(", ", letters)})");
    return sb.ToString();
  }

  private static string SaveOutputsExpr(int n)
  {
    if (n == 1) return "out_ => output1.Save(out_)";
    var letters = Enumerable.Range(1, n).Select(i => $"o{i}").ToArray();
    var dummies = Enumerable.Range(1, n).Select(i => $"_x{i}").ToArray();
    var sb = new StringBuilder();
    sb.Append("out_ => { var (");
    sb.Append(string.Join(", ", letters));
    sb.Append(") = out_; return ");
    for (int i = 1; i <= n; i++) sb.Append($"from {dummies[i - 1]} in output{i}.Save({letters[i - 1]}) ");
    sb.Append("select global::Flowthru.Prelude.FlowUnit.Default; }");
    return sb.ToString();
  }

  private static string ToPascalCase(string snakeCase)
  {
    var parts = snakeCase.Split('_');
    return string.Join("", parts.Select(p => p.Length == 0 ? p : char.ToUpperInvariant(p[0]) + p.Substring(1)));
  }

  /// <summary>Information about a Python step parsed from source.</summary>
  internal sealed class PythonStepInfo
  {
    public string FunctionName { get; }
    public string ModulePath { get; }
    public List<string> Inputs { get; }
    public List<string> Outputs { get; }

    public PythonStepInfo(string functionName, string modulePath, List<string> inputs, List<string> outputs)
    {
      FunctionName = functionName;
      ModulePath = modulePath;
      Inputs = inputs;
      Outputs = outputs;
    }
  }
}
