using Flowthru.Data;
using MagicAtlas.Data._07_ModelOutput.Schemas;

namespace MagicAtlas.Data;

/// <summary>
/// Model output data catalog entries (Layer 7).
/// Contains results generated by machine learning models.
/// </summary>
public partial class Catalog
{
  /// <summary>
  /// Oracle text embeddings generated from sentence-transformers model.
  /// </summary>
  public ICatalogEntry<IEnumerable<OracleTextEmbedding>> OracleTextEmbeddings =>
    GetOrCreateEntry(
      () =>
        CatalogEntries.Enumerable.Parquet<OracleTextEmbedding>(
          label: "OracleTextEmbeddings",
          filePath: $"{_basePath}/_07_ModelOutput/Datasets/oracle_text_embeddings.parquet"
        )
    );
}
