using Flowthru.Data;
using MagicAtlas.Data._07_ModelOutput.Schemas;

namespace MagicAtlas.Data;

/// <summary>
/// Model output data catalog entries (Layer 7).
/// Contains results generated by machine learning models.
/// </summary>
public partial class Catalog
{
  /// <summary>
  /// Oracle text embeddings generated from sentence-transformers model.
  /// </summary>
  public ICatalogEntry<IEnumerable<OracleTextEmbedding>> OracleTextEmbeddings =>
    GetOrCreateEntry(
      () =>
        CatalogEntries.Enumerable.Parquet<OracleTextEmbedding>(
          label: "OracleTextEmbeddings",
          filePath: $"{_basePath}/_07_ModelOutput/Datasets/oracle_text_embeddings.parquet"
        )
    );

  /// <summary>
  /// PCA-reduced embeddings generated from oracle text embeddings.
  /// Lower-dimensional representation for visualization and analysis.
  /// </summary>
  public ICatalogEntry<IEnumerable<OraclePcaEmbedding>> OraclePcaEmbeddings =>
    GetOrCreateEntry(
      () =>
        CatalogEntries.Enumerable.Parquet<OraclePcaEmbedding>(
          label: "OraclePcaEmbeddings",
          filePath: $"{_basePath}/_07_ModelOutput/Datasets/oracle_pca_embeddings.parquet"
        )
    );

  /// <summary>
  /// UMAP-reduced embeddings generated from oracle text embeddings.
  /// Manifold-learning-based dimensionality reduction that preserves both
  /// local and global structure for superior visualization.
  /// </summary>
  public ICatalogEntry<IEnumerable<OracleUmapEmbedding>> OracleUmapEmbeddings =>
    GetOrCreateEntry(
      () =>
        CatalogEntries.Enumerable.Parquet<OracleUmapEmbedding>(
          label: "OracleUmapEmbeddings",
          filePath: $"{_basePath}/_07_ModelOutput/Datasets/oracle_umap_embeddings.parquet"
        )
    );

  /// <summary>
  /// UMAP embeddings enhanced with card metadata for rich visualizations.
  /// Includes card name, color identity, and mana value joined to embedding coordinates.
  /// </summary>
  public ICatalogEntry<IEnumerable<EnhancedUmapEmbedding>> EnhancedUmapEmbeddings =>
    GetOrCreateEntry(
      () =>
        CatalogEntries.Enumerable.Parquet<EnhancedUmapEmbedding>(
          label: "EnhancedUmapEmbeddings",
          filePath: $"{_basePath}/_07_ModelOutput/Datasets/enhanced_umap_embeddings.parquet"
        )
    );
}
