using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Flowthru.Core.SourceGenerators;

/// <summary>
/// Generates AddStep overloads for FlowBuilder supporting up to 8 inputs and 8 outputs.
/// </summary>
[Generator]
public class FlowBuilderGenerator : IIncrementalGenerator
{
  private const int MaxInputs = 8;
  private const int MaxOutputs = 8;

  public void Initialize(IncrementalGeneratorInitializationContext context)
  {
    // Only run this generator for the Flowthru assembly itself, not consuming projects
    var assemblyName = context.CompilationProvider.Select((c, _) => c.AssemblyName);

    context.RegisterSourceOutput(
      assemblyName,
      (ctx, name) =>
      {
        if (name != "Flowthru.Core")
          return;

        GenerateAddStepOverloads(ctx);
      }
    );
  }

  private static void GenerateAddStepOverloads(SourceProductionContext context)
  {
    var sb = new StringBuilder();

    // File header
    sb.AppendLine(
      """
      // <auto-generated/>
      #nullable enable

      using Flowthru.Core.Graph;
      using Flowthru.Core.Steps;

      namespace Flowthru.Core.Flows;

      public partial class FlowBuilder
      {
      """
    );

    // Generate overloads for all combinations except 1x1 (hand-written)
    for (int inputs = 1; inputs <= MaxInputs; inputs++)
    {
      for (int outputs = 1; outputs <= MaxOutputs; outputs++)
      {
        // Skip 1x1 - it's hand-written for clarity
        if (inputs == 1 && outputs == 1)
        {
          continue;
        }

        // Generate both async and sync versions
        GenerateAddStepOverload(sb, inputs, outputs, isAsync: true);
        sb.AppendLine();
        GenerateAddStepOverload(sb, inputs, outputs, isAsync: false);
        sb.AppendLine();
      }
    }

    sb.AppendLine("}");

    context.AddSource("FlowBuilder.Generated.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
  }

  private static void GenerateAddStepOverload(
    StringBuilder sb,
    int inputCount,
    int outputCount,
    bool isAsync
  )
  {
    // Generate XML documentation
    GenerateXmlDoc(sb, inputCount, outputCount, isAsync);

    // Generate type parameters and method signature
    var typeParams = GenerateTypeParameters(inputCount, outputCount);
    var funcSignature = GenerateFuncSignature(inputCount, outputCount, isAsync);
    var inputParam = GenerateInputParameter(inputCount);
    var outputParam = GenerateOutputParameter(outputCount);

    sb.AppendLine(
      $$"""
        public FlowBuilder AddStep<{{typeParams}}>(
          string label,
          {{funcSignature}} transform,
          {{inputParam}} input,
          {{outputParam}} output,
          string description = ""
        )
        {
      """
    );

    // Generate input deconstruction
    GenerateInputDeconstruction(sb, inputCount);

    // Generate output deconstruction
    GenerateOutputDeconstruction(sb, outputCount);

    // Generate inputs and outputs lists
    var inputsList = GenerateInputsList(inputCount);
    var outputsList = GenerateOutputsList(outputCount);

    sb.AppendLine(
      $$"""
          var flowStep = new FlowStep(
            label: label,
            description: description,
            step: transform,
            inputs: new List<INode> { {{inputsList}} },
            outputs: new List<INode> { {{outputsList}} }
          );

          _flow.AddStep(flowStep);
          return this;
        }
      """
    );
  }

  private static void GenerateXmlDoc(
    StringBuilder sb,
    int inputCount,
    int outputCount,
    bool isAsync
  )
  {
    var asyncDesc = isAsync ? " (asynchronous transformation)" : " (synchronous transformation)";
    sb.AppendLine(
      $"""
        /// <summary>
        /// Adds a step with {inputCount} input{(
        inputCount == 1 ? "" : "s"
      )} and {outputCount} output{(outputCount == 1 ? "" : "s")}{asyncDesc}.
        /// </summary>
      """
    );

    // Type parameter documentation
    for (int i = 1; i <= inputCount; i++)
    {
      sb.AppendLine($"  /// <typeparam name=\"TIn{i}\">Input type {i}</typeparam>");
    }
    for (int i = 1; i <= outputCount; i++)
    {
      sb.AppendLine($"  /// <typeparam name=\"TOut{i}\">Output type {i}</typeparam>");
    }

    // Parameter documentation
    var transformDesc = isAsync
      ? "Asynchronous transformation function"
      : "Synchronous transformation function";
    sb.AppendLine(
      $"""
        /// <param name="label">Unique identifier for this step</param>
        /// <param name="transform">{transformDesc}</param>
        /// <param name="input">Catalog item or tuple of catalog items providing input data</param>
        /// <param name="output">Catalog item or tuple of catalog items to store output data</param>
        /// <param name="description">Optional description of the step's purpose</param>
        /// <returns>This builder for method chaining</returns>
      """
    );
  }

  private static string GenerateTypeParameters(int inputCount, int outputCount)
  {
    var parts = new List<string>();

    for (int i = 1; i <= inputCount; i++)
    {
      parts.Add($"TIn{i}");
    }
    for (int i = 1; i <= outputCount; i++)
    {
      parts.Add($"TOut{i}");
    }

    return string.Join(", ", parts);
  }

  private static string GenerateFuncSignature(int inputCount, int outputCount, bool isAsync)
  {
    var inputType =
      inputCount == 1
        ? "TIn1"
        : $"({string.Join(", ", Enumerable.Range(1, inputCount).Select(i => $"TIn{i}"))})";
    var outputType =
      outputCount == 1
        ? "TOut1"
        : $"({string.Join(", ", Enumerable.Range(1, outputCount).Select(i => $"TOut{i}"))})";

    var returnType = isAsync ? $"Task<{outputType}>" : outputType;
    return $"Func<{inputType}, {returnType}>";
  }

  private static string GenerateInputParameter(int inputCount)
  {
    if (inputCount == 1)
    {
      return "INode<TIn1>";
    }

    var types = string.Join(", ", Enumerable.Range(1, inputCount).Select(i => $"INode<TIn{i}>"));
    return $"({types})";
  }

  private static string GenerateOutputParameter(int outputCount)
  {
    if (outputCount == 1)
    {
      return "INode<TOut1>";
    }

    var types = string.Join(", ", Enumerable.Range(1, outputCount).Select(i => $"INode<TOut{i}>"));
    return $"({types})";
  }

  private static void GenerateInputDeconstruction(StringBuilder sb, int inputCount)
  {
    if (inputCount <= 1)
    {
      return;
    }

    sb.Append("    var (");
    for (int i = 1; i <= inputCount; i++)
    {
      if (i > 1)
      {
        sb.Append(", ");
      }
      sb.Append($"input{i}");
    }
    sb.AppendLine(") = input;");
    sb.AppendLine();
  }

  private static void GenerateOutputDeconstruction(StringBuilder sb, int outputCount)
  {
    if (outputCount <= 1)
    {
      return;
    }

    sb.Append("    var (");
    for (int i = 1; i <= outputCount; i++)
    {
      if (i > 1)
      {
        sb.Append(", ");
      }
      sb.Append($"output{i}");
    }
    sb.AppendLine(") = output;");
    sb.AppendLine();
  }

  private static string GenerateInputsList(int inputCount)
  {
    if (inputCount == 1)
    {
      return "input";
    }

    return string.Join(", ", Enumerable.Range(1, inputCount).Select(i => $"input{i}"));
  }

  private static string GenerateOutputsList(int outputCount)
  {
    if (outputCount == 1)
    {
      return "output";
    }

    return string.Join(", ", Enumerable.Range(1, outputCount).Select(i => $"output{i}"));
  }
}
