using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Flowthru.SourceGenerators;

/// <summary>
/// Generates multi-catalog RegisterPipeline overloads for FlowthruServiceBuilder,
/// supporting up to 8 catalog type parameters.
/// </summary>
[Generator]
public class ServiceBuilderGenerator : IIncrementalGenerator
{
  private const int MaxCatalogs = 8;

  public void Initialize(IncrementalGeneratorInitializationContext context)
  {
    // Only run this generator for the Flowthru.Core assembly itself
    var assemblyName = context.CompilationProvider.Select((c, _) => c.AssemblyName);

    context.RegisterSourceOutput(
      assemblyName,
      (ctx, name) =>
      {
        if (name != "Flowthru.Core")
          return;

        GenerateRegisterPipelineOverloads(ctx);
      }
    );
  }

  private static void GenerateRegisterPipelineOverloads(SourceProductionContext context)
  {
    var sb = new StringBuilder();

    sb.AppendLine(
      """
      // <auto-generated/>
      #nullable enable

      using Flowthru.Configuration;
      using Flowthru.Data;
      using Flowthru.Pipelines;
      using Microsoft.Extensions.Configuration;
      using Microsoft.Extensions.DependencyInjection;

      namespace Flowthru.Services;

      public sealed partial class FlowthruServiceBuilder
      {
      """
    );

    // Generate overloads for N = 2..MaxCatalogs catalogs (1-catalog is hand-written)
    for (int n = 2; n <= MaxCatalogs; n++)
    {
      // No-params overload: RegisterPipeline<TC1, ..., TCN>(label, Func<TC1, ..., TCN, Pipeline>)
      GenerateRegisterPipelineOverload(sb, n);
      sb.AppendLine();

      // Explicit-params overload: RegisterPipeline<TC1, ..., TCN, TParams>(label, func, TParams)
      GenerateRegisterPipelineWithParamsOverload(sb, n);
      sb.AppendLine();

      // Config-bound overload: RegisterPipelineWithConfiguration<TC1, ..., TCN, TParams>(label, func, section)
      GenerateRegisterPipelineWithConfigurationOverload(sb, n);
      sb.AppendLine();
    }

    sb.AppendLine("}");

    context.AddSource(
      "FlowthruServiceBuilder.Generated.cs",
      SourceText.From(sb.ToString(), Encoding.UTF8)
    );
  }

  private static void GenerateRegisterPipelineOverload(StringBuilder sb, int catalogCount)
  {
    var typeParams = GenerateCatalogTypeParams(catalogCount);
    var constraints = GenerateConstraints(catalogCount);
    var funcSignature = GenerateNoParamsFuncSignature(catalogCount);
    var resolvers = GenerateResolvers(catalogCount);

    sb.AppendLine(
      $$"""
        /// <summary>
        /// Registers a pipeline that draws from {{catalogCount}} catalogs (inline registration).
        /// </summary>
        {{GenerateTypeParamDocs(catalogCount)}}/// <param name="label">Unique pipeline name</param>
        /// <param name="pipeline">Factory function that creates the pipeline from catalogs</param>
        /// <returns>This builder for method chaining</returns>
        public FlowthruServiceBuilder RegisterPipeline<{{typeParams}}>(
          string label,
          {{funcSignature}} pipeline
        )
        {{constraints}}
        {
          var entry = new PipelineRegistrationEntry(
            label,
            sp => pipeline({{resolvers}})
          );
          _registrations.Add(entry);
          _lastRegistration = entry;
          return this;
        }
      """
    );
  }

  private static void GenerateRegisterPipelineWithParamsOverload(StringBuilder sb, int catalogCount)
  {
    var typeParams = GenerateCatalogTypeParams(catalogCount) + ", TParams";
    var constraints = GenerateConstraints(catalogCount);
    var funcSignature = GenerateWithParamsFuncSignature(catalogCount);
    var resolvers = GenerateResolvers(catalogCount);

    sb.AppendLine(
      $$"""
        /// <summary>
        /// Registers a pipeline that draws from {{catalogCount}} catalogs with explicit parameters (inline registration).
        /// </summary>
        {{GenerateTypeParamDocs(
        catalogCount
      )}}/// <typeparam name="TParams">The type of parameters the pipeline requires</typeparam>
        /// <param name="label">Unique pipeline name</param>
        /// <param name="pipeline">Factory function that creates the pipeline from catalogs and parameters</param>
        /// <param name="parameters">Parameter instance to pass to the pipeline</param>
        /// <returns>This builder for method chaining</returns>
        public FlowthruServiceBuilder RegisterPipeline<{{typeParams}}>(
          string label,
          {{funcSignature}} pipeline,
          TParams parameters
        )
        {{constraints}}
        {
          var entry = new PipelineRegistrationEntry(
            label,
            sp => pipeline({{resolvers}}, parameters)
          );
          _registrations.Add(entry);
          _lastRegistration = entry;
          return this;
        }
      """
    );
  }

  private static void GenerateRegisterPipelineWithConfigurationOverload(
    StringBuilder sb,
    int catalogCount
  )
  {
    var typeParams = GenerateCatalogTypeParams(catalogCount) + ", TParams";
    var catalogConstraints = GenerateConstraints(catalogCount);
    var funcSignature = GenerateWithParamsFuncSignature(catalogCount);
    var resolvers = GenerateResolvers(catalogCount);

    sb.AppendLine(
      $$"""
        /// <summary>
        /// Registers a pipeline that draws from {{catalogCount}} catalogs with parameters loaded from configuration.
        /// Call UseConfiguration() before this method.
        /// </summary>
        {{GenerateTypeParamDocs(
        catalogCount
      )}}/// <typeparam name="TParams">The type of parameters the pipeline requires</typeparam>
        /// <param name="label">Unique pipeline name</param>
        /// <param name="pipeline">Factory function that creates the pipeline from catalogs and parameters</param>
        /// <param name="configurationSection">Configuration section path (e.g. "Flowthru:Pipelines:MyPipeline")</param>
        /// <returns>This builder for method chaining</returns>
        public FlowthruServiceBuilder RegisterPipelineWithConfiguration<{{typeParams}}>(
          string label,
          {{funcSignature}} pipeline,
          string configurationSection
        )
        {{catalogConstraints}}
            where TParams : class, new()
        {
          if (_configuration == null)
          {
            throw new System.InvalidOperationException(
              "Configuration has not been set up. Call UseConfiguration() before RegisterPipelineWithConfiguration()."
            );
          }
          var parameters = _configuration.GetValidated<TParams>(configurationSection);
          var entry = new PipelineRegistrationEntry(
            label,
            sp => pipeline({{resolvers}}, parameters)
          );
          _registrations.Add(entry);
          _lastRegistration = entry;
          return this;
        }
      """
    );
  }

  private static string GenerateCatalogTypeParams(int catalogCount) =>
    string.Join(", ", Enumerable.Range(1, catalogCount).Select(i => $"TC{i}"));

  private static string GenerateConstraints(int catalogCount)
  {
    var constraints = Enumerable
      .Range(1, catalogCount)
      .Select(i => $"    where TC{i} : DataCatalogBase");
    return string.Join("\n", constraints);
  }

  private static string GenerateNoParamsFuncSignature(int catalogCount)
  {
    var typeArgs = string.Join(
      ", ",
      Enumerable.Range(1, catalogCount).Select(i => $"TC{i}").Append("Pipeline")
    );
    return $"Func<{typeArgs}>";
  }

  private static string GenerateWithParamsFuncSignature(int catalogCount)
  {
    var typeArgs = string.Join(
      ", ",
      Enumerable.Range(1, catalogCount).Select(i => $"TC{i}").Append("TParams").Append("Pipeline")
    );
    return $"Func<{typeArgs}>";
  }

  private static string GenerateResolvers(int catalogCount) =>
    string.Join(
      ", ",
      Enumerable.Range(1, catalogCount).Select(i => $"sp.GetRequiredService<TC{i}>()")
    );

  private static string GenerateTypeParamDocs(int catalogCount) =>
    string.Join(
      "\n",
      Enumerable
        .Range(1, catalogCount)
        .Select(i => $"  /// <typeparam name=\"TC{i}\">Catalog type {i}</typeparam>")
    ) + "\n";
}
