using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Flowthru.SourceGenerators;

/// <summary>
/// Generates AddNode overloads for PipelineBuilder supporting up to 8 inputs and 8 outputs.
/// </summary>
[Generator]
public class PipelineBuilderGenerator : IIncrementalGenerator
{
  private const int MaxInputs = 8;
  private const int MaxOutputs = 8;

  public void Initialize(IncrementalGeneratorInitializationContext context)
  {
    // Only run this generator for the Flowthru assembly itself, not consuming projects
    var assemblyName = context.CompilationProvider.Select((c, _) => c.AssemblyName);

    context.RegisterSourceOutput(
      assemblyName,
      (ctx, name) =>
      {
        if (name != "Flowthru")
          return;

        GenerateAddNodeOverloads(ctx);
      }
    );
  }

  private static void GenerateAddNodeOverloads(SourceProductionContext context)
  {
    var sb = new StringBuilder();

    // File header
    sb.AppendLine(
      """
      // <auto-generated/>
      #nullable enable

      using Flowthru.Data;
      using Flowthru.Nodes;

      namespace Flowthru.Pipelines;

      public partial class PipelineBuilder
      {
      """
    );

    // Generate overloads for all combinations except 1x1 (hand-written)
    for (int inputs = 1; inputs <= MaxInputs; inputs++)
    {
      for (int outputs = 1; outputs <= MaxOutputs; outputs++)
      {
        // Skip 1x1 - it's hand-written for clarity
        if (inputs == 1 && outputs == 1)
        {
          continue;
        }

        GenerateAddNodeOverload(sb, inputs, outputs);
        sb.AppendLine();
      }
    }

    sb.AppendLine("}");

    context.AddSource(
      "PipelineBuilder.Generated.cs",
      SourceText.From(sb.ToString(), Encoding.UTF8)
    );
  }

  private static void GenerateAddNodeOverload(StringBuilder sb, int inputCount, int outputCount)
  {
    // Generate XML documentation
    GenerateXmlDoc(sb, inputCount, outputCount);

    // Generate type parameters and method signature
    var typeParams = GenerateTypeParameters(inputCount, outputCount);
    var funcSignature = GenerateFuncSignature(inputCount, outputCount);
    var inputParam = GenerateInputParameter(inputCount);
    var outputParam = GenerateOutputParameter(outputCount);

    sb.AppendLine(
      $$"""
        public PipelineBuilder AddNode<{{typeParams}}>(
          string label,
          {{funcSignature}} transform,
          {{inputParam}} input,
          {{outputParam}} output,
          string description = ""
        )
        {
      """
    );

    // Generate input deconstruction
    GenerateInputDeconstruction(sb, inputCount);

    // Generate output deconstruction
    GenerateOutputDeconstruction(sb, outputCount);

    // Generate inputs and outputs lists
    var inputsList = GenerateInputsList(inputCount);
    var outputsList = GenerateOutputsList(outputCount);

    sb.AppendLine(
      $$"""
          var pipelineNode = new PipelineNode(
            label: label,
            description: description,
            node: transform,
            inputs: new List<ICatalogEntry> { {{inputsList}} },
            outputs: new List<ICatalogEntry> { {{outputsList}} }
          );

          _pipeline.AddNode(pipelineNode);
          return this;
        }
      """
    );
  }

  private static void GenerateXmlDoc(StringBuilder sb, int inputCount, int outputCount)
  {
    sb.AppendLine(
      $"""
        /// <summary>
        /// Adds a node with {inputCount} input{(
        inputCount == 1 ? "" : "s"
      )} and {outputCount} output{(outputCount == 1 ? "" : "s")}.
        /// </summary>
      """
    );

    // Type parameter documentation
    for (int i = 1; i <= inputCount; i++)
    {
      sb.AppendLine($"  /// <typeparam name=\"TIn{i}\">Input type {i}</typeparam>");
    }
    for (int i = 1; i <= outputCount; i++)
    {
      sb.AppendLine($"  /// <typeparam name=\"TOut{i}\">Output type {i}</typeparam>");
    }

    // Parameter documentation
    sb.AppendLine(
      """
        /// <param name="label">Unique identifier for this node</param>
        /// <param name="transform">Transformation function</param>
        /// <param name="input">Catalog entry or tuple of catalog entries providing input data</param>
        /// <param name="output">Catalog entry or tuple of catalog entries to store output data</param>
        /// <param name="description">Optional description of the node's purpose</param>
        /// <returns>This builder for method chaining</returns>
      """
    );
  }

  private static string GenerateTypeParameters(int inputCount, int outputCount)
  {
    var parts = new List<string>();

    for (int i = 1; i <= inputCount; i++)
    {
      parts.Add($"TIn{i}");
    }
    for (int i = 1; i <= outputCount; i++)
    {
      parts.Add($"TOut{i}");
    }

    return string.Join(", ", parts);
  }

  private static string GenerateFuncSignature(int inputCount, int outputCount)
  {
    var inputType =
      inputCount == 1
        ? "TIn1"
        : $"({string.Join(", ", Enumerable.Range(1, inputCount).Select(i => $"TIn{i}"))})";
    var outputType =
      outputCount == 1
        ? "TOut1"
        : $"({string.Join(", ", Enumerable.Range(1, outputCount).Select(i => $"TOut{i}"))})";

    return $"Func<{inputType}, Task<{outputType}>>";
  }

  private static string GenerateInputParameter(int inputCount)
  {
    if (inputCount == 1)
    {
      return "ICatalogEntry<TIn1>";
    }

    var types = string.Join(
      ", ",
      Enumerable.Range(1, inputCount).Select(i => $"ICatalogEntry<TIn{i}>")
    );
    return $"({types})";
  }

  private static string GenerateOutputParameter(int outputCount)
  {
    if (outputCount == 1)
    {
      return "ICatalogEntry<TOut1>";
    }

    var types = string.Join(
      ", ",
      Enumerable.Range(1, outputCount).Select(i => $"ICatalogEntry<TOut{i}>")
    );
    return $"({types})";
  }

  private static void GenerateInputDeconstruction(StringBuilder sb, int inputCount)
  {
    if (inputCount <= 1)
    {
      return;
    }

    sb.Append("    var (");
    for (int i = 1; i <= inputCount; i++)
    {
      if (i > 1)
      {
        sb.Append(", ");
      }
      sb.Append($"input{i}");
    }
    sb.AppendLine(") = input;");
    sb.AppendLine();
  }

  private static void GenerateOutputDeconstruction(StringBuilder sb, int outputCount)
  {
    if (outputCount <= 1)
    {
      return;
    }

    sb.Append("    var (");
    for (int i = 1; i <= outputCount; i++)
    {
      if (i > 1)
      {
        sb.Append(", ");
      }
      sb.Append($"output{i}");
    }
    sb.AppendLine(") = output;");
    sb.AppendLine();
  }

  private static string GenerateInputsList(int inputCount)
  {
    if (inputCount == 1)
    {
      return "input";
    }

    return string.Join(", ", Enumerable.Range(1, inputCount).Select(i => $"input{i}"));
  }

  private static string GenerateOutputsList(int outputCount)
  {
    if (outputCount == 1)
    {
      return "output";
    }

    return string.Join(", ", Enumerable.Range(1, outputCount).Select(i => $"output{i}"));
  }
}
